
var f_actor = [
	'header_type',
	'obj_type', 'lang',
	'header_public',
	'header_actor',
	'header_sect_name',
	'contributor_type', 
	//'lang',
	'name',
	'person_titles',
//	'name_other',
	'name_uniform',
	'ea_date_start',
	'ea_date_end',
	//'contributors_all',
	'comment_simple',

	'header_sect_subjects_urls',
	'subject',
	'url_rel',
	'header_sect_info',
	'note_generic_m',
	//'description_abstract',
//	'description',
	'header_relations',
	'relations_folder',
	'relations_all',

	'header_private',
	'comment_simple_internal',
	//'header_sect_priv_info',
	'status_comment',
	'header_status',
	'status',
	];
