

var f_book2 = [
	'header_type',
	'obj_type', 'lang','country_code',
	'header_public',
	'header_manifestation',
	'header_sect_title',
	//'lang',
	'title_ro',
	'isbn',
	'title_statement_title',
	'marc_edition_statement',
	//'subtitle',
	//'marc_title_statement_remainder',
	'title_uniform',
	'isbd_series_title_proper',
	'contributors_all',
	'header_sect_edition_with_add','header_edition',
	//'publication_statement',
	//'header_sect_edition',
	//'publisher',
	//'publishers_all',
	//'publication_place',
	//'date_orgissued',
	//'pages_cardinality',
	//'dimensions_2',
	'header_sect_subjects_urls',
	'subject',
	'url_rel',
//	'url_org',
	'header_sect_info',
	'pages_cardinality',
	'dimensions_2',
	'note_generic_m',

	//'description_abstract',
	//'description',
	'isis_record',
	'ddc',
	'header_relations',
	'relations_folder',
	'relations_all',


	//'header_works_with_add','header_work',
	'header_works','works_all',
	'header_private',
//	'header_collection',
//	'collection_place',
//	'collection_name',
	'header_sect_priv_info',
	'origin_comment',
	'status_comment',
	'header_status',
	'status',
	];
