var contributor_publication_manif_map = {
	'ea:manif:Publisher_Name' : 'Εκδότης',
	'ea:manif:Distribution_Name' : 'Διαθέτης',
	'ea:manif:Production_Name' : 'Παραγωγός',
	'ea:manif:Manufactur_Name' : 'Κατασκευαστής',
};

var contributor_manif_type_map = {
	'ea:manif:editorVersion' : 'Επιμελητής έκδοσης',
	'ea:manif:authorPreface' : 'Συγγραφέας Προλόγου',
	'ea:manif:admissionAuthor' : 'Συγγραφέας Εισαγωγής',
	'ea:manif:distributor' : 'Διαθέτης',
	'ea:manif:filmDistributor' : 'Διαθέτης κινηματογραφικών ταινιών',
	'ea:manif:publisher' : 'Εκδότης',
	'ea:manif:broadcaster' : 'Εκφωνητής',
	'ea:manif:manufacturer' : 'Κατασκευαστής',
	'ea:manif:lithographer' : 'Λιθογράφος',
	'ea:manif:etcher' : 'Οξυγράφος',
	'ea:manif:bookDesigner' : 'Σχεδιαστής βιβλίου',
	'ea:manif:printer' : 'Τυπογράφος',
	'ea:manif:engraver' : 'Χαράκτης',
	'ea:manif:brailleEmbosser' : 'Braille embosser',
	'ea:manif:caster' : 'Caster',
	'ea:manif:collotyper' : 'Collotyper',
	'ea:manif:platemaker' : 'Platemaker',
	'ea:manif:printmaker' : 'Printmaker',
};

var contributor_work_type_map = {
	'ea:work:authorWork' : 'Συγγραφέας',
	'ea:work:dedicateeWork' : 'Αποδέκτης Αφιέρωσης',
	'ea:work:sender' : 'Αποστολέας',
	'ea:work:landscapeArchitectWork' : 'Αρχιτέκτονας τοπίου',
	'ea:work:architectWork' : 'Αρχιτέκτων',
	'ea:work:sculptorWork' : 'Γλύπτης',
	'ea:work:directorOfPhotographyWork' : 'Διευθυντής φωτογραφίας',
	'ea:work:organizer' : 'Διοργανωτής',
	'ea:work:judgeWork' : 'Δικαστής',
	'ea:work:donor' : 'Δωρητής',
	'ea:work:defendantWork' : 'Εναγόμενος',
	'ea:work:plaintiffWork' : 'Ενάγων',
	'ea:work:editorWork' : 'Επιμελητής',
	'ea:work:researcher' : 'Ερευνητής',
	'ea:work:productionCompanyWork' : 'Εταιρεία παραγωγής',
	'ea:work:inventorWork' : 'Εφευρέτης',
	'ea:work:hostInstitutionWork' : 'Ινστιτούτο φιλοξενίας',
	'ea:work:degreeGrantingInstitutionWork' : 'Ινστιτούτο χορήγησης πτυχίου',
	'ea:work:artistWork' : 'Καλλιτέχνης',
	'ea:work:filmmakerWork' : 'Κινηματογραφιστής',
	'ea:work:interviewerWork' : 'Λαμβάνων συνέντευξη',
	'ea:work:librettistWork' : 'Λιμπερίστας',
	'ea:work:issuingBodyWork' : 'Οργανισμός έκδοσης',
	'ea:work:sponsoringBodyWork' : 'Οργανισμός χορηγίας',
	'ea:work:producerWork' : 'Παραγωγός',
	'ea:work:filmProducerWork' : 'Παραγωγός κινηματογραφικής ταινίας',
	'ea:work:radioProducerWork' : 'Παραγωγός ραδιοφωνικού προγράμματος',
	'ea:work:televisionProducerWork' : 'Παραγωγός τηλεοπτικού προγράμματος',
	'ea:work:recipient' : 'Παραλήπτης',
	'ea:work:Interviewee' : 'Παραχωρών συνέντευξη',
	'ea:work:programmerWork' : 'Προγραμματιστής',
	'ea:work:screenwriterWork' : 'Σεναριογράφος',
	'ea:work:directorWork' : 'Σκηνοθέτης',
	'ea:work:filmDirectorWork' : 'Σκηνοθέτης κινηματογραφικής ταινίας',
	'ea:work:radioDirectorWork' : 'Σκηνοθέτης ραδιοφωνικού προγράμματος',
	'ea:work:televisionDirectorWork' : 'Σκηνοθέτης τηλεοπτικού προγράμματος',
	'ea:work:lyricistWork' : 'Στιχουργός',
	'ea:work:admissionAuthor' : 'Συγγραφέας εισαγωγής',
	'ea:work:authorPreface' : 'Συγγραφέας προλόγου',
	'ea:work:thesisAdvisor' : 'Σύμβουλος διατριβής',
	'ea:work:congress' : 'Συνέδριο',
	'ea:work:co-organizer' : 'Συνδιοργανωτής',
	'ea:work:composerWork' : 'Συνθέτης',
	'ea:work:compilerWork' : 'Συντάκτης',
	'ea:work:designerWork' : 'Σχεδιαστής',
	'ea:work:honoureeWork' : 'Τιμώμενος',
	'ea:work:photographerWork' : 'Φωτογράφος',
	'ea:work:cartographerWork' : 'Χαρτογράφος ',
	'ea:work:choreographerWork' : 'Χορογράφος',
	'ea:work:courtGovernedWork' : 'Court governed',
	'ea:work:enactingJurisdictionWork' : 'Enacting jurisdiction ',
	'ea:work:jurisdictionGovernedWork' : 'Jurisdiction governed ',
	'ea:work:praesesWork' : 'Praeses ',
	'ea:work:respondentWork' : 'Respondent',

};

var contributor_express_type_map = {
'ea:expres:translator' : 'Μεταφραστής',
'ea:expres:narrator' : 'Αφηγητής',
'ea:expres:teacher' : 'Δάσκαλος',
'ea:expres:arrangerOfMusic' : 'Διασκευαστής μουσικής',
'ea:expres:conductor' : 'Διευθυντής Ορχήστρας',
'ea:expres:illustrator' : 'Εικονογράφος',
'ea:expres:cinematographer' : 'Εικονολήπτης',
'ea:expres:editor' : 'Επιμελητής',
'ea:expres:editorOfMovingImageWork' : 'Επιμελητής Work κινούμενης εικόνας',
'ea:expres:editorOfCompilation' : 'Επιμελητής συλλογής',
'ea:expres:singer' : 'Ερμηνευτής - τραγουδιστής',
'ea:expres:performer' : 'Ηθοποιός / Εκτελεστής',
'ea:expres:artDirector' : 'Καλλιτεχνικός διευθυντής',
'ea:expres:puppeteer' : 'Κουκλοπαίκτης',
'ea:expres:interviewer' : 'Λαμβάνων συνέντευξη',
'ea:expres:transcriber' : 'Μεταγραφέας',
'ea:expres:recordingEngineer' : 'Μηχανικός εγγραφής',
'ea:expres:speaker' : 'Ομιλητής',
'ea:expres:instrumentalist' : 'Οργανοπαίκτης',
'ea:expres:storyteller' : 'Παραμυθάς',
'ea:expres:interviewee' : 'Παραχωρών συνέντευξη',
'ea:expres:presenter' : 'Παρουσιαστής',
'ea:expres:host' : 'Παρουσιαστής εκπομπής',
'ea:expres:onScreenPresenter' : 'Παρουσιαστής οθόνης',
'ea:expres:writerOfAddedText' : 'Συγγραφέας πρόσθετου κειμένου',
'ea:expres:writerOfAddedCommentary' : 'Συγγραφέας πρόσθετου σχολιασμού',
'ea:expres:writerOfAddedLyrics' : 'Συγγραφέας πρόσθετων στίχων',
'ea:expres:composer' : 'Συνθέτης',
'ea:expres:composerOfIncidentalMusic' : 'Συνθέτης Incidental Music',
'ea:expres:composerOfMusicForSilentFilm' : 'Συνθέτης μουσικής βωβού κινηματογράφου',
'ea:expres:composerOfMusicForSoundFilm' : 'Συνθέτης μουσικής για ηχητική κινηματογραφική ταινία',
'ea:expres:composerOfAdditionalMusic' : 'Συνθέτης πρόσθετης μουσικής',
'ea:expres:productionDesigner' : 'Σχεδιαστής παραγωγής',
'ea:expres:commentator' : 'Σχολιαστής - Ερμηνευτής',
'ea:expres:surveyor' : 'Τοπογράφος',
'ea:expres:dancer' : 'Χορευτής',
'ea:expres:choreographer' : 'Χορογράφος',
'ea:expres:photographer' : 'Φωτογράφος',
'ea:expres:abridger' : 'Abridger',
'ea:expres:animator' : 'Animator',
'ea:expres:costumeDesigner' : 'Costume designer',
'ea:expres:courtReporter' : 'Court reporter ',
'ea:expres:draftsman' : 'Draftsman',
'ea:expres:moderator' : 'Moderator',
'ea:expres:musicalDirector' : 'Musical director',
'ea:expres:panelist' : 'Panelist (μέλος προγράμματος)',
'ea:expres:recordist' : 'Recordist',
'ea:expres:stageDirector' : 'Stage director',
}


var contributor_item_type_map = {
'ea:item:dedicateeOfItem' : 'Αποδέκτης Αφιέρωσης',
'ea:item:inscriberItem' : 'Αφιερωτής',
'ea:item:binderItem' : 'Βιβλιοδέτης',
'ea:item:illuminatorItem' : 'Διακοσμητής χειρογράφου',
'ea:item:donorItem' : 'Δωρητής',
'ea:item:curatorItem' : 'Επιμελητής συλλογής, έκθεσης κλπ.',
'ea:item:depositorItem' : 'Καταθέτης',
'ea:item:collectionRegistrarItem' : 'Καταχωρητής συλλογής',
'ea:item:ownerItem' : 'Κάτοχος / ιδιοκτήτης',
'ea:item:formerOwnerItem' : 'Προηγούμενος κάτοχος / ιδιοκτήτης',
'ea:item:sellerItem' : 'Πωλητής',
'ea:item:collectorItem' : 'Συλλέκτης',
'ea:item:honoureeOfItem' : 'Τιμώμενος στο Item',
'ea:item:currentOwnerItem' : 'Τρέχον κάτοχος / ιδιοκτήτης',
'ea:item:custodianItem' : 'Φύλακας',
'ea:item:autographerItem' : 'Autographer',
'ea:item:restorationistItem' : 'Restorationist',
}


var relation_work_derivative_map = {
	'ea:relation:basedOnWork' : 'Βασισμένο στο Work',
	'ea:relation:derivativeWork' : 'Παράγωγο  Work',
	'ea:relation:musicalVariationsBasedOnWork' : 'Μουσική παραλλαγή βασισμένη στο Work',
	'ea:relation:musicalVariationsWork' : 'Μουσική παραλλαγή  Work',
	'ea:relation:abridgementOfWork' : 'Επιτομή του Work',
	'ea:relation:abridgedAsWork' : 'Επιτομή στο Work',
	'ea:relation:digestOfWork' : 'Digest του Work',
	'ea:relation:digestWork' : 'Digest Work',
	'ea:relation:adaptationOfWork' : 'Προσαρμογή του Work',
	'ea:relation:dramatizationOfWork' : 'Δραματοποίηση του Work',
	'ea:relation:verseAdaptationOfWork' : 'Στιχουργική προσαρμογή  του Work',
	'ea:relation:motionPictureAdaptationOfWork' : 'Κινηματογραφική προσαρμογή του Work',
	'ea:relation:novelizationOfWork' : 'Προσαρμογή σε μυθιστόρημα  του Work',
	'ea:relation:televisionAdaptationOfWork' : 'Τηλεοπτική προσαρμογή του Work',
	'ea:relation:radioAdaptationOfWork' : 'Ραδιοφωνική προσαρμογή του Work',
	'ea:relation:screenplayBasedOnWork' : 'Σενάριο βασισμένο στο Work',
	'ea:relation:radioScriptBasedOnWork' : 'Είναι Ραδιοφωνικό Σενάριο βασισμένο στο Work',
	'ea:relation:videoAdaptationOfWork' : 'Προσαρμογή Video του Work',
	'ea:relation:musicalTheatreAdaptationOfWork' : 'Προσαρμογή σε μουσικό  θέατρο  του Work ',
	'ea:relation:operaAdaptationOf' : 'Προσαρμογή σε όπερα του Work',
	'ea:relation:motionPictureScreenplayBasedOnWork' : 'Σενάριο κινηματογραφικής ταινίας βασισμένο στο Work',
	'ea:relation:televisionScreenplayBasedOnWork' : 'Τηλεοπτικό σενάριο βασισμένο στο Work',
	'ea:relation:videoScreenplayBasedOnWork' : 'Σενάριο για Video βασισμένο στο Work',
	'ea:relation:adaptedAsWork' : 'Προσαρμόστηκε στο Work',
	'ea:relation:dramatizedAsWork' : 'Δραματοποιήθηκε στο Work',
	'ea:relation:verseAdaptationWork' : 'Στιχουργική προσαρμογή στο Work',
	'ea:relation:adaptedAsAMotionPictureWork' : 'Προσαρμόστηκε ως Work Κινηματογραφικής ταινίας',
	'ea:relation:novelizationWork' : 'Προσαρμόστηκε ως μυθιστόρημα στο Work',
	'ea:relation:adaptedAsATelevisionProgrammeWork' : 'Προσαρμόστηκε ως Work τηλεοπτικού προγράμματος',
	'ea:relation:adaptedAsARadioProgrammeWork' : 'Προσαρμόστηκε ως  Work ραδιοφωνικού προγράμματος',
	'ea:relation:adaptedAsAScreenplayWork' : 'Προσαρμόστηκε ως  Work σεναρίου',
//	'ea:relation:adaptedAsARadioScriptWork' : 'Adapted as a Radio Script Work',
//	'ea:relation:adaptedAsAVideoWork' : 'Adapted as a Video Work',
//	'ea:relation:adaptedAsMusicalTheatreWork' : 'Adapted as musical theatre Work',
//	'ea:relation:adaptedAsOperaWork' : 'Adapted as opera Work',
//	'ea:relation:adaptedAsAMotionPictureScreenplayWork' : 'Adapted as a Motion Picture Screenplay Work',
//	'ea:relation:adaptedAsATelevisionScreenplayWork' : 'Adapted as a Television Screenplay Work',
//	'ea:relation:adaptedAsAVideoScreenplayWork' : 'Adapted as a Video Screenplay Work',
	'ea:relation:freeTranslationOfWork' : 'Ελεύθερη μετάφραση του Work',
	'ea:relation:freelyTranslatedAsWork' : 'Μεταφράστηκε ελεύθερα στο Work:',
//	'ea:relation:musicalSettingOfWork' : 'Musical Setting of Work',
//	'ea:relation:musicalSettingWork' : 'Musical Setting Work',
	'ea:relation:summaryOfWork' : 'Περίληψη του Work',
	'ea:relation:summaryWork' : 'Περίληψη στο Work',
//	'ea:relation:choreographyForWork' : 'Choreography for Work',
//	'ea:relation:choreographyWork' : 'Choreography Work',
//	'ea:relation:expandedVersionOfWork' : 'Expanded Version of Work',
//	'ea:relation:expandedAsWork' : 'Expanded as Work',
//	'ea:relation:remakeOfWork' : 'Remake of Work',
//	'ea:relation:remadeAsWork' : 'Remade as Work',
//	'ea:relation:paraphraseOfWork' : 'Paraphrase of Work',
//	'ea:relation:paraphrasedAsWork' : 'Paraphrased as Work',
//	'ea:relation:librettoBasedOnWork' : 'Libretto Based on Work',
//	'ea:relation:basisForLibrettoWork' : 'Basis for Libretto Work',
//	'ea:relation:abstractsForWork' : 'Abstracts for Work',
//	'ea:relation:abstractWork' : 'Abstract Work',
//	'ea:relation:abstractOfWork' : 'Abstract of Work',
//	'ea:relation:abstractedInWork' : 'Abstracted in Work',
//	'ea:relation:indexingForWork' : 'Indexing for Work',
//	'ea:relation:indexedInWork' : 'Indexed in Work',
//	'ea:relation:imitationOfWork' : 'Imitation of Work',
//	'ea:relation:imitatedAsWork' : 'Imitated as Work',
	'ea:relation:parodyOfWork' : 'Παρωδία του Work',
	'ea:relation:parodiedAsWork' : 'Παρωδία στο Work',
};


var relation_work_descriptive_map = {
	'ea:relation:descriptionOfWork' : 'Περιγραφή του Work',
	'ea:relation:describedInWork' : 'Περιγράφεται στο Work',
	'ea:relation:analysisOfWork' : 'Ανάλυση του Work',
	'ea:relation:analysedInWork' : 'Αναλύεται στο Work',
	'ea:relation:commentaryOnWork' : 'Σχολιασμός του Work',
	'ea:relation:commentaryInWork' : 'Σχολιάζεται στο Work',
	'ea:relation:critiqueOfWork' : 'Κριτική του Work',
	'ea:relation:critiquedInWork' : 'Κριτικάρεται στο Work',
	'ea:relation:evaluationOfWork' : 'Αξιολόγηση του Work',
	'ea:relation:evaluatedInWork' : 'Αξιολογείται στο Work',
	'ea:relation:reviewOfWork' : 'Review του Work',
	'ea:relation:reviewedInWork' : 'Reviewed στο Work',
};

var relation_work_wholepart_map = {
	'ea:relation:containerOfIndependent' : 'Περιέχει τα ανεξάρτητα έργα',
	'ea:relation:containedInIndividual' : 'Περιέχεται στο αυτοτελές έργο',
	'ea:relation:containerOfArticle' : 'Περιέχει τα άρθρα',
	'ea:relation:containedInWorkArticles' : 'Περιέχεται στα άρθρα του έργου',
	'ea:relation:containerOfIndividual' : 'Περιέχει τα αυτοτελή έργα',
	'ea:relation:containedInAggregation' : 'Περιέχεται στη συλλογή έργων',
	'ea:relation:containerOfDocuments' : 'Περιέχει τα έγγραφα',
	'ea:relation:containedInDocuments' : 'Περιέχεται στα έγγραφα του έργου',
	'ea:relation:containerOfDependent' : 'Περιέχει τα εξαρτημένα μέρη',
	'ea:relation:containedInDependent' : 'Περιέχεται ως εξαρτημένο μέρος στο έργο',
	'ea:relation:containerOfSeries' : 'Περιέχει τα έργα σειράς',
	'ea:relation:containedInSeries' : 'Περιέχεται στην σειρά',
	'ea:relation:containerOfSubseries' : 'Περιέχει τα έργα υποσειράς',
	'ea:relation:containedInSubseries' : 'Περιέχεται στην υποσειρά',
	'ea:relation:containerOfMusicTracks' : 'Περιέχει τα μουσικά έργα',
	'ea:relation:containedInMusicTracks' : 'Περιέχεται στο μουσικό έργο',
	'ea:relation:containerOfSerialArticles' : 'Περιέχει τα περιοδικά άρθρα',
	'ea:relation:containedInSerialArticles' : 'Περιέχεται στα άρθρα του περιοδικού έργου',
	'ea:relation:containerOfCorrespondence' : 'Περιέχει την αλληλογραφία',
	'ea:relation:containedInCorrespondence' : 'Περιέχεται στην αλληλογραφία του  έργου',
	'ea:relation:containerOfLectures' : 'Περιέχει τις διαλέξεις',
	'ea:relation:containedInLectures' : 'Περιέχεται στις διαλέξεις του έργου',
	'ea:relation:containerOfContributions' : 'Περιέχει τις εισηγήσεις - συμβολές',
	'ea:relation:containedInContributions' : 'Περιέχεται στις εισηγήσεις – συμβολές του έργου',
	'ea:relation:containerOfSpeeches' : 'Περιέχει τις ομιλίες',
	'ea:relation:containedInSpeeches' : 'Περιέχεται στις ομιλίες του έργου',
};

var relation_work_accompanying_map = {
	'ea:relation:complementedByWork' : 'Συνοδευόμενο από Work',
	'ea:relation:librettoForWork' : 'Libretto για Work',
	'ea:relation:screenplayForWork' : 'Σενάριο για Work',
	'ea:relation:screenplayForTheMotionPictureWork' : 'Σενάριο για το Work Κινηματογραφικής Ταινίας',
	'ea:relation:screenplayForTheTelevisionProgrammeWork' : 'Σενάριο για το Work Τηλεοπτικού προγράμματος',
	'ea:relation:screenplayForTheVideoWork' : 'Σενάριο για το Work Video',
	'ea:relation:scriptForTheRadioProgrammeWork' : 'Σενάριο για το Work Ραδιοφωνικού Σεναρίου',
	'ea:relation:screenplayWork' : 'Work Σεναρίου',
	'ea:relation:augmentedByWork' : 'Επαυξημένο (Augmented) από Work',
	'ea:relation:cadenzaWork' : 'Cadenza Work',
	'ea:relation:errataWork' : 'Παροράματα (Errata) Work',
	'ea:relation:illustrationsWork' : 'Εικονογραφήσεις Work',
	'ea:relation:catalogueWork' : 'Κατάλογος Work',
	'ea:relation:concordanceWork' : 'Concordance Work',
	'ea:relation:supplementWork' : 'Συμπλήρωμα (Supplement) Work',
	'ea:relation:addendaWork' : 'Addenda Work',
	'ea:relation:appendixWork' : 'Παράρτημα Work',
	'ea:relation:guideWork' : 'Οδηγός (Guide) Work',
	'ea:relation:findingAidWork' : 'Finding Aid Work',
	'ea:relation:indexWork' : 'Ευρετήριο (Index) Work',
	'ea:relation:augmentationOfWork' : 'Επαύξηση (augmentation) του Work',
	'ea:relation:cadenzaComposedForWork' : 'Cadenza Composed for Work',
	'ea:relation:errataToWork' : 'Παροράματα (Errata) του Work',
	'ea:relation:illustrationsForWork' : 'Εικονογραφήσεις (Illustrations) του Work',
	'ea:relation:catalogueOfWork' : 'Κατάλογος του Work',
	'ea:relation:concordanceToWork' : 'Concordance to Work',
	'ea:relation:supplementToWork' : 'Συμπλήρωμα (Supplement) του Work',
	'ea:relation:addendaToWork' : 'Πρόσθετα του Work',
	'ea:relation:appendixToWork' : 'Παράρτημα του Work',
	'ea:relation:guideToWork' : 'Οδηγός (Guide) του Work',
	'ea:relation:findingAidForWork' : 'Finding Aid for Work',
	'ea:relation:indexToWork' : 'Ευρετήριο (Index) του Work',
};

var relation_work_sequential_map = {
	'ea:relation:absorptionInPartOfWork' : 'Απερρόφησε εν μέρει το Work',
	'ea:relation:replacementInPartOfWork' : 'Αναπλήρωσε εν μέρει (Replacement) το Work',
	'ea:relation:supersedesWork' : 'Αντικαθιστά (Supersedes) το Work',
	'ea:relation:supersedesInPartWork' : 'Αντικαθιστά (Supersedes) εν μέρει το Work',
	'ea:relation:replacementOfWork' : 'Αναπλήρωσε (Replacement) το Work',
	'ea:relation:absorbedByWork' : 'Απερροφήθη από το Work',
	'ea:relation:absorptionOfWork' : 'Απερρόφησε το Work',
	'ea:relation:absorbedInPartByWork' : 'Απερροφήθη εν μέρει από το Work',
	'ea:relation:succeededByWork' : 'Διάδοχο Work',
	'ea:relation:mergedToFormWork' : 'Ενώθηκε για να σχηματίσει το Work',
	'ea:relation:mergedWithToFormWork' : 'Ενώθηκε με το … για να σχηματίσει το …. Work',
	'ea:relation:precededByWork' : 'Προηγούμενο Work',
	'ea:relation:continuedByWork' : 'Συνεχίζεται από το Work',
	'ea:relation:continuationInPartOfWork' : 'Συνεχίζει εν μέρει το Work',
	'ea:relation:continuedInPartByWork' : 'Συνεχίζεται εν μέρει από το Work',
	'ea:relation:continuationOfWork' : 'Συνεχίζει το Work',
	'ea:relation:mergerOfWork' : 'Σχηματίστηκε από την ένωση του Work',
	'ea:relation:separatedFromWork' : 'Χωρίστηκε από το Work',
	'ea:relation:prequel' : 'Prequel Work',
	'ea:relation:sequelTo' : 'Sequel to Work',
};

var relation_expres_derivative_map = {
	'ea:relation:dramatizationOfExpression' : 'Δραματοποίηση του Expression',
	'ea:relation:dramatizedAsExpression' : 'Δραματοποιήθηκε στο Expression',
	'ea:relation:freeTranslationOfExpression' : 'Ελεύθερη μετάφραση του Expression',
	'ea:relation:expandedAsExpression' : 'Εκτεταμένο στο Expression',
	'ea:relation:expandedVersionOfExpression' : 'Εκτεταμένη έκδοση του Expression',
	'ea:relation:abridgementOfExpression' : 'Επιτομή του Expression',
	'ea:relation:abridgedAsExpression' : 'Επιτομή στο Expression',
	'ea:relation:motionPictureAdaptationOfExpression' : 'Κινηματογραφική προσαρμογή του Expression',
	'ea:relation:freelyTranslatedAsExpression' : 'Μεταφράστηκε ελεύθερα στο Expression',
	'ea:relation:translationOfExpression' : 'Μετάφραση του Expression',
	'ea:relation:translatedAsExpression' : 'Μεταφράστηκε στο Expression',
	'ea:relation:musicalSettingOfExpression' : 'Μελοποίηση του Expression',
	'ea:relation:musicalSettingExpression' : 'Μελοποιήθηκε στο Expression',
	'ea:relation:summaryOfExpression' : 'Περίληψη του Expression',
	'ea:relation:summaryExpression' : 'Περίληψη στο Expression',
	'ea:relation:adaptationOfExpression' : 'Προσαρμογή του Expression',
	'ea:relation:novelizationOfExpression' : 'Προσαρμογή σε μυθιστόρημα του Expression',
	'ea:relation:adaptedAsExpression' : 'Προσαρμόστηκε στο Expression',
	'ea:relation:novelizationExpression' : 'Προσαρμόστηκε ως μυθιστόρημα στο Expression',
	'ea:relation:verseAdaptationOfExpression' : 'Στιχουργική προσαρμογή του Expression',
	'ea:relation:choreographyForExpression' : 'Χορογραφία του Expression',
	'ea:relation:choreographyExpression' : 'Χορογραφία στο Expression',
};

var relation_expres_descriptive_map = {
	'ea:relation:analysedInExpression' : 'Αναλύεται στο Expression',
	'ea:relation:analysisOfExpression' : 'Ανάλυση του Expression',
	'ea:relation:evaluatedInExpression' : 'Αξιολογείται στο Expression',
	'ea:relation:evaluationOfExpression' : 'Αξιολόγηση του Expression',
	'ea:relation:critiquedInExpression' : 'Κριτικάρεται στο Expression',
	'ea:relation:critiqueOfExpression' : 'Κριτική του Expression',
	'ea:relation:describedInExpression' : 'Περιγράφεται στο Expression',
	'ea:relation:descriptionOfExpression' : 'Περιγραφή του Expression',
	'ea:relation:commentaryOnExpression' : 'Σχολιασμός του Expression',
	'ea:relation:commentaryInExpression' : 'Σχολιάζεται στο Expression',
	'ea:relation:reviewOfExpression' : 'Review του Expression',
	'ea:relation:reviewedInExpression' : 'Reviewed στο Expression',
};

var relation_expres_wholepart_map = {
	'ea:relation:containedInExpression' : 'Περιέχεται στο Expression',
	'ea:relation:containerOfExpression' : 'Περιεχόμενο  του Expression',
};


var relation_expres_accompanying_map = {
'ea:relation:illustrationsForExpression':'Εικονογραφήσεις (Illustrations) του Expression ',
'ea:relation:illustrationsExpression':'Εικονογραφήσεις Expression ',
'ea:relation:augmentedByExpression':'Επαυξημένο (Augmented) από Expression ',
'ea:relation:augmentationOfExpression':'Επαύξηση (augmentation) του Expression ',
'ea:relation:indexExpression':'Ευρετήριο (Index) Expression ',
'ea:relation:indexToExpression':'Ευρετήριο (Index) του Expression ',
'ea:relation:catalogueExpression':'Κατάλογος Expression ',
'ea:relation:catalogueOfExpression':'Κατάλογος του Expression ',
'ea:relation:guideExpression':'Οδηγός (Guide) Expression ',
'ea:relation:guideToExpression':'Οδηγός (Guide) του Expression ',
'ea:relation:appendixExpression':'Παράρτημα Expression ',
'ea:relation:appendixToExpression':'Παράρτημα του Expression ',
'ea:relation:errataExpression':'Παροράματα (Errata) Expression ',
'ea:relation:errataToExpression':'Παροράματα (Errata) του Expression ',
'ea:relation:addendaToExpression':'Πρόσθετα του Expression ',
'ea:relation:screenplayForExpression':'Σενάριο για Expression ',
'ea:relation:screenplayForTheVideoExpression':'Σενάριο για το Expression Video ',
'ea:relation:screenplayForTheMotionPictureExpression':'Σενάριο για το Expression Κινηματογραφικής Ταινίας ',
'ea:relation:scriptForTheRadioProgrammeExpression':'Σενάριο για το Expression Ραδιοφωνικού Σεναρίου ',
'ea:relation:screenplayForTheTelevisionProgrammeExpression':'Σενάριο για το Expression Τηλεοπτικού προγράμματος ',
'ea:relation:supplementExpression':'Συμπλήρωμα (Supplement) Expression ',
'ea:relation:supplementToExpression':'Συμπλήρωμα (Supplement) του Expression ',
'ea:relation:complementedByExpression':'Συνοδευόμενο από Expression ',
'ea:relation:addendaExpression':'Addenda Expression ',
'ea:relation:cadenzaComposedForExpression':'Cadenza Composed του Expression ',
'ea:relation:cadenzaExpression':'Cadenza Expression ',
'ea:relation:concordanceExpression':'Concordance Expression ',
'ea:relation:concordanceToExpression':'Concordance του Expression ',
'ea:relation:librettoExpression':'Expression Libretto ',
'ea:relation:radioScriptExpression':'Expression Ραδιοφωνικού Σεναρίου ',
'ea:relation:screenplayExpression':'Expression Σεναρίου ',
'ea:relation:videoScreenplayExpression':'Expression Σεναρίου Video ',
'ea:relation:motionPictureScreenplayExpression':'Expression Σεναρίου Κινηματογραφικής Ταινίας ',
'ea:relation:televisionScreenplayExpression':'Expression Σεναρίου Τηλεοπτικού προγράμματος ',
'ea:relation:findingAidExpression':'Finding Aid Expression ',
'ea:relation:findingAidForExpression':'Finding Aid του Expression ',
'ea:relation:librettoForExpression':'Libretto για Expression ',
};


var relation_expres_sequential_map = {
		'ea:relation:replacedByExpression' : 'Αναπληρώθηκε (Replaced) από το Expression',
		'ea:relation:replacedInPartByExpression' : 'Αναπληρώθηκε (Replaced) εν μέρει από το Expression',
		'ea:relation:supersededByExpression' : 'Αντικατεστάθη (Superseded) από το Expression',
		'ea:relation:supersededInPartByExpression' : 'Αντικατεστάθη (Superseded) εν μέρει από το Expression',
		'ea:relation:supersedesExpression' : 'Αντικαθιστά (Supersedes) το Expression',
		'ea:relation:supersedesInPartExpression' : 'Αντικαθιστά (Supersedes) εν μέρει το Expression',
		'ea:relation:replacementOfExpression' : 'Αναπλήρωσε (Replacement) το Expression',
		'ea:relation:replacementInPartOfExpression' : 'Αναπλήρωσε εν μέρει (Replacement) το Expression',
		'ea:relation:absorbedByExpression' : 'Απερροφήθη από το Expression',
		'ea:relation:absorptionOfExpression' : 'Απερρόφησε το Expression',
		'ea:relation:absorptionInPartOfExpression' : 'Απερρόφησε εν μέρει το Expression',
		'ea:relation:absorbedInPartByExpression' : 'Απερροφήθη εν μέρει από το Expression',
		'ea:relation:succeededByExpression' : 'Διάδοχο Expression',
		'ea:relation:mergedToFormExpression' : 'Ενώθηκε για να σχηματίσει το Expression',
		'ea:relation:mergedWithToFormExpression' : 'Ενώθηκε με το … για να σχηματίσει το …. Expression',
		'ea:relation:precededByExpression' : 'Προηγούμενο Expression',
		'ea:relation:continuationOfExpression' : 'Συνεχίζει το Expression',
		'ea:relation:continuedByExpression' : 'Συνεχίζεται από το Expression',
		'ea:relation:continuedInPartByExpression' : 'Συνεχίζεται εν μέρει από το Expression',
		'ea:relation:continuationInPartOfExpression' : 'Συνεχίζει εν μέρει το Expression',
		'ea:relation:mergerOfExpression' : 'Σχηματίστηκε από την ένωση του Expression',
		'ea:relation:separatedFromExpression' : 'Χωρίστηκε από το Expression',
		'ea:relation:splitIntoExpression' : 'Χωρίστηκε σε Expression',
};

var relation_name_not_map = {
	'ea:relation:OrganizationAlter_full_name_not' : 'Πλήρες όνομα',
	'ea:relation:OrganizationAlterEarlier_name_not' : 'Προγενέστερο όνομα',
	'ea:relation:OrganizationAlterLater_name_not' : 'Μεταγενέστερο όνομα',
	'ea:relation:OrganizationAlterAcronym_name_not' : 'Συντομογραφία',
	'ea:relation:OrganizationAlterOther_name_not' : 'Άλλο όνομα',
};

var relation_alter_map = {
	'ea:relation:OrganizationAlter_full_name' : 'Πλήρες όνομα',
	'ea:relation:OrganizationAlterEarlier' : 'Προγενέστερο όνομα',
	'ea:relation:OrganizationAlterLater' : 'Μεταγενέστερο όνομα',
	'ea:relation:OrganizationAlterAcronym' : 'Συντομογραφία',
	'ea:relation:OrganizationAlterOther' : 'Άλλο όνομα',
};

var relation_organization_see_also_organization_map = {
//	'ea:relation:OrganizationOtherSubordinate' : 'Θυγατρική',
//	'ea:relation:OrganizationOtherLarger' : 'Μητρικός οργανισμός',
//	'ea:relation:OrganizationOtherOther' : 'Άλλοι οργανισμοί',
//	'ea:relation:OrganizationOtherMeberHas' : 'Μέλη οργανισμού',
//	'ea:relation:OrganizationOtherFoundedBy' : 'Ιδρυτής',
//	'ea:relation:OrganizationOtherOwnedBy' : 'Ιδιοκτήτης',
//	'ea:relation:OrganizationOtherPredecessor' : 'Προκάτοχος',
//	'ea:relation:OrganizationOtherSuccessor' : 'Διάδοχος',
//	'ea:relation:OrganizationOtherCooperative' : 'Συνεργαζόμενος',
//	'ea:relation:OrganizationOtherMerged' : 'Συγχωνεύθηκε',
//	'ea:relation:OrganizationOtherMerge' : 'Συγχώνευσε',
//	'ea:relation:OrganizationOtherUnited' : 'Ενώθηκε',
//	'ea:relation:OrganizationOtherUnite' : 'Ένωσε',
//	'ea:relation:OrganizationParticipate' : 'Συμμετέχει',
//	'ea:relation:OrganizationAnnex' : 'Παράρτημα',
//	'ea:relation:OrganizationPart' : 'Τμήμα',
//	'ea:relation:OrganizationInstitution' : 'Σχολή',
	'ea:relation:OrganizationOtherOther' : 'Άλλοι οργανισμοί',
	'ea:relation:OrganizationOtherCompetitor' : 'Αντίπαλοι',
	'ea:relation:OrganizationOtherSuccessor' : 'Διάδοχος',
	'ea:relation:OrganizationOtherorganized' : 'Διοργανώθηκε',
	'ea:relation:OrganizationOtherOrganizer' : 'Διοργανωτής',
	'ea:relation:OrganizationOtherUnited' : 'Ενώθηκε',
	'ea:relation:OrganizationOtherUnite' : 'Ένωσε',
	'ea:relation:OrganizationOtherSubordinate' : 'Θυγατρικές',
	'ea:relation:OrganizationOtherOwners' : 'Ιδιοκτήτες',
	'ea:relation:OrganizationOtherOwnedBy' : 'Ιδιοκτήτης',
	'ea:relation:OrganizationOtherFounders' : 'Ιδρυτές',
	'ea:relation:OrganizationOtherFoundedBy' : 'Ιδρυτής',
	'ea:relation:OrganizationOtherMeberHas' : 'Μέλη του οργανισμού',
	'ea:relation:OrganizationOtherMeber' : 'Μέλος του οργανισμού',
	'ea:relation:OrganizationOtherLarger' : 'Μητρικός οργανισμός',
	'ea:relation:OrganizationAnnex' : 'Παράρτημα',
	'ea:relation:OrganizationAnnexs' : 'Παραρτήματα',
	'ea:relation:OrganizationOtherPredecessor' : 'Προκάτοχος',
	'ea:relation:OrganizationOtherMerged' : 'Συγχωνεύθηκε',
	'ea:relation:OrganizationOtherMerge' : 'Συγχώνευσε',
	'ea:relation:OrganizationOtherAllies' : 'Σύμμαχοι',
	'ea:relation:OrganizationParticipate' : 'Συμμετέχει στον οργανισμό',
	'ea:relation:OrganizationParticipants' : 'Συμμετέχουν στον οργανισμό',
	'ea:relation:OrganizationOtherCollaborating' : 'Συνεργαζόμενοι',
	'ea:relation:OrganizationOtherCooperative' : 'Συνεργαζόμενος',
	'ea:relation:OrganizationInstitutions' : 'Σχολές',
	'ea:relation:OrganizationInstitution' : 'Σχολή',
	'ea:relation:OrganizationPart' : 'Τμήμα',
	'ea:relation:OrganizationParts' : 'Τμήματα',
};

var relation_person_see_map = {
	'ea:relation:PersonAlterWork' : 'Αποδιδόμενο όνομα',
	'ea:relation:PersonAlterOfficial' : 'Επίσημο όνομα',
	'ea:relation:PersonAlterReligion' : 'Θρησκευτικό όνομα',
	'ea:relation:PersonAlterPseudonymShared' : 'Κοινόχρηστο ψευδώνυμο',
	'ea:relation:PersonAlterSecular' : 'Κοσμικό όνομα',
	'ea:relation:PersonAlterBeforeMarriage' : 'Όνομα πριν το συζυγικό',
	'ea:relation:PersonAlterReal' : 'Πραγματικό όνομα',
	'ea:relation:PersonAlterMarried' : 'Συζυγικό όνομα',
	'ea:relation:PersonAlterPseudonym' : 'Ψευδώνυμο',
	'ea:relation:PersonAlterOther' : 'Άλλο όνομα',
};

var relation_person_see_map_alter = {

	'ea:relation:PersonAlterWork_alter' : 'Αποδιδόμενο όνομα',
	'ea:relation:PersonAlterOfficial_alter' : 'Επίσημο όνομα',
	'ea:relation:PersonAlterReligion_alter' : 'Θρησκευτικό όνομα',
	'ea:relation:PersonAlterPseudonymShared_alter' : 'Κοινόχρηστο ψευδώνυμο',
	'ea:relation:PersonAlterSecular_alter' : 'Κοσμικό όνομα',
	'ea:relation:PersonAlterBeforeMarriage_alter' : 'Όνομα πριν το συζυγικό',
	'ea:relation:PersonAlterReal_alter' : 'Πραγματικό όνομα',
	'ea:relation:PersonAlterMarried_alter' : 'Συζυγικό όνομα',
	'ea:relation:PersonAlterPseudonym_alter' : 'Ψευδώνυμο',
	'ea:relation:PersonAlterOther_alter' : 'Άλλο όνομα',
};

var relation_person_see_also_person_map = {
	'ea:relation:PersonOtherSibling' : 'Αδέλφια',
	'ea:relation:PersonOtherNephews' : 'Ανίψια',
	'ea:relation:PersonOtherParent' : 'Γονείς',
	'ea:relation:PersonOtherDescendant' : 'Εγγόνια',
	'ea:relation:PersonOtherUncles' : 'Θείοι',
	'ea:relation:PersonOtherChild' : 'Παιδιά',
	'ea:relation:PersonOtherProgenitor' : 'Παππούδες',
	'ea:relation:PersonOtherMarriage' : 'Σύζυγοι',
	'ea:relation:PersonOtherCousins' : 'Ξαδέρφια',
	'ea:relation:PersonOtherOther' : 'Άλλες συγγένειες',
};

var relation_family_see_also_person_map = {
	'ea:relation:FamilyPersonFoundedBy' : 'Γενάρχες οικογένειας',
	'ea:relation:FamilyPersonMeberHas' : 'Μέλη οικογένειας',
};

var relation_person_see_also_person_family_map = {
	'ea:relation:PersonOtherDescendant' : 'Απογονική οικογενειακή σχέση',
	'ea:relation:PersonOtherProgenitor' : 'Προγονική οικογενειακή σχέση',
	'ea:relation:PersonOtherOther' : 'Άλλη οικογενειακή σχέση',
};

var relation_person_see_also_organization_map = {
	'ea:relation:PersonOrganizationUnknown' : 'Αγνώστου τύπου σχέση με οργανισμό',
	'ea:relation:PersonOrganizationAcademic' : 'Ακαδημαϊκό προσωπικό',
	'ea:relation:PersonOrganizationCommissioned' : 'Αξιωματικός',
	'ea:relation:PersonOrganizationVicePresident' : 'Αντιπρόεδρος',
	'ea:relation:PersonOrganizationRegent' : 'Αντιβασιλέας',
	'ea:relation:PersonOrganizationUnspecified' : 'Απροσδιόριστου τύπου σχέση με οργανισμό',
	'ea:relation:PersonOrganizationLeader' : 'Αρχηγός',
	'ea:relation:PersonOrganizationArchbishop' : 'Αρχιεπίσκοπος',
	'ea:relation:PersonOrganizationParliament' : 'Βουλευτής',
	'ea:relation:PersonOrganizationGeneralsecretary' : 'Γενικός γραμματέας',
	'ea:relation:PersonOrganizationSecretary' : 'Γραμματέας',
	'ea:relation:PersonOrganizationMayor' : 'Δήμαρχος',
	'ea:relation:PersonOrganizationManager' : 'Διευθυντής',
	'ea:relation:PersonOrganizationCommander' : 'Διοικητής',
	'ea:relation:PersonOrganizationTeacher' : 'Εκπαιδευτικός',
	'ea:relation:PersonOrganizationResearcher' : 'Ερευνητής',
	'ea:relation:PersonOrganizationHead' : 'Ηγέτης ',
	'ea:relation:PersonOrganizationOwnedBy' : 'Ιδιοκτήτης',
	'ea:relation:PersonOrganizationFoundedBy' : 'Ιδρυτής',
	'ea:relation:PersonOrganizationMeberHas' : 'Μέλος',
	'ea:relation:PersonOrganizationShareholder' : 'Μέτοχος',
	'ea:relation:PersonOrganizationMetropolitan' : 'Μητροπολίτης',
	'ea:relation:PersonOrganizationMonarch' : 'Μονάρχης',
	'ea:relation:PersonOrganizationPatriarch' : 'Πατριάρχης',
	'ea:relation:PersonOrganizationRegional' : 'Περιφερειάρχης',
	'ea:relation:PersonOrganizationPolitician' : 'Πολιτευτής',
	'ea:relation:PersonOrganizationPresident' : 'Πρόεδρος',
	'ea:relation:PersonOrganizationRector' : 'Πρύτανης',
	'ea:relation:PersonOrganizationPrimeminister' : 'Πρωθυπουργός',
	'ea:relation:PersonOrganizationStrain' : 'Στέλεχος',
	'ea:relation:PersonOrganizationSoldier' : 'Στρατιώτης',
	'ea:relation:PersonOrganizationAdvisor' : 'Σύμβουλος',
	'ea:relation:PersonOrganizationCo-founder' : 'Συνιδρυτής',
	'ea:relation:PersonOrganizationEmployee' : 'Υπάλληλος',
	'ea:relation:PersonOrganizationNoncommissioned' : 'Υπαξιωματικός',
	'ea:relation:PersonOrganizationDeputyhead' : 'Υπαρχηγός',
	'ea:relation:PersonOrganizationMinister' : 'Υπουργός',
	'ea:relation:PersonOrganizationDeputyminister' : 'Υφυπουργός',
};


var relation_organization_see_also_person_map = {
		'ea:relation:OrganizationPersonUnknown' : 'Αγνώστου τύπου σχέση με πρόσωπο',
		'ea:relation:OrganizationPersonAcademic' : 'Ακαδημαϊκό προσωπικό',
		'ea:relation:OrganizationPersonCommissioned' : 'Αξιωματικός',
		'ea:relation:OrganizationPersonVicePresident' : 'Αντιπρόεδρος',
		'ea:relation:OrganizationPersonRegent' : 'Αντιβασιλέας',
		'ea:relation:OrganizationPersonUnspecified' : 'Απροσδιόριστου τύπου σχέση με πρόσωπο',
		'ea:relation:OrganizationPersonLeader' : 'Αρχηγός',
		'ea:relation:OrganizationPersonArchbishop' : 'Αρχιεπίσκοπος',
		'ea:relation:OrganizationPersonParliament' : 'Βουλευτής',
		'ea:relation:OrganizationPersonGeneralsecretary' : 'Γενικός γραμματέας',
		'ea:relation:OrganizationPersonSecretary' : 'Γραμματέας',
		'ea:relation:OrganizationPersonMayor' : 'Δήμαρχος',
		'ea:relation:OrganizationPersonManager' : 'Διευθυντής',
		'ea:relation:OrganizationPersonCommander' : 'Διοικητής',
		'ea:relation:OrganizationPersonTeacher' : 'Εκπαιδευτικός',
		'ea:relation:OrganizationPersonResearcher' : 'Ερευνητής',
		'ea:relation:OrganizationPersonHead' : 'Ηγέτης ',
		'ea:relation:OrganizationPersonOwnedBy' : 'Ιδιοκτήτης',
		'ea:relation:OrganizationPersonFoundedBy' : 'Ιδρυτής',
		'ea:relation:OrganizationPersonMeberHas' : 'Μέλος',
		'ea:relation:OrganizationPersonShareholder' : 'Μέτοχος',
		'ea:relation:OrganizationPersonMetropolitan' : 'Μητροπολίτης',
		'ea:relation:OrganizationPersonMonarch' : 'Μονάρχης',
		'ea:relation:OrganizationPersonPatriarch' : 'Πατριάρχης',
		'ea:relation:OrganizationPersonRegional' : 'Περιφερειάρχης',
		'ea:relation:OrganizationPersonPolitician' : 'Πολιτευτής',
		'ea:relation:OrganizationPersonPresident' : 'Πρόεδρος',
		'ea:relation:OrganizationPersonRector' : 'Πρύτανης',
		'ea:relation:OrganizationPersonPrimeminister' : 'Πρωθυπουργός',
		'ea:relation:OrganizationPersonStrain' : 'Στέλεχος',
		'ea:relation:OrganizationPersonSoldier' : 'Στρατιώτης',
		'ea:relation:OrganizationPersonAdvisor' : 'Σύμβουλος',
		'ea:relation:OrganizationPersonCo-founder' : 'Συνιδρυτής',
		'ea:relation:OrganizationPersonEmployee' : 'Υπάλληλος',
		'ea:relation:OrganizationPersonNoncommissioned' : 'Υπαξιωματικός',
		'ea:relation:OrganizationPersonDeputyhead' : 'Υπαρχηγός',
		'ea:relation:OrganizationPersonMinister' : 'Υπουργός',
		'ea:relation:OrganizationPersonDeputyminister' : 'Υφυπουργός',
};


var relation_organization_see_also_family_map = {
	'ea:relation:OrganizationFamilyMeberHas' : 'Μέλη οργανισμού',
	'ea:relation:OrganizationFamilyFoundedBy' : 'Ιδρυτές οργανισμού',
	'ea:relation:OrganizationFamilyOwnedBy' : 'Ιδιοκτήτες οργανισμού',
	};

var relation_family_see_also_organization_map = {
		'ea:relation:OrganizationFamilyMeberHas' : 'Μέλη του οργανισμού',
		'ea:relation:OrganizationFamilyFoundedBy' : 'Ιδρυτές του οργανισμού',
		'ea:relation:OrganizationFamilyOwnedBy' : 'Ιδιοκτήτες του οργανισμού',
		};

var relation_person_see_also_family_map = {
	'ea:relation:PersonFamilyMember' : 'Μέλος της οικογένειας',
	'ea:relation:PersonFamilyFounder' : 'Γενάρχης',
};

var relation_person_other_language_map = {
	'ea:relation:Language' : 'Ο όρος σε άλλη γλώσσα',
};

var relation_equivalent_map = {
	'ea:relation:reproductionOfManifestation' : 'Αναπαραγωγή του Manifestation',
	'ea:relation:reproducedAsManifestation' : 'Αναπαράχθηκε ως Manifestation',
	'ea:relation:reprintOfManifestation' : 'Ανατύπωση του Manifestation',
	'ea:relation:reprintedAs' : 'Ανατύπωση ως',
	'ea:relation:alsoIssuedAs' : 'Εκδόθηκε επίσης ως Manifestation',
	'ea:relation:electronicReproduction' : 'Ηλεκτρονική αναπαραγωγή',
	'ea:relation:electronicReproductionOfManifestation' : 'Ηλεκτρονική αναπαραγωγή του Manifestation',
	'ea:relation:equivalentManifestation' : 'Ισοδύναμο Manifestation',
	'ea:relation:facsimileOfManifestation' : 'Πανομοιότυπο του Manifestation',
	'ea:relation:facsimile' : 'Πανομοιότυπο',
	'ea:relation:digitalTransferManifestation' : 'Ψηφιακή μεταφορά του Manifestation',
	'ea:relation:digitalTransfer' : 'Ψηφιακή μεταφορά',
	'ea:relation:mirrorSiteManifestation' : 'Mirror Site Manifestation',
	'ea:relation:preservationFacsimile' : 'Preservation Facsimile',
	'ea:relation:preservationFacsimileOfManifestation' : 'Preservation Facsimile του Manifestation',
};


var relation_descriptive_map = {
	'ea:relation:descriptionOfManifestation' : 'Περιγραφή του Manifestation',
	'ea:relation:analysisOfManifestation' : 'Ανάλυση του Manifestation',
	'ea:relation:commentaryOnManifestation' : 'Σχολιασμός του Manifestation',
	'ea:relation:critiqueOfManifestation' : 'Κριτική του Manifestation',
	'ea:relation:evaluationOfManifestation' : 'Αξιολόγηση του Manifestation',
	'ea:relation:reviewOfManifestation' : 'Review του Manifestation',
};

var relation_wholepart_map = {
	'ea:relation:containedInManifestation' : 'Περιέχεται στο Manifestation',
	'ea:relation:insertedIn' : 'Ένθετο στο',
	'ea:relation:specialIssueOf' : 'Ειδικό τεύχος (Issue) στο',
	'ea:relation:facsimileContainedIn' : 'Περιέχεται πανομοιότυπο στο',
	'ea:relation:containerOfManifestation' : 'Περιεχόμενο του Manifestation',
	'ea:relation:insert' : 'Ένθετο',
	'ea:relation:specialIssue' : 'Ειδικό τεύχος',
	'ea:relation:facsimileContainerOf' : 'Περιέχει πανομοιότυπο το',
};


var relation_accompanying_map = {
	'ea:relation:accompaniedByManifestation' : 'Συνοδεύεται από Manifestation',
	'ea:relation:issuedWith' : 'Εκδόθηκε με Manifestation',
	'ea:relation:filmedWithManifestation' : 'Filmed με Manifestation',
	'ea:relation:onDiscWithManifestation' : 'Σε δίσκο με Manifestation',
};

var relation_concept_alter_map_not_term = {
	'ea:relation:TermAlterSee_Alternative_not_term' : 'Εναλλακτικό όνομα',
	'ea:relation:TermAlterSee_official_not_term' : 'Επίσημο όνομα',
	'ea:relation:TermAlterSee_full_name_not_term' : 'Πλήρες όνομα',
	'ea:relation:TermAlterSee_acronym_not_term' : 'Συντομογραφία',
	'ea:relation:TermAlterSee_Variant_not_term' : 'Άλλη παραλλαγή ονόματος',
	'ea:relation:TermAlterSee_Other_not_term' : 'Άλλο όνομα',
};

var relation_concept_alter_map = {
		'ea:relation:TermAlterSee_Alternative' : 'Εναλλακτικό όνομα',
		'ea:relation:TermAlterSee_official' : 'Επίσημο όνομα',
		'ea:relation:TermAlterSee_full_name' : 'Πλήρες όνομα',
		'ea:relation:TermAlterSee_acronym' : 'Συντομογραφία',
		'ea:relation:TermAlterSee_Variant' : 'Άλλη παραλλαγή ονόματος',
		'ea:relation:TermAlterSee_Other' : 'Άλλο όνομα',
	};

var relation_place_alter_map_not_term = {
			'ea:relation:TermAlterSee_Alternative_not_term' : 'Εναλλακτική ονομασία',
			'ea:relation:TermAlterSee_Variant_new_not_term' : 'Νεώτερη ονομασία',
			'ea:relation:TermAlterSee_Variant_old_not_term' : 'Παλαιότερη ονομασία',
			'ea:relation:TermAlterSee_Other_not_term' : 'Άλλη ονομασία',
		};

var relation_place_alter_map = {
		'ea:relation:TermAlterSee_Alternative' : 'Εναλλακτική ονομασία',
		'ea:relation:TermAlterSee_Variant_new' : 'Νεώτερη ονομασία',
		'ea:relation:TermAlterSee_Variant_old' : 'Παλαιότερη ονομασία',
		'ea:relation:TermAlterSee_Other' : 'Άλλη ονομασία',
		};


var relation_place_organization_map = {
		'ea:relation:PlaceOrganizationMunicipal' : 'Δήμος',
		'ea:relation:PlaceOrganizationMunicipal_Unity' : 'Δημοτική ενότητα',
		'ea:relation:PlaceOrganizationEducational' : 'Εκπαιδευτικό ίδρυμα',
		'ea:relation:PlaceOrganizationCommunity' : 'Κοινότητα',
		'ea:relation:PlaceOrganizationState' : 'Κράτος',
		'ea:relation:PlaceOrganizationAdministrative' : 'Περιφέρεια',
		'ea:relation:PlaceOrganizationRegional' : 'Περιφερειακή ενότητα',
		'ea:relation:PlaceOrganizationUnknown' : 'Άγνωστη σχέση με οργανισμό',
};


var relation_place_other_map = {
		'ea:relation:Encloses':'Περικλείει',
		'ea:relation:Enclosed':'Περικλείεται',
		'ea:relation:EnclosesPartially':'Περικλείει μερικώς',
		'ea:relation:EnclosedPartially':'Περικλείεται μερικώς',
		'ea:relation:Proximity':'Γειτνιάζει',
		'ea:relation:ProximityEast':'Γειτνιάζει ανατολικά',
		'ea:relation:ProximityWest':'Γειτνιάζει δυτικά',
		'ea:relation:ProximityNorth':'Γειτνιάζει βόρεια',
		'ea:relation:ProximitySouth':'Γειτνιάζει νότια',
		'ea:relation:ProximityNorthEast':'Γειτνιάζει βορειοανατολικά',
		'ea:relation:ProximityNorthWest':'Γειτνιάζει βορειοδυτικά',
		'ea:relation:ProximitySouthEast':'Γειτνιάζει νότιoανατολικά',
		'ea:relation:ProximitySouthWest':'Γειτνιάζει νότιoδυτικά',
};

var relation_term_other_map = {
	'ea:relation:TermOtherEarlier' : 'Προγενέστερο όνομα',
	'ea:relation:TermOtherLater' : 'Μεταγενέστερο όνομα',
//	'ea:relation:TermOtherOfficial' : 'Επίσημο όνομα',
//	'ea:relation:TermOtherAcronym' : 'Συντομογραφία',
	'ea:relation:TermOtherBroader' : 'Ευρύτερος όρος',
	'ea:relation:TermOtherNarrower' : 'Στενότερος όρος',
	'ea:relation:TermOtherCategory' : 'Κατηγορία',
	'ea:relation:TermOtherSubategory' : 'Υποκατηγορία',
	'ea:relation:TermOtherOther' : 'Άλλος σχετικός όρος',
	'ea:relation:TermOtherEquivalent' : 'Ισοδύναμος όρος',
};

var relation_subject_chain_related_other_map = {
		'ea:relation:SubjectChainRelatedOther' : 'Σχετιζόμενος Όρος',
};

var	subject_type_map = {
	'ea:subj:work':'Work',
	'ea:subj:person':'Person/Family/Organization',
	'ea:subj:concept':'Concept',
	'ea:subj:object':'Object',
	'ea:subj:event':'Event',
	'ea:subj:place':'Place',
	'ea:subj:form':'Form',
};


var	primary_subject_type_map = {
	'ea:subj:work:primary':'Work',
	'ea:subj:person:primary':'Person/Family/Organization',
	'ea:subj:concept:primary':'Concept',
	'ea:subj:object:primary':'Object',
	'ea:subj:event:primary':'Event',
	'ea:subj:place:primary':'Place',
	'ea:subj:form:primary':'Form',
};


var	primary_subject_obj_type_map = {
		'ea:subj:work:primary':'auth-work',
		'ea:subj:person:primary':'actor',
		'ea:subj:concept:primary':'auth-concept',
		'ea:subj:object:primary':'auth-object',
		'ea:subj:event:primary':'auth-event',
		'ea:subj:place:primary':'auth-place',
		'ea:subj:form:primary':'auth-genre',
	};

var	subject_obj_type_map = {
		'ea:subj:work':'auth-work',
		'ea:subj:person':'actor',
		'ea:subj:concept':'auth-concept',
		'ea:subj:object':'auth-object',
		'ea:subj:event':'auth-event',
		'ea:subj:place':'auth-place',
		'ea:subj:form':'auth-genre',
	};


var expres_frequency_map = {
		'ea:expres:FrequencyTable_u':'Άγνωστο',
		'ea:expres:FrequencyTable_z':'Άλλο',
		'ea:expres:FrequencyTable_|':'Δεν εφαρμόζεται συχνότητα',
		'ea:expres:FrequencyTable_#':'Δεν προσδιορίζεται συχνότητα',
		'ea:expres:FrequencyTable_g':'Διετές',
		'ea:expres:FrequencyTable_b':'Διμηνιαίο',
		'ea:expres:FrequencyTable_c':'Δύο φορές την εβδομάδα',
		'ea:expres:FrequencyTable_s':'Δύο φορές τον μήνα',
		'ea:expres:FrequencyTable_w':'Εβδομαδιαίο',
		'ea:expres:FrequencyTable_f':'Εξαμηνιαίο',
		'ea:expres:FrequencyTable_a':'Ετήσιο',
		'ea:expres:FrequencyTable_e':'Κάθε δύο εβδομάδες',
		'ea:expres:FrequencyTable_d':'Καθημερινό',
		'ea:expres:FrequencyTable_m':'Μηνιαίο',
		'ea:expres:FrequencyTable_k':'Συνεχή updated',
		'ea:expres:FrequencyTable_i':'Τρεις φορές την εβδομάδα',
		'ea:expres:FrequencyTable_j':'Τρεις φορές τον μήνα',
		'ea:expres:FrequencyTable_t':'Τρεις φορές τον χρόνο',
		'ea:expres:FrequencyTable_h':'Τριετές',
		'ea:expres:FrequencyTable_q':'Τριμηνιαίο',
}


var relation_item_equivalent_map = {
		'ea:relation:equivalentItem' : 'Ισοδύναμο Item',
		'ea:relation:reproductionOfItem' : 'Αναπαραγωγή του Item',
		'ea:relation:digitalTransferOfItem' : 'Ψηφιακή μεταφορά του Item',
		'ea:relation:electronicReproductionOfItem' : 'Ηλεκτρονική αναπαραγωγή του Item',
		'ea:relation:facsimileOfItem' : 'Πανομοιότυπο του Item',
		'ea:relation:preservationFacsimileOfItem' : 'Preservation Facsimile του Item',
		'ea:relation:reprintOfItem' : 'Ανατύπωση του Item',
	};

	var relation_item_descriptive_map = {
		'ea:relation:descriptionOfItem' : 'Περιγραφή του Item',
		'ea:relation:analysisOfItem' : 'Ανάλυση του Item',
		'ea:relation:commentaryOnItem' : 'Σχολιασμός του Item',
		'ea:relation:critiqueOfItem' : 'Κριτική του Item',
		'ea:relation:evaluationOfItem' : 'Αξιολόγηση του Item',
		'ea:relation:reviewOfItem' : 'Review του Item',
	};

	var relation_item_wholepart_map = {
		'ea:relation:containedInItem' : 'Περιέχεται στο Item',
		'ea:relation:containerOfItem' : 'Περιεχόμενο του Item',
	};

	var relation_item_accompanying_map = {
		'ea:relation:accompaniedByItem' : 'Συνοδεύεται από Item',
		'ea:relation:boundWith' : 'Δεμένο με Item',
		'ea:relation:filmedWithItem' : 'Filmed με Item',
		'ea:relation:onDiscWithItem' : 'Σε δίσκο με Item',
	};

	var item_type_map= {
			'undefined':'Μη προσδιορισμένος',
			'pdf':'PDF',
			'daisy':'DAISY κειμένου',
			'epub':'EPUB',
			'docx':'DOCX',
			'doc':'DOC',
			'mp3':'MP3',
			'wav':'WAV',
			'wma':'WMA',
			'zip':'ZIP',
			'rar':'RAR',
			'7z':'7Z',
			'png':'PNG',
	};

