
var formSetups = {
//	'manuscript':f_manuscript,
//	'book':f_book,
//	'efimerida-tefxos':f_efimerida_tefxos,
//	'mprosoura':f_book,
//	'periodiko-tefxos':f_periodiko_tefxos,
//	'web-site':f_wsite,
//	'edocs':f_book,
//	'afisa':f_1_page,
//	'autokolito':f_1_page,
//	'flyer':f_1_page,
//	'image':f_1_page,
//	'mprosoura':f_book,
//	'other':f_1_page,
//	'prokiri3i':f_1_page,
//	'web-site-instance':f_web_site_instance,
//	'actor':f_actor,
//	'work':f_work,
//	'place':f_place,
//	'recipe':f_recipe,
//	'material':f_material,
//	'situation':f_situation,
//	'process':f_process,
//	'symbol':f_symbol,
//	'instrument':f_instrument,
//	//
//	'efimerida':f_serial,
//	'periodiko':f_serial,
//	'silogi':f_collection,
//	'artifact1':f_artifact1,
//	'artifact':f_artifact,
//	'bitstream':f_bitstream,
	'auth-person':f_auth_person,
	'auth-family':f_auth_family,
	'auth-organization':f_auth_organization,
	'auth-place':f_auth_place,
	'auth-manifestation':f_auth_manifestation,
	'auth-work':f_auth_work,
	'auth-expression':f_auth_expression,
	'auth-work-man':f_auth_work_man,
	'auth-concept':f_auth_concept,
	'auth-event':f_auth_event,
	'auth-genre':f_auth_genre,
	'auth-object':f_auth_object,
	'auth-general':f_auth_general,
	'auth-object_collection':f_auth_obj_collection,
	'digital-item':f_digital_item,
	'physical-item':f_physical_item,
	'subject-chain':f_subject_chain,
	'collection':f_collection,
};

