
//
////var	subject_type_map = {
////    'ea:subj:general':'Γενικό',
////    'ea:subj:person':'Πρόσωπο',
////    'ea:subj:work':'Έργο',
////    'ea:subj:concept':'Έννοια',
////    'ea:subj:object':'Αντικείμενο',
//////		'ea:subj:person-work':'Person-Work',
////    'ea:subj:event':'Γεγονός',
////    'ea:subj:place':'Περιοχή',
////    'ea:subj:form':'Eίδος',
////};


var	type_manif_map = {
    'BOOK/M':'Βιβλίο έντυπο',
    'BOOD/M':'Ψηφιοποιημένο βιβλίο',
    'BBOE/M':'Ηλεκτρονικό βιβλίο',
    'MANU/M':'Χειρόγραφο (βιβλίο, κώδικας κλπ.)',
    'SERL/S':'Περιοδικό έντυπο',
    'SERD/S':'Περιοδικό ψηφιοποιημένο',
    'SERE/S':'Περιοδικό ηλεκτρονικό ',
    'MUSA/Μ':'Μουσικός Δίσκος 78 στροφών',
    'MUSΒ/Μ':'Μουσικός Δίσκος 45 στροφών',
    'MUSC/Μ':'Μουσικό Άλμπουμ (33 στροφές)',
    'MUSD/M':'Μουσική Κασέτα',
    'MUSE/M':'Μουσικό CD',
    'MUSF/M':'Μουσικό DVD',
    'MUSG/M':'Ψηφιακή μουσική ηχογράφηση',
    'SOUN/M':'Μη μουσική ηχογράφηση',
    'RADI/M':'Ραδιοφωνικό πρόγραμμα',
    'SCOP/M':'Παρτιτούρα έντυπη',
    'SCOM/M':'Παρτιτούρα  χειρόγραφη',
    'FILM/M':'Κινηματογραφική ταινία',
    'TELE/M':'Tηλεοπτικό πρόγραμμα',
    'VIDEO/M':'Video',
    'FOTO/M':'Φωτογραφία, γραμματόσημο, αφίσα, έργο τέχνης κλπ.',
    'STAM/M':'Γραμματόσημο',
    'POST/M':'Αφίσα',
    'ARTM/M':'Έργο τέχνης',
    'THRE/M':'Τρισδιάστατο αντικείμενο (γλυπτό, παιχνίδι κλπ.)',
    'MAPS/M':'Χάρτης',
    'MAPM/M':'Χειρόγραφος χάρτης ',
    'COMP/M':'Ηλεκτρονικοί πόροι (software, multimedia, online συστήμα ή υπηρεσία)',
    'KITS/M':'Κιτ',
    'COLL/C':'Αρχειακή συλλογή',
    'COLL/D':'Υπομονάδα αρχειακής συλλογής',
   };

var type_work_map = {
    'workSubclassTable_Individual':'Αυτοτελή έργα',
    'workSubclassTable_Dependent':'Εξαρτημένα μέρη έργου',
    'workSubclassTable_Independent':'Ανεξάρτητα μέρη έργου',
    'workSubclassTable_Aggregation':'Συλλογές έργων',
    'workSubclassTable_Series':'Έργα σειράς',
    'workSubclassTable_Serial':'Περιοδικά Έργα',
    'workSubclassTable_Other':'Άλλα έργα',

};

var authority_kind_record_map = {
    'authorityKindRecord_a':'Καθιερωμένη επικεφαλίδα',
    'authorityKindRecord_b':'Επεξηγηματική επικεφαλίδα',
    'authorityKindRecord_c':'Παραπεμπτική επικεφαλίδα',
};

var authority_kind_record_extend_map = {
    'authorityKindRecord_c':'Παραπεμπτική επικεφαλίδα',
    'authorityKindRecord_a':'Καθιερωμένη επικεφαλίδα',
    'authorityKindRecord_b':'Επεξηγηματική επικεφαλίδα',
};

var authority_kind_record_concept_map = {
    'authorityKindRecord_a':'a - Established heading',
    'authorityKindRecord_b':'b - Untraced reference',
    'authorityKindRecord_c':'c - Traced reference',
    'authorityKindRecord_d':'d - Subdivision',
    'authorityKindRecord_e':'e - Node label',
    'authorityKindRecord_f':'f - Established heading and subdivision',
    'authorityKindRecord_g':'g - Reference and subdivision',
    'authorityKindRecord_|':'| - No attempt to code',
};

var authority_level_establish_extend_map = {
    'authorityLevelEstablish_c':'Προσωρινό',
    'authorityLevelEstablish_a':'Πλήρης καθιέρωση',
    'authorityLevelEstablish_n':'Δεν εφαρμόζεται',
};

var authority_level_establish_map = {
    'authorityLevelEstablish_a':'Πλήρης καθιέρωση',
    'authorityLevelEstablish_c':'Προσωρινό',
    'authorityLevelEstablish_n':'Δεν εφαρμόζεται',
};

var	additional_title_map = {
   'ea:manif:ParallelTitle': 'Παράλληλος τίτλος',
   'ea:manif:PortionTitle': 'Τίτλος τμήματος',
   'ea:manif:OtherTitle': 'Άλλες παραλλαγές του τίτλου',
   'ea:manif:CoverTitle': 'Τίτλος καλύμματος',
   'ea:manif:AddedTitle': 'Τίτλος πρόσθετης σελίδας τίτλου',
   'ea:manif:CaptionTitle': 'Τίτλος επικεφαλίδας',
   'ea:manif:RunningTitle': 'Τρέχων τίτλος',
   'ea:manif:SpineTitle': 'Τίτλος ράχης',
   'ea:manif:TranslationTitle': 'Μεταφρασμένος τίτλος',
   'ea:manif:AbbreviatedTitle': 'Συντομευμένος τίτλος',
   'ea:manif:KeyTitle': 'Τίτλος κλειδί',
   'ea:manif:FormerTitle': 'Προηγούμενος τίτλος'
 };

var	publications_map = {
    'ea:manif:Publication':'Δημοσίευση',
    'ea:manif:Distribution':'Διάθεση',
    'ea:manif:Production':'Παραγωγή',
    'ea:manif:Manufactur': 'Κατασκευή'
   };

var	media_type_map = {
//		'undefined':'Μη προσδιορισμένο',
//    'manifMediaTypeTable_s':'audio',
//    'manifMediaTypeTable_c':'computer',
//    'manifMediaTypeTable_h':'microform',
//    'manifMediaTypeTable_p':'microscopic',
//    'manifMediaTypeTable_g':'projected',
//    'manifMediaTypeTable_e':'stereographic',
//    'manifMediaTypeTable_n':'unmediated',
//    'manifMediaTypeTable_v':'video',
//    'manifMediaTypeTable_x':'other',
//    'manifMediaTypeTable_z':'unspecified',
//    'manifMediaTypeTable_z':'Απροσδιόριστο (Unspecified)',
    'undefined':'Απροσδιόριστο (Unspecified)',
    'manifMediaTypeTable_s':'Ήχος (Audio)',
    'manifMediaTypeTable_h':'Μικροφόρμα (Microform)',
    'manifMediaTypeTable_c':'Υπολογιστής (Computer)',
    'manifMediaTypeTable_n':'Χωρίς Μέσο (Unmediated)',
    'manifMediaTypeTable_p':'Microscopic',
    'manifMediaTypeTable_g':'Projected',
    'manifMediaTypeTable_e':'Stereographic',
    'manifMediaTypeTable_v':'Video',
    'manifMediaTypeTable_x':'Άλλο',
   };

var	carrier_type_map = {
 'undefined':'Μη προσδιορισμένο',
 'manifCarrierTypeTable_sg':'Audio carriers - audio cartridge',
 'manifCarrierTypeTable_se':'Audio carriers - audio cylinder',
 'manifCarrierTypeTable_sd':'Audio carriers - audio disc',
 'manifCarrierTypeTable_si':'Audio carriers - sound track reel',
 'manifCarrierTypeTable_sq':'Audio carriers - audio roll',
 'manifCarrierTypeTable_ss':'Audio carriers - audiocassette',
 'manifCarrierTypeTable_st':'Audio carriers - audiotape reel',
 'manifCarrierTypeTable_sz':'Audio carriers - other',
 'manifCarrierTypeTable_ck':'Computer carriers - computer card',
 'manifCarrierTypeTable_cb':'Computer carriers - computer chip cartridge',
 'manifCarrierTypeTable_cd':'Computer carriers - computer disc',
 'manifCarrierTypeTable_ce':'Computer carriers - computer disc cartridge',
 'manifCarrierTypeTable_ca':'Computer carriers - computer tape cartridge',
 'manifCarrierTypeTable_cf':'Computer carriers - computer tape cassette',
 'manifCarrierTypeTable_ch':'Computer carriers - computer tape reel',
 'manifCarrierTypeTable_cr':'Computer carriers - online resource',
 'manifCarrierTypeTable_cz':'Computer carriers - other',
 'manifCarrierTypeTable_ha':'Microform carriers - aperture card',
 'manifCarrierTypeTable_he':'Microform carriers - microfiche',
 'manifCarrierTypeTable_hf':'Microform carriers - microfiche cassette',
 'manifCarrierTypeTable_hb':'Microform carriers - microfilm cartridge',
 'manifCarrierTypeTable_hc':'Microform carriers - microfilm cassette',
 'manifCarrierTypeTable_hd':'Microform carriers - microfilm reel',
 'manifCarrierTypeTable_hj':'Microform carriers - microfilm roll',
 'manifCarrierTypeTable_hh':'Microform carriers - microfilm slip',
 'manifCarrierTypeTable_hg':'Microform carriers - microopaque',
 'manifCarrierTypeTable_hz':'Microform carriers - other',
 'manifCarrierTypeTable_pp':'Microscopic carriers - slide',
 'manifCarrierTypeTable_pz':'Microscopic carriers - other',
 'manifCarrierTypeTable_mc':'Projected image - film Projected image - cartridge',
 'manifCarrierTypeTable_mf':'Projected image - film cassette',
 'manifCarrierTypeTable_mr':'Projected image - film reel',
 'manifCarrierTypeTable_mo':'Projected image - film roll',
 'manifCarrierTypeTable_gd':'Projected image - filmslip',
 'manifCarrierTypeTable_gf':'Projected image - filmstrip',
 'manifCarrierTypeTable_gc':'Projected image - filmstrip cartridge',
 'manifCarrierTypeTable_gt':'Projected image - overhead transparency',
 'manifCarrierTypeTable_gs':'Projected image - slide',
 'manifCarrierTypeTable_mz':'Projected image - other',
 'manifCarrierTypeTable_eh':'stereograph card',
 'manifCarrierTypeTable_es':'stereograph disc',
 'manifCarrierTypeTable_ez':'stereograph other',
 'manifCarrierTypeTable_no':'Unmediated carriers - card',
 'manifCarrierTypeTable_nn':'Unmediated carriers - flipchart',
 'manifCarrierTypeTable_na':'Unmediated carriers - roll',
 'manifCarrierTypeTable_nb':'Unmediated carriers - sheet',
 'manifCarrierTypeTable_nc':'Unmediated carriers - volume',
 'manifCarrierTypeTable_nr':'Unmediated carriers - object',
 'manifCarrierTypeTable_nz':'Unmediated carriers - other',
 'manifCarrierTypeTable_vc':'Video carriers - video cartridge',
 'manifCarrierTypeTable_vf':'Video carriers - videocassette',
 'manifCarrierTypeTable_vd':'Video carriers - videodisc',
 'manifCarrierTypeTable_vr':'Video carriers - videotape reel',
 'manifCarrierTypeTable_vz':'Video carriers - other',
 'manifCarrierTypeTable_zu':'Unspecified carriers - unspecified',
};

var	isbn_map = {
    'ea:manif:ISBN_Number':'ISBN',
    'ea:manif:ISSN_Number':'ISSN',
    'ea:manif:ISMN_Number':'ISMN',
   };

var	note_map = {
    'ea:manif:NoteGeneral':'Γενική σημείωση',
    'ea:manif:Note_Content':'Βιβλιογραφία, ευρετηρία',
    'ea:manif:Note_Edition':'Σημείωση έκδοσης',
    'ea:manif:NoteWith':'Σημείωση με',
    'ea:manif:CreditsNote':'Σημείωση συντελεστών δημιουργίας / παραγωγής',
    'ea:manif:CastNote':'Σημείωση cast  συμμετοχών ή performer',
    'ea:manif:SystemNote':'Σημείωση τεχνικών λεπτομερειών',
    'ea:manif:UseTerm':'Σημείωση όρων χρήσης και αναπαραγωγής'
   };


var content_type_map = {
		'expresContentTypeTable_txt':'Κείμενο (Text)',
		'expresContentTypeTable_sti':'Ακίνητη εικόνα (Still image)',
		'expresContentTypeTable_xxx':'Άλλο (Other)',
		'expresContentTypeTable_zzz':'Απροσδιόριστο (Unspecified)',
		'expresContentTypeTable_tdi':'Διδιάστατη κινούμενη εικόνα(Two-dimensional moving image)',
		'expresContentTypeTable_tci':'Εικόνες αφής (Tactile image)',
		'expresContentTypeTable_snd':'Ήχοι (Sounds)',
		'expresContentTypeTable_tct':'Κείμενο αφής (Tactile text)',
		'expresContentTypeTable_ntm':'Παρτιτούρες (Notated music)',
		'expresContentTypeTable_tcm':'Παρτιτούρες αφής (Tactile notated music)',
		'expresContentTypeTable_cop':'Προγράμματα υπολογιστή (Computer program)',
		'expresContentTypeTable_spw':'Προφορικός λόγος (Spoken word)',
		'expresContentTypeTable_tdm':'Τρισδιάστατη κινούμενη εικόνα (Three-dimensional moving image)',
		'expresContentTypeTable_tdf':'Τρισδιάστατη μορφή (Τhree-dimensional form)',
		'expresContentTypeTable_tcf':'Τρισδιάστατη μορφή αφής (Τactile three-dimensional form)',
		'expresContentTypeTable_crd':'Χαρτογραφική dataset (Cartographic dataset)',
		'expresContentTypeTable_cri':'Χαρτογραφική εικόνα (Cartographic image)',
		'expresContentTypeTable_crt':'Χαρτογραφική εικόνα αφής (Cartographic tactile image)',
		'expresContentTypeTable_crm':'Χαρτογραφική κινούμενη εικόνα (Cartographic moving image)',
		'expresContentTypeTable_crf':'Χαρτογραφική τρισδιάστατη μορφή (Cartographic three-dimensional form)',
		'expresContentTypeTable_crn':'Χαρτογραφική τρισδιάστατη μορφή αφής (Cartographic tactile three-dimensional form)',
		'expresContentTypeTable_cod':'Dataset υπολογιστή (Computer dataset)',
		'expresContentTypeTable_ntv':'Notated movement',
		'expresContentTypeTable_prm':'Performed music',
		'expresContentTypeTable_tcn':'Tactile notated movement',
};


//var expres_language_map = {
//	'ea:expres:Language_Text':'Language of text, sound track etc.',
//	'ea:expres:Language_Original':'Language of original',
//	'ea:expres:Language_Intermediate':'Language of intermediate translations',
//	'ea:expres:Language_Sung':'Language of sung or spoken text',
//	'ea:expres:Language_Subtitles':'Language of subtitles or captions',
//	'ea:expres:Language_Summary':'Language of summary or abstract'
//}


var	symbology_tactile_material_map = {
		'expresSymbologyTable_b':'Braille',
		'expresSymbologyTable_c':'Combination',
		'expresSymbologyTable_a':'Moon',
		'expresSymbologyTable_d':'Tactile, with no writing system',
		'expresSymbologyTable_z':'Άλλο (Other)',
		'expresSymbologyTable_u':'Απροσδιόριστο (Unspecified)',
		'expresSymbologyTable_|':'Δεν εφαρμόζεται κωδικός',
   };

var actor_type_map = {
    'undefined': 'undefined',
    'person': 'Person',
    'collective':'Collective',
    'collective_name':'Collective Name',
    'corporate_body':'Corporate Body',
    'family':'Family',
  };

var personal_type_map = {
		'typePersonalName_1': 'Επώνυμο',
    'typePersonalName_0': 'Όνομα',
//		'typePersonalName_3': 'Family name',
  };

var organization_name_map  = {
    'ControlSubfieldRelation_d':'Όνομα Organization σε ευθεία μορφή',
    'ControlSubfieldRelation_a':'Όνομα Organization σε αντεστραμμένη μορφή',
    'ControlSubfieldRelation_b':'Όνομα Organization σε τόπο ή πολιτική δικαιοδοσία',
    'ControlSubfieldRelation_e':'Συνέδριο σε αντεστραμμένη μορφή',
    'ControlSubfieldRelation_f':'Συνέδριο σε τόπο ή πολιτική δικαιοδοσία',
    'ControlSubfieldRelation_g':'Συνέδριο σε ευθεία μορφή',
};


var organization_type_map  = {
		'undefined':'Μη προσδιορισμένος τύπος',
		'OrganizationTypeUnknown':'Άγνωστου τύπου οργανισμός',
		'OrganizationTypeSport':'Αθλητικός οργανισμός',
		'OrganizationTypeOther':'Άλλου τύπου οργανισμός',
		'OrganizationTypeResistance':'Αντιστασιακή οργάνωση',
		'OrganizationTypeWomen':'Γυναικεία οργάνωση',
		'OrganizationTypeMunicipal':'Δήμος',
		'OrganizationTypePublic':'Δημόσια υπηρεσία',
		'OrganizationTypeMunicipalUnit':'Δημοτική ενότητα',
		'OrganizationTypeInternational':'Διεθνής οργάνωση',
		'OrganizationTypeJudicial':'Δικαστικός οργανισμός',
		'OrganizationTypePublishers':'Εκδοτικός οργανισμός',
		'OrganizationTypeEcclesiastical':'Εκκλησιαστικός οργανισμός',
		'OrganizationTypeEducational':'Εκπαιδευτικό ίδρυμα',
		'OrganizationTypeCommercial':'Εμπορική οργάνωση',
		'OrganizationTypeArmy':'Ένοπλες δυνάμεις',
		'OrganizationTypeProfessional':'Επαγγελματική οργάνωση',
		'OrganizationTypeBusiness':'Επιχείρηση',
		'OrganizationTypeCompany':'Εταιρεία',
		'OrganizationTypeWorkshop':'Ημερίδα - Διημερίδα',
		'OrganizationTypeReligious':'Θρησκευτική οργάνωση',
		'OrganizationTypePrivately':'Ιδιωτικός οργανισμός',
		'OrganizationTypeFoundation':'Ίδρυμα',
		'OrganizationTypeGuild':'Ινστιτούτο',
		'OrganizationTypeArt':'Καλλιτεχνική οργάνωση',
		'OrganizationTypeCommunity':'Κοινότητα',
		'OrganizationTypeSocial':'Κοινωνική οργάνωση',
		'OrganizationTypeState':'Κράτος',
		'OrganizationTypeGovernment':'Κυβερνητικός οργανισμός',
		'OrganizationTypeLiterary':'Λογοτεχνική οργάνωση',
		'OrganizationTypeNongovernment':'Μη κυβερνητική οργάνωση',
		'OrganizationTypeSecret':'Μυστική οργάνωση',
		'OrganizationTypeEcology':'Οικολογική  οργάνωση',
		'OrganizationTypeParamilitary':'Παραστρατιωτική οργάνωση',
		'OrganizationTypeAdministrative':'Περιφέρεια',
		'OrganizationTypeRegional':'Περιφερειακή ενότητα',
		'OrganizationTypePolitical':'Πολιτική οργάνωση',
		'OrganizationTypePoliticalyouth':'Πολιτική οργάνωση νέων',
		'OrganizationTypePoliticalparty':'Πολιτικό κόμμα',
		'OrganizationTypeCultural':'Πολιτιστική οργάνωση',
		'OrganizationTypeMilitary':'Πολιτοφυλακή',
		'OrganizationTypeMilitary':'Στρατιωτικό σκέλος αντιστασιακών οργανώσεων',
		'OrganizationTypeAlliancesparty':'Συνασπισμός πολιτικών κομμάτων',
		'OrganizationTypeTrade':'Συνδικαλιστική οργάνωση',
		'OrganizationTypeCongress':'Συνέδριο',
		'OrganizationTypeCooperative':'Συνεταιριστική οργάνωση',
		'OrganizationTypeTreaty':'Συνθήκη',
		'OrganizationTypeGuild':'Συντεχνιακή οργάνωση',
		'OrganizationTypeSecurity':'Σώμα ασφαλείας',
		'OrganizationTypeBanking':'Τραπεζικός οργανισμός',
		'OrganizationTypeTerrorist':'Τρομοκρατική οργάνωση',
		'OrganizationTypeCharitable':'Φιλανθρωπική οργάνωση',
		'OrganizationTypeEntertainment':'Ψυχαγωγική  οργάνωση',
	};


var gender_map = {
		'undefined':'Μη προσδιορισμένο',
    'male': 'Άνδρας',
    'female': 'Γυναίκα',
  };


var item_type_map_pdf= {
		'undefined':'Μη προσδιορισμένος',
		'pdf':'PDF σκαναρισμένο (scanned)',
		'daisy':'PDF με αναγνώρηση χαρακτήρων (OCR)',
};

var physical_item_type_map= {
		'undefined':'Μη προσδιορισμένος',
		'book':'Βιβλίο',
		'braille':'Braille',
		'magazine':'Περιοδικό',
		'map':'Χάρτης',
		'dvd':'DVD',
		'cd-rom':'CD-ROM',
		'lp':'Δίσκος LP',
};

var item_location_map = {
		'altsol_demo':'RG Demo',
  };

//var item_sublocation_map = {
//		'panteio':'Πάντειο Πανεπιστήμιο',
//		'pamak':'Πανεπιστήμιο Μακεδονίας',
//		'panthessalias':'Πανεπιστήμιο Θεσσαλίας',
//		'ebe':'Εθνική Βιβλιοθήκη',
//		'ioniopan':'Ιόνιο Πανεπιστήμιο',
//		'keat':'Κέντρο Εκπαίδευσης και Αποκατάστασης Τυφλών',
//		'opa':'Οικονομικό Πανεπιστήμιο Αθηνών',
//		'pst':'Πανελλήνιος Σύνδεσμος Τυφλών',
//		'teikritis':'ΤΕΙ Κρήτης',
//		'faros':'Φάρος Τυφλών',
//  };

var item_sublocation_map = {
		'0':'RG Demo',
  };

var item_collection_map = {
		'undefined':'Μη προσδιορισμένο',
  };

var item_reproduction_map = {
'itemReproductionTable_a':'Με περιορισμούς αναπαραγωγής',
'undefined':'Μη προσδιορισμένοι',
'itemReproductionTable_b':'Χωρίς περιορισμούς αναπαραγωγής',
'itemReproductionTable_u':'Άγνωστοι περιορισμοί αναπαραγωγής',
};

var item_loan_map = {
'itemLoanTableGeneral':'Γενικός δανεισμός',
'itemLoanTableSpecial':'Ειδικός δανεισμός',
'itemLoanTableNotloan':'Δεν δανείζεται',
'itemLoanTableLimited':'Περιορισμένος δανεισμός',
};

var item_acquisition_method_map = {
'undefined':'Μη προσδιορισμένη',
'itemAcquisitionMethodTable_c':'Συνεργατική ή μέσω κοινοπραξίας αγορά',
'itemAcquisitionMethodTable_d':'Deposit',
'itemAcquisitionMethodTable_e':'Ανταλλαγή',
'itemAcquisitionMethodTable_f':'Free',
'itemAcquisitionMethodTable_g':'Δωρεά',
'itemAcquisitionMethodTable_l':'Κατά νόμο προσφορά',
'itemAcquisitionMethodTable_m':'Μέλος',
'itemAcquisitionMethodTable_n':'Αγορά (εκτός βιβλιοθήκης)',
'itemAcquisitionMethodTable_p':'Αγορά',
'itemAcquisitionMethodTable_u':'Άγνωστη',
'itemAcquisitionMethodTable_z':'Άλλη μέθοδος απόκτησης',
};


var place_type_map = {
'undefined':'Μη προσδιορισμένη τιμή',
'Acropolis':'Ακρόπολη',
'Cape':'Ακρωτήρι',
'Mountain':'Βουνό',
'Islet':'Βραχονησίδα',
'Département':'Γεωγραφικό διαμέρισμα',
'River_Delta':'Δέλτα ποταμού',
'Union_Countries':'Ένωση χωρών',
'Desert':'Έρημος',
'Continent':'Ήπειρος',
'Volcano':'Ηφαίστειο',
'Isthmus':'Ισθμός',
'Castle':'Κάστρο',
'Cataract':'Καταρράκτης',
'Ridge':'Κορυφογραμμή',
'Town':'Κωμόπολη',
'Avenue':'Λεωφόρος',
'Port':'Λιμάνι',
'Lake':'Λίμνη',
'Hill':'Λόφος',
'Island':'Νησί',
'Province':'Νομός',
'Street':'Οδός',
'Hamlet':'Οικισμός',
'Mountain_pass':'Ορεινό πέρασμα',
'Cove':'Όρμος',
'Plateau':'Οροπέδιο',
'Sierra':'Οροσειρά',
'Beach':'Παραλία',
'Plain':'Πεδιάδα',
'Region':'Περιοχή',
'Square':'Πλατεία',
'City':'Πόλη',
'State':'Πολιτεία',
'Strait':'Πορθμός',
'River':'Ποτάμι',
'Cave':'Σπήλαιο',
'District':'Συνοικία',
'Canyon':'Φαράγγι',
'Peninsula':'Χερσόνησος',
'Country':'Χώρα',
'Village':'Χωριό',
'Unknown':'Άγνωστος τύπος Place',
}


var language_min_map = {
    "undefined": "undefined",
    "gre":"Ελληνική",
    "grc":"Ελληνική, Αρχαία (μέχρι 1453)",
    "eng": "Αγγλική",
    "deu": "Γερμανικά",
    "fra": "Γαλλικά",
    "rus": "Russian",
    "bul": "Bulgarian",
    "bel": "Belarusian",
    "geo": "Georgian",
    "rum": "Romanian",
    "srp": "Serbian",
    "ukr": "Ukrainian",
}

var language_map = {
'undefined':'Μη προσδιορισμένη',
'gre':'Ελληνική',
'grc':'Ελληνική, Αρχαία (μέχρι 1453)',
'ave':'Αβεστική',
'eng':'Αγγλική',
'ang':'Αγγλική, Αρχαία (ca. 450-1100)',
'enm':'Αγγλική, Μεσαιωνική (1100-1500)',
'aze':'Αζερική',
'egy':'Αιγυπτιακή',
'gez':'Αιθιοπική',
'akk':'Ακκαδική',
'alb':'Αλβανική',
'alg':'Αλγκονκινική',
'tut':'Αλταϊκή (Άλλες)',
'und':'Απροσδιόριστη',
'ara':'Αραβική',
'arg':'Αραγκονική',
'arc':'Αραμαϊκή',
'arm':'Αρμενική',
'afr':'Αφρικάανς',
'afa':'Αφροασιατική',
'wln':'Βαλλωνική',
'bat':'Βαλτική (Άλλες)',
'baq':'Βασκική',
'ber':'Βερβερική (Άλλη)',
'vie':'Βιετναμέζικη',
'vol':'Βολαπιούκ',
'bos':'Βοσνιακή',
'bul':'Βουλγαρική',
'glg':'Γαλικιανή',
'fre':'Γαλλική',
'fro':'Γαλλική, Αρχαία (π. 842-1300)',
'frm':'Γαλλική, Μεσαιωνική (π.1300-1600)',
'gsw':'Γερμανικά, Ελβετικά',
'ger':'Γερμανική',
'gem':'Γερμανική (Άλλες)',
'goh':'Γερμανική, Αρχαία Υψηλή (π. 750-1050)',
'gmh':'Γερμανική, Μεσαιωνική Υψηλή (π. 1050-1500)',
'geo':'Γεωργιανή',
'yid':'Γίντις',
'yor':'Γιορουμπά',
'got':'Γοτθική',
'dan':'Δανική',
'mis':'Διάφορες γλώσσες',
'dra':'Δραβιδική (Άλλη)',
'heb':'Εβραϊκή',
'est':'Εσθονική',
'epo':'Εσπεράντο',
'zza':'Ζαζαϊκή',
'zul':'Ζουλού',
'tib':'Θιβετιανή',
'jpn':'Ιαπωνική',
'aus':'Ινδογενής αυστραλιανές γλώσσες',
'ine':'Ινδοευρωπαϊκή (Άλλες)',
'ind':'Ινδονησιακή',
'ido':'Ίντο',
'ira':'Ιρανική (Άλλες)',
'gle':'Ιρλανδική',
'sga':'Ιρλανδική, Αρχαία (μέχρι το 1100)',
'mga':'Ιρλανδική, Μεσαιωνική (π.1100-1550)',
'iro':'Ιροκουά (Άλλες)',
'ice':'Ισλανδική',
'spa':'Ισπανική',
'ita':'Ιταλική',
'nap':'Ιταλική, Ναπολίτικη ',
'scn':'Ιταλική, Σικελική',
'kaz':'Καζακική',
'kbd':'Καμπαντική',
'cat':'Καταλανική',
'cau':'Καυκάσια (Άλλες)',
'cel':'Κέλτικες (Άλλες)',
'que':'Κέτσουα',
'chi':'Κινεζική',
'kon':'Κονγκολεζική',
'cop':'Κοπτική',
'hrv':'Κορατική',
'kor':'Κορεατική',
'cor':'Κορνουαλική',
'cos':'Κορσικανική',
'kur':'Κουρδική',
'cus':'Κουσιτική (Άλλες)',
'crp':'Κρεολική και Pidgins (Άλλες)',
'cre':'Κρι',
'crh':'Κριμαϊκή Ταταρική',
'kro':'Κρου (Άλλες)',
'lad':'Λαντίνο (Ισπανοεβραϊκή)',
'lat':'Λατινική',
'lav':'Λεττονική',
'bel':'Λευκορωσική',
'lit':'Λιθουανική',
'lim':'Λιμβουργιανή',
'ltz':'Λουξεμβουργιανή',
'mlt':'Μαλτεζική',
'glv':'Μανξ',
'mao':'Μαορί',
'mas':'Μασάι ',
'zxx':'Μη γλωσσικό περιεχόμενο',
'mon':'Μογγολική',
'moh':'Μόχακ',
'bnt':'Μπαντού (Άλλες)',
'ben':'Μπενγκάλι',
'bis':'Μπισλάμα',
'bre':'Μπρετονική',
'nau':'Ναουρού',
'nah':'Ναχουάτλ',
'new':'Νεβάρι',
'nep':'Νεπαλεζική',
'sgn':'Νοηματικές γλώσσες',
'nor':'Νορβηγική',
'nob':'Νορβηγική (Bokmål)',
'nno':'Νορβηγική (Nynorsk)',
'div':'Ντιβέχι',
'dut':'Ολλανδική',
'dum':'Ολλανδική, Μεσαιωνική (π. 1050-1350)',
'oto':'Οξιτανικές γλώσσες',
'wel':'Ουαλική',
'hun':'Ουγγαρική',
'uga':'Ουγκαριτική',
'uzb':'Ουζμπεκική',
'ukr':'Ουκρανική',
'pau':'Παλάου',
'paa':'Παπούα (Άλλες)',
'per':'Περσική',
'peo':'Περσική, Αρχαία (π. 600-400 π.Χ)',
'mul':'Πολλαπλές γλώσσες',
'pol':'Πολωνική',
'por':'Πορτογαλλική',
'rom':'Ρομάνι',
'roa':'Ρομανική (Άλλες)',
'rum':'Ρουμανική',
'rus':'Ρωσική',
'smo':'Σαμόα (γλώσσα)',
'san':'Σανσκριτική',
'srd':'Σαρδινική',
'srp':'Σερβική',
'sem':'Σημιτικές (Άλλες)',
'sit':'Σινοθιβετική (Άλλες)',
'non':'Σκανδιναβική, Αρχαία',
'sco':'Σκωτική',
'gla':'Σκωτική Γαελική',
'sla':'Σλαβική (Άλλες)',
'chu':'Σλαβική εκκλησιαστική',
'mac':'Σλαβομακεδονική',
'slo':'Σλοβακική',
'slv':'Σλοβενική',
'som':'Σομαλική',
'wen':'Σορβική (Άλλες)',
'swa':'Σουαχίλι',
'swe':'Σουηδική',
'sux':'Σουμεριακή',
'syc':'Συριακή, Κλασική',
'syr':'Συριακή, Σύγχρονη',
'tgl':'Ταγκαλόγκ',
'tai':'Τάι (Άλλες)',
'tha':'Ταϊλανδική',
'tam':'Ταμίλ',
'tat':'Ταταρική',
'tgk':'Τατζικική',
'tel':'Τελούγκου',
'art':'Τεχνητή (Άλλη)',
'tur':'Τουρκική',
'ota':'Τουρκική, Οθωμανική',
'tuk':'Τουρκμένικη',
'cmc':'Τσαμικές γλώσσες',
'chr':'Τσερόκι',
'che':'Τσετσενική',
'cze':'Τσεχική',
'fil':'Φιλιππινεζική',
'fin':'Φινλανδική',
'haw':'Χαβαϊκή',
'hit':'Χεττιτική',
'hin':'Χίντι',
'khm':'Χμερ',
'aar':'Afar',
'abk':'Abkhaz',
'ace':'Achinese',
'ach':'Acoli',
'ada':'Adangme',
'ady':'Adygei',
'afh':'Afrihili (Artificial language)',
'ain':'Ainu',
'aka':'Akan',
'ale':'Aleut',
'alt':'Altai',
'amh':'Amharic',
'anp':'Angika',
'apa':'Apache languages',
'arp':'Arapaho',
'arw':'Arawak',
'rup':'Aromanian',
'asm':'Assamese',
'ath':'Athapascan (Other)',
'map':'Austronesian (Other)',
'ava':'Avaric',
'awa':'Awadhi',
'aym':'Aymara',
'ast':'Bable',
'ban':'Balinese',
'bal':'Baluchi',
'bam':'Bambara',
'bai':'Bamileke languages',
'bad':'Banda languages',
'bas':'Basa',
'bak':'Bashkir',
'btk':'Batak',
'bej':'Beja',
'bem':'Bemba',
'bho':'Bhojpuri',
'bih':'Bihari (Other)',
'bik':'Bikol',
'byn':'Bilin',
'bin':'Bini, Edo',
'zbl':'Blissymbolics',
'bra':'Braj',
'bug':'Bugis',
'bua':'Buriat',
'bur':'Burmese',
'cad':'Caddo',
'car':'Carib',
'ceb':'Cebuano',
'cai':'Central American Indian (Other)',
'chg':'Chagatai',
'cha':'Chamorro',
'chy':'Cheyenne',
'chb':'Chibcha',
'chn':'Chinook jargon',
'chp':'Chipewyan',
'cho':'Choctaw',
'chk':'Chuukese',
'chv':'Chuvash',
'mus':'Creek',
'cpe':'Creoles and Pidgins, English-based (Other)',
'cpf':'Creoles and Pidgins, French-based (Other)',
'cpp':'Creoles and Pidgins, Portuguese-based (Other)',
'dak':'Dakota',
'dar':'Dargwa',
'day':'Dayak',
'del':'Delaware',
'din':'Dinka',
'doi':'Dogri',
'dgr':'Dogrib',
'dua':'Duala',
'dyu':'Dyula',
'dzo':'Dzongkha',
'frs':'East Frisian',
'efi':'Efik',
'eka':'Ekajuk',
'elx':'Elamite',
'myv':'Erzya',
'ewe':'Ewe',
'ewo':'Ewondo',
'fan':'Fang',
'fat':'Fanti',
'fao':'Faroese',
'fij':'Fijian',
'fiu':'Finno-Ugrian (Other)',
'fon':'Fon',
'fry':'Frisian',
'fur':'Friulian',
'ful':'Fula',
'gaa':'Gã',
'lug':'Ganda',
'gay':'Gayo',
'gba':'Gbaya',
'gil':'Gilbertese',
'gon':'Gondi',
'gor':'Gorontalo',
'grb':'Grebo',
'grn':'Guarani',
'guj':'Gujarati',
'gwi':'Gwich in',
'hai':'Haida',
'hat':'Haitian French Creole',
'hau':'Hausa',
'her':'Herero',
'hil':'Hiligaynon',
'hmo':'Hiri Motu',
'hmn':'Hmong',
'hup':'Hupa',
'iba':'Iban',
'ibo':'Igbo',
'ijo':'Ijo',
'ilo':'Iloko',
'smn':'Inari Sami',
'inc':'Indic (Other)',
'inh':'Ingush',
'ina':'Interlingua (International Auxiliary Language Association)',
'ile':'Interlingue',
'iku':'Inuktitut',
'ipk':'Inupiaq',
'jav':'Javanese',
'jrb':'Judeo-Arabic',
'jpr':'Judeo-Persian',
'kab':'Kabyle',
'kac':'Kachin',
'kal':'Kalâtdlisut',
'kam':'Kamba',
'kan':'Kannada',
'kau':'Kanuri',
'kaa':'Kara-Kalpak',
'krc':'Karachay-Balkar',
'krl':'Karelian',
'kar':'Karen languages',
'kas':'Kashmiri',
'csb':'Kashubian',
'kaw':'Kawi',
'kha':'Khasi',
'khi':'Khoisan (Other)',
'kho':'Khotanese',
'kik':'Kikuyu',
'kmb':'Kimbundu',
'kin':'Kinyarwanda',
'tlh':'Klingon (Artificial language)',
'kom':'Komi',
'kok':'Konkani',
'kut':'Kootenai',
'kos':'Kosraean',
'kpe':'Kpelle',
'kua':'Kuanyama',
'kum':'Kumyk',
'kru':'Kurukh',
'kir':'Kyrgyz',
'lah':'Lahndā',
'lam':'Lamba (Zambia and Congo)',
'lao':'Lao',
'lez':'Lezgian',
'lin':'Lingala',
'jbo':'Lojban (Artificial language)',
'nds':'Low German',
'dsb':'Lower Sorbian',
'loz':'Lozi',
'lub':'Luba-Katanga',
'lua':'Luba-Lulua',
'lui':'Luiseño',
'smj':'Lule Sami',
'lun':'Lunda',
'luo':'Luo (Kenya and Tanzania)',
'lus':'Lushai',
'mad':'Madurese',
'mag':'Magahi',
'mai':'Maithili',
'mak':'Makasar',
'mlg':'Malagasy',
'may':'Malay',
'mal':'Malayalam',
'mnc':'Manchu',
'mdr':'Mandar',
'man':'Mandingo',
'mni':'Manipuri',
'mno':'Manobo languages',
'arn':'Mapuche',
'mar':'Marathi',
'chm':'Mari',
'mah':'Marshallese',
'mwr':'Marwari',
'myn':'Mayan languages',
'men':'Mende',
'mic':'Micmac',
'min':'Minangkabau',
'mwl':'Mirandese',
'mdf':'Moksha',
'mkh':'Mon-Khmer (Other)',
'lol':'Mongo-Nkundu',
'mos':'Mooré',
'mun':'Munda (Other)',
'nqo':'N Ko',
'nav':'Navajo',
'nbl':'Ndebele (South Africa)',
'nde':'Ndebele (Zimbabwe)',
'ndo':'Ndonga',
'nwc':'Newari, Old',
'nia':'Nias',
'nic':'Niger-Kordofanian (Other)',
'ssa':'Nilo-Saharan (Other)',
'niu':'Niuean',
'nog':'Nogai',
'nai':'North American Indian (Other)',
'frr':'North Frisian',
'sme':'Northern Sami',
'nso':'Northern Sotho',
'nub':'Nubian languages',
'nym':'Nyamwezi',
'nya':'Nyanja',
'nyn':'Nyankole',
'nyo':'Nyoro',
'nzi':'Nzima',
'xal':'Oirat',
'pal':'Pahlavi',
'pli':'Pali',
'pam':'Pampanga',
'pag':'Pangasinan',
'pan':'Panjabi',
'pap':'Papiamento',
'phi':'Philippine (Other)',
'phn':'Phoenician',
'pon':'Pohnpeian',
'pra':'Prakrit languages',
'pro':'Provençal (to 1500)',
'pus':'Pushto',
'roh':'Raeto-Romance',
'raj':'Rajasthani',
'rap':'Rapanui',
'rar':'Rarotongan',
'run':'Rundi',
'sal':'Salishan languages',
'sam':'Samaritan Aramaic',
'smi':'Sami',
'sad':'Sandawe',
'sag':'Sango (Ubangi Creole)',
'sat':'Santali',
'sas':'Sasak',
'sel':'Selkup',
'srr':'Serer',
'shn':'Shan',
'sna':'Shona',
'iii':'Sichuan Yi',
'sid':'Sidamo',
'bla':'Siksika',
'snd':'Sindhi',
'sin':'Sinhalese',
'sio':'Siouan (Other)',
'sms':'Skolt Sami',
'den':'Slavey',
'sog':'Sogdian',
'son':'Songhai',
'snk':'Soninke',
'sot':'Sotho',
'sai':'South American Indian (Other)',
'sma':'Southern Sami',
'srn':'Sranan',
'suk':'Sukuma',
'sun':'Sundanese',
'sus':'Susu',
'ssw':'Swazi',
'tah':'Tahitian',
'tmh':'Tamashek',
'tem':'Temne',
'ter':'Terena',
'tet':'Tetum',
'tig':'Tigré',
'tir':'Tigrinya',
'tiv':'Tiv',
'tli':'Tlingit',
'tpi':'Tok Pisin',
'tkl':'Tokelauan',
'tog':'Tonga (Nyasa)',
'ton':'Tongan',
'tsi':'Tsimshian',
'tso':'Tsonga',
'tsn':'Tswana',
'tum':'Tumbuka',
'tup':'Tupi languages',
'tvl':'Tuvaluan',
'tyv':'Tuvinian',
'twi':'Twi',
'udm':'Udmurt',
'uig':'Uighur',
'umb':'Umbundu',
'hsb':'Upper Sorbian',
'urd':'Urdu',
'vai':'Vai',
'ven':'Venda',
'vot':'Votic',
'wak':'Wakashan languages',
'war':'Waray',
'was':'Washoe',
'him':'Western Pahari languages',
'wal':'Wolayta',
'wol':'Wolof',
'xho':'Xhosa',
'sah':'Yakut',
'yao':'Yao (Africa)',
'yap':'Yapese',
'ypk':'Yupik languages',
'znd':'Zande languages',
'zap':'Zapotec',
'zen':'Zenaga',
'zha':'Zhuang',
'zun':'Zuni',

};


//var language_map = {
//'undefined':'Μη προσδιορισμένη',
//'gre':'Ελληνική',
//'grc':'Ελληνική, Αρχαία (μέχρι 1453)',
//'alb':'Αλβανική',
//'ara':'Αραβική',
//'arm':'Αρμενική',
//'baq':'Βασκική',
//'bel':'Λευκορωσική',
//'bos':'Βοσνιακή',
//'bul':'Βουργαρική',
//'cat':'Καταλανική',
//'chi':'Κινεζική',
//'cop':'Κοπτική',
//'cze':'Τσεχική',
//'dan':'Δανική',
//'dut':'Ολλανδική',
//'egy':'Αιγυπτιακή',
//'eng':'Αγγλική',
//'ang':'Αγγλική, Αρχαία (ca. 450-1100)',
//'enm':'Αγγλική',
//'fin':'Φινλανδική',
//'fre':'Γαλλική',
//'geo':'Γεωργιανή',
//'ger':'Γερμανική',
//'gle':'Ιρλανδική',
//'heb':'Εβραϊκή',
//'hrv':'Κορατική',
//'hun':'Ουγγαρική',
//'ice':'Ισλανδική',
//'ita':'Ιταλική',
//'jpn':'Ιαπωνική',
//'kor':'Κορεατική',
//'kur':'Κουρδική',
//'lat':'Λατινική',
//'mis':'Διάφορες γλώσσες',
//'mul':'Πολλαπλές γλώσσες',
//'per':'Περσική',
//'pol':'Πολωνική',
//'por':'Πορτογαλλική',
//'rom':'Ρομά',
//'rum':'Ρουμανική',
//'rus':'Ρωσική',
//'slo':'Σλοβακική',
//'slv':'Σλοβενική',
//'spa':'Ισπανική',
//'srp':'Σερβική',
//'swe':'Σουηδική',
//'tur':'Τουρκική',
//'ota':'Τουρκική, Οθωμανική',
//'ukr':'Ουκρανική',
//};


var county_map = {
'undefined':'Μη προσδιορισμένη',
'GR':'Ελλάδα',
'LC':'Αγία Λουκία',
'BL':'Άγιος Βαρθολομαίος',
'VC':'Άγιος Βικέντιος και Γρεναδίνες',
'SM':'Άγιος Μαρίνος',
'MF':'Άγιος Μαρτίνος (Γαλλία)',
'SX':'Άγιος Μαρτίνος (Ολλανδία)',
'KN':'Άγιος Χριστόφορος και Νέβις',
'AZ':'Αζερμπαϊτζάν',
'EG':'Αίγυπτος',
'ET':'Αιθιοπία',
'HT':'Αϊτή',
'CI':'Ακτή Ελεφαντοστού',
'AL':'Αλβανία',
'DZ':'Αλγερία',
'VI':'Αμερικανικές Παρθένοι Νήσοι',
'AS':'Αμερικανική Σαμόα',
'TL':'Ανατολικό Τιμόρ',
'AO':'Ανγκόλα',
'AI':'Ανγκουίλα',
'AD':'Ανδόρρα',
'AQ':'Ανταρκτική',
'AG':'Αντίγκουα και Μπαρμπούντα',
'UM':'Απομακρυσμένες Νησίδες των Ηνωμένων Πολιτειών',
'AR':'Αργεντινή',
'AM':'Αρμενία',
'AW':'Αρούμπα',
'AU':'Αυστραλία',
'AT':'Αυστρία',
'AF':'Αφγανιστάν',
'VU':'Βανουάτου',
'VA':'Βατικανό',
'BE':'Βέλγιο',
'VE':'Βενεζουέλα',
'BM':'Βερμούδες',
'VN':'Βιετνάμ',
'BO':'Βολιβία',
'MP':'Βόρειες Μαριάνες Νήσοι',
'BA':'Βοσνία και Ερζεγοβίνη',
'BG':'Βουλγαρία',
'BR':'Βραζιλία',
'VG':'Βρετανικές Παρθένοι Νήσοι',
'IO':'Βρετανικό Έδαφος Ινδικού Ωκεανού',
'FR':'Γαλλία',
'TF':'Γαλλικά Νότια και Ανταρκτικά Εδάφη',
'GF':'Γαλλική Γουιάνα',
'PF':'Γαλλική Πολυνησία',
'DE':'Γερμανία',
'GE':'Γεωργία',
'GI':'Γιβραλτάρ',
'GM':'Γκάμπια',
'GA':'Γκαμπόν',
'GH':'Γκάνα',
'GU':'Γκουάμ',
'GP':'Γουαδελούπη',
'GT':'Γουατεμάλα',
'GY':'Γουιάνα',
'GN':'Γουινέα',
'GW':'Γουινέα-Μπισσάου',
'GD':'Γρενάδα',
'GL':'Γροιλανδία',
'DK':'Δανία',
'CG':'Δημοκρατία του Κονγκό',
'DM':'Δομινίκα',
'DO':'Δομινικανή Δημοκρατία',
'EH':'Δυτική Σαχάρα',
'EC':'Εκουαδόρ',
'SV':'Ελ Σαλβαδόρ',
'CH':'Ελβετία',
'ER':'Ερυθραία',
'EE':'Εσθονία',
'ZM':'Ζάμπια',
'ZW':'Ζιμπάμπουε',
'AE':'Ηνωμένα Αραβικά Εμιράτα',
'US':'Ηνωμένες Πολιτείες Αμερικής',
'JP':'Ιαπωνία',
'IN':'Ινδία',
'ID':'Ινδονησία',
'JO':'Ιορδανία',
'IQ':'Ιράκ',
'IR':'Ιράν',
'IE':'Ιρλανδία',
'GQ':'Ισημερινή Γουινέα',
'IS':'Ισλανδία',
'ES':'Ισπανία',
'IL':'Ισραήλ',
'IT':'Ιταλία',
'KZ':'Καζακστάν',
'CM':'Καμερούν',
'KH':'Καμπότζη',
'CA':'Καναδάς',
'QA':'Κατάρ',
'KY':'Κέιμαν Νήσοι',
'CF':'Κεντροαφρικανική Δημοκρατία',
'KE':'Κένυα',
'CN':'Κίνα',
'KG':'Κιργιζία',
'KI':'Κιριμπάτι',
'CO':'Κολομβία',
'KM':'Κομόρες',
'KP':'Κορέα, Βόρεια',
'KR':'Κορέα, Νότια',
'CR':'Κόστα Ρίκα',
'CU':'Κούβα',
'KW':'Κουβέιτ',
'CW':'Κουρασάο',
'HR':'Κροατία',
'CY':'Κύπρος',
'CD':'Λαϊκή Δημοκρατία του Κονγκό',
'LA':'Λάος',
'LS':'Λεσότο',
'LV':'Λετονία',
'BY':'Λευκορωσία',
'LB':'Λίβανος',
'LR':'Λιβερία',
'LY':'Λιβύη',
'LT':'Λιθουανία',
'LI':'Λιχτενστάιν',
'LU':'Λουξεμβούργο',
'YT':'Μαγιότ',
'MG':'Μαδαγασκάρη',
'MO':'Μακάου',
'MY':'Μαλαισία',
'MW':'Μαλάουι',
'MV':'Μαλδίβες',
'ML':'Μάλι',
'MT':'Μάλτα',
'MA':'Μαρόκο',
'MQ':'Μαρτινίκα',
'MU':'Μαυρίκιος',
'MR':'Μαυριτανία',
'ME':'Μαυροβούνιο',
'GB':'Μεγάλη Βρετανία',
'MX':'Μεξικό',
'MM':'Μιανμάρ (Βιρμανία)',
'FM':'Μικρονησία (Ομόσπονδες Πολιτείες)',
'MN':'Μογγολία',
'MZ':'Μοζαμβίκη',
'MD':'Μολδαβία',
'MC':'Μονακό',
'MS':'Μοντσερράτ',
'BD':'Μπανγκλαντές',
'BB':'Μπαρμπάντος',
'BS':'Μπαχάμες',
'BH':'Μπαχρέιν',
'BZ':'Μπελίζ',
'BJ':'Μπενίν',
'BQ':'Μποναίρ, Άγιος Ευστάθιος και Σάμπα (BES νησιά)',
'BW':'Μποτσουάνα',
'BV':'Μπουβέ, Νησί',
'BF':'Μπουρκίνα Φάσο',
'BI':'Μπουρούντι',
'BT':'Μπουτάν',
'BN':'Μπρουνέι',
'NA':'Ναμίμπια',
'NR':'Ναουρού',
'NZ':'Νέα Ζηλανδία',
'NC':'Νέα Καληδονία',
'NP':'Νεπάλ',
'NF':'Νησί Νόρφολκ',
'CC':'Νησιά Κόκος (Κήλινγκ)',
'CK':'Νήσοι Κουκ',
'MH':'Νήσοι Μάρσαλ',
'GS':'Νήσοι Νότια Γεωργία και Νότιες Σάντουιτς',
'PN':'Νήσοι Πίτκαιρν',
'SB':'Νήσοι Σολομώντα',
'FO':'Νήσοι Φερόες',
'FK':'Νήσοι Φώκλαντ (Μαλβίνας)',
'HM':'Νήσοι Χερντ και Μακντόναλντ',
'AX':'Νήσοι Ώλαντ',
'IM':'Νήσος του Μαν',
'CX':'Νήσος των Χριστουγέννων',
'NE':'Νίγηρας',
'NG':'Νιγηρία',
'NI':'Νικαράγουα',
'NU':'Νιούε',
'NO':'Νορβηγία',
'ZA':'Νότια Αφρική',
'SS':'Νότιο Σουδάν',
'NL':'Ολλανδία',
'OM':'Ομάν',
'HN':'Ονδούρα',
'WF':'Ουαλίς και Φουτουνά',
'HU':'Ουγγαρία',
'UG':'Ουγκάντα',
'UZ':'Ουζμπεκιστάν',
'UA':'Ουκρανία',
'UY':'Ουρουγουάη',
'PK':'Πακιστάν',
'PS':'Παλαιστίνη, Κράτος της',
'PW':'Παλάου',
'PA':'Παναμάς',
'PG':'Παπούα Νέα Γουινέα',
'PY':'Παραγουάη',
'PE':'Περού',
'PL':'Πολωνία',
'PT':'Πορτογαλία',
'PR':'Πουέρτο Ρίκο',
'CV':'Πράσινο Ακρωτήριο',
'MK':'Πρώην Γιουγκοσλαβική Δημοκρατία της Μακεδονίας',
'RE':'Ρεϋνιόν',
'RW':'Ρουάντα',
'RO':'Ρουμανία',
'RU':'Ρωσία',
'PM':'Σαιν Πιερ και Μικελόν',
'WS':'Σαμόα',
'ST':'Σάο Τομέ και Πρίνσιπε',
'SA':'Σαουδική Αραβία',
'SN':'Σενεγάλη',
'RS':'Σερβία',
'SC':'Σεϋχέλλες',
'SG':'Σιγκαπούρη',
'SL':'Σιέρα Λεόνε',
'SK':'Σλοβακία',
'SI':'Σλοβενία',
'SO':'Σομαλία',
'SZ':'Σουαζιλάνδη',
'SD':'Σουδάν',
'SE':'Σουηδία',
'SR':'Σουρινάμ',
'LK':'Σρι Λάνκα',
'SY':'Συρία',
'TW':'Ταϊβάν (Δημοκρατία της Κίνας)',
'TH':'Ταϊλάνδη',
'TZ':'Τανζανία',
'TJ':'Τατζικιστάν',
'TC':'Τερκς και Κέικος',
'JM':'Τζαμάικα',
'JE':'Τζέρσεϊ',
'DJ':'Τζιμπουτί',
'TG':'Τόγκο',
'TK':'Τοκελάου',
'TO':'Τόνγκα',
'TV':'Τουβαλού',
'TR':'Τουρκία',
'TM':'Τουρκμενιστάν',
'TT':'Τρινιντάντ και Τομπάγκο',
'TD':'Τσαντ',
'CZ':'Τσεχία',
'TN':'Τυνησία',
'YE':'Υεμένη',
'PH':'Φιλιππίνες',
'FI':'Φινλανδία',
'FJ':'Φίτζι',
'CL':'Χιλή',
'HK':'Χονγκ Κονγκ',
'GG':'Guernsey',
'SH':'Saint Helena, Ascension and Tristan da Cunha',
'SJ':'Svalbard and Jan Mayen',
};

var nationality_map = {
'undefined':'Μη προσδιορισμένη',
'GRC':'Έλληνας / Ελληνίδα',
'ENG':'Άγγλος / Αγγλίδα',
'EGY':'Αιγύπτιος / Αιγύπτια',
'ETH':'Αιθίοπας ',
'HTI':'Αϊτινός',
'ALB':'Αλβανός / Αλβανίδα',
'DZA':'Αλγερινός / Αλγερινή',
'USA':'Αμερικάνος / Αμερικανή',
'AND':'Ανδορρανός / Ανδορρανή ',
'ARG':'Αργεντίνος / Αργεντίνη',
'ARM':'Αρμένης / Αρμένισσα',
'AUS':'Αυστραλός /  Αυστραλή',
'AUT':'Αυστριακός / Αυστριακή',
'AFG':'Αφγανός / Αφγανή',
'BEL':'Βέλγος / Βελγίδα',
'VEN':'Βενεζουελανός / Βενεζουελανή ',
'VNM':'Βιετναμέζος / Βιετναμέζα',
'MMR':'Βιρμανός / Βιρμανή',
'BOL':'Βολιβιανός / Βολιβιανή',
'NIR':'Βορειοιρλανδός / Βορειοϊρλανδή',
'PRK':'Βορειοκορεάτης / Βορειοκορεάτισσα',
'BIH':'Βόσνιος / Βόσνια',
'BGR':'Βούλγαρος / Βουλγάρα',
'BRA':'Βραζιλιάνος / Βραζιλιάνα',
'GBR':'Βρετανός / Βρετανίδα',
'FRA':'Γάλλος / Γαλλίδα',
'DEU':'Γερμανός / Γερμανίδα',
'GEO':'Γεωργιανός / Γεωργιανή',
'GAB':'Γκαμπονέζος / Γκαμπονέζα',
'GHA':'Γκανέζος / Γκανέζα',
'DNK':'Δανός / Δανέζα',
'DOM':'Δομινικανός / Δομινικανή',
'ECU':'Εκουαδοριανός / Εκουαδοριανή',
'CHE':'Ελβετός / Ελβετίδα',
'EST':'Εσθονός / Εσθονή',
'ZWE':'Ζιμπαμπουανός',
'JPN':'Γιαπωνέζος / Γιαπωνέζα',
'CIV':'Ιβοριανός / Ιβοριανή',
'IDN':'Ινδονήσιος / Ινδονήσια',
'IND':'Ινδός / Ινδή',
'JOR':'Ιορδανός / Ιορδανή',
'IRQ':'Ιρακινός / Ιρακινή',
'IRN':'Ιρανός / Ιρανή',
'IRL':'Ιρλανδός / Ιρλανδή',
'ISL':'Ισλανδός / Ισλανδή',
'ESP':'Ισπανός / Ισπανίδα',
'ISR':'Ισραηλινός / Ισραηλινή',
'ITA':'Ιταλός / Ιταλίδα',
'KAZ':'Καζακστανός / Καζακστανή',
'CMR':'Καμερουνέζος / Καμερουνέζα',
'KHM':'Καμποτζιανός / Καμποτζιανή',
'CAN':'Καναδός / Καναδή',
'QAT':'Καταρινός',
'CAF':'Κεντροαφρικανός / Κεντροαφρικανή',
'KEN':'Κενυάτης / Κενυάτισσα',
'CHN':'Κινέζος / Κινέζα',
'COG':'Κογκολέζος / Κογκολέζα',
'COL':'Κολομβιανός / Κολομβιανή',
'CRI':'Κοσταρικανός / Κοσταρικανή',
'CUB':'Κουβανός / Κουβανή',
'HRV':'Κροάτης / Κροάτισσα',
'CYP':'Κύπριος / Κύπρια',
'LVA':'Λετονός / Λετονή',
'BLR':'Λευκορώσος / Λευκορωσίδα',
'LBN':'Λιβανέζος / Λιβανέζα',
'LBR':'Λιβεριανός / Λιβεριανή',
'LBY':'Λίβυος / Λίβυα',
'LUX':'Λουξεμβούργιος / Λουξεμβούργια',
'MYS':'Μαλαισιανός / Μαλαισιανή',
'MLT':'Μαλτέζος / Μαλτέζα',
'MAR':'Μαροκινός / Μαροκινή',
'MRT':'Μαυριτανός / Μαυριτανή',
'MNE':'Μαυροβούνιος / Μαυροβούνια',
'MEX':'Μεξικάνος / Μεξικανή',
'MNG':'Μογγόλος / Μογγόλα',
'MDA':'Μολδαβός / Μολδαβή',
'BGD':'Μπαγκλαντεσιανός / Μπαγκλαντεσιανή',
'NZL':'Νεοζηλανδός / Νεοζηλανδή ',
'NGA':'Νιγηριανός / Νιγηριανή',
'NIC':'Νικαραγουανός / Νικαραγουανή',
'NOR':'Νορβηγός / Νορβηγίδα',
'ZAF':'Νοτιοαφρικανός / Νοτιοαφρικανή',
'KOR':'Νοτιοκορεάτης / Νοτιοκορεάτισσα',
'NLD':'Ολλανδός / Ολλανδή',
'WLS':'Ουαλός / Ουαλή',
'HUN':'Ούγγρος / Ουγγαρέζα',
'UZB':'Ουζμπέκος',
'UKR':'Ουκρανός /Ουκρανή',
'URY':'Ουρουγουανός / Ουρουγουανή',
'PAK':'Πακιστανός / Πακιστανή',
'PSE':'Παλαιστίνιος / Παλαιστίνια',
'PAN':'Παναμέζος / Παναμέζα',
'PRY':'Παραγουανός / Παραγουανή',
'PER':'Περουβιανός / Περουβιανή',
'POL':'Πολωνός / Πολωνή',
'PRT':'Πορτογάλος / Πορτογαλίδα',
'ROU':'Ρουμάνος / Ρουμάνα',
'RUS':'Ρώσος / Ρωσίδα',
'SLV':'Σαλβαδοριανός / Σαλβαδοριανή',
'SEN':'Σενεγαλέζος / Σενεγαλέζα',
'SRB':'Σέρβος / Σέρβα',
'SGP':'Σιγκαπουριανός / Σιγκαπουριανή',
'SCT':'Σκωτσέζος / Σκωτσέζα',
'MKD':'Σλαβομακεδόνας / Σλαβομακεδόνισσα',
'SVK':'Σλοβάκος / Σλοβάκα',
'SVN':'Σλοβένος / Σλοβένα',
'SOM':'Σομαλός / Σομαλή',
'SDN':'Σουδανός / Σουδανή',
'SWE':'Σουηδός / Σουηδέζα',
'SYR':'Σύριος / Σύρια',
'TWN':'Ταϊβανός / Ταϊβανή',
'THA':'Ταϊλανδός / Ταϊλανδή',
'TZA':'Τανζανός / Τανζανή',
'JAM':'Τζαμαϊκανός / Τζαμαϊκανή',
'TUR':'Τούρκος / Τουρκάλα',
'CZE':'Τσέχος / Τσέχα',
'TUN':'Τυνήσιος / Τυνήσια',
'PHL':'Φιλιππινέζος / Φιλιππινέζα',
'FIN':'Φινλανδός / Φινλανδή',
'CHL':'Χιλιανός / Χιλιανή',
'PRI':'Afro-Puerto Rican',
'AGO':'Angolan',
'ATG':'Antiguans, Barbudans',
'AZE':'Azerbaijani',
'BHS':'Bahamian',
'BHR':'Bahraini',
'BRB':'Barbadian or Bajuns',
'BLZ':'Belizean',
'BEN':'Beninese',
'BTN':'Bhutanese',
'BRN':'Bruneian',
'BFA':'Burkinabe',
'BDI':'Burundian',
'CPV':'Cape Verdian or Cape Verdean',
'TCD':'Chadian',
'COM':'Comoran',
'DJI':'Djibouti',
'ARE':'Emirian',
'GNQ':'Equatoguinean',
'ERI':'Eritrean',
'FJI':'Fijian',
'GMB':'Gambian',
'GRD':'Grenadian',
'GTM':'Guatemalan',
'GNB':'Guinea-Bissauan',
'GIN':'Guinean',
'GUY':'Guyanese',
'HND':'Honduran',
'KIR':'I-Kiribati',
'KNA':'Kittian and Nevisian',
'KWT':'Kuwaiti',
'KGZ':'Kyrgyz or Kirghiz',
'LAO':'Lao or Laotian',
'LIE':'Liechtensteiner',
'LTU':'Lithuanian',
'MDG':'Malagasy',
'MWI':'Malawian',
'MDV':'Maldivan',
'MLI':'Malian',
'MHL':'Marshallese',
'MUS':'Mauritian',
'FSM':'Micronesian',
'MCO':'Monacan',
'LSO':'Mosotho ',
'BWA':'Motswana, Batswana',
'MOZ':'Mozambican',
'NAM':'Namibian',
'NRU':'Nauruan',
'NPL':'Nepalese',
'NER':'Nigerien',
'OMN':'Omani',
'PLW':'Palauan',
'PNG':'Papua New Guinean',
'RWA':'Rwandan',
'LCA':'Saint Lucian',
'WSM':'Samoan',
'SMR':'San Marinese',
'STP':'Sao Tomean',
'SAU':'Saudi Arabian',
'SYC':'Seychellois',
'SLE':'Sierra Leonean',
'SLB':'Solomon Islander',
'LKA':'Sri Lankan',
'SUR':'Surinamer',
'SWZ':'Swazi',
'TJK':'Tajik or Tadzhik',
'TGO':'Togolese',
'TON':'Tongan',
'TTO':'Trinidadian or Tobagonian',
'TUV':'Tuvaluan',
'TKM':'Turkmen',
'UGA':'Ugandan',
'YEM':'Yemeni or Yemenite',
'ZMB':'Zambian',
};


//****Deprecated Maps*****//
//var county_nationality_map = {
//'undefined':'Μη προσδιορισμένη',
//'gr':'Greece',
//'aa':'Albania',
//'ae':'Algeria',
//'af':'Afghanistan',
//'ag':'Argentina',
//'au':'Australia',
//'at':'Austria',
//'be':'Belgium',
//'bl':'Brazil',
//'bn':'Bosnia and Hercegovina',
//'bo':'Bolivia',
//'bu':'Bulgaria',
//'bw':'Belarus',
//'cc':'China',
//'ci':'Croatia',
//'cl':'Chile',
//'cn':'Canada',
//'cu':'Cuba',
//'cy':'Cyprus',
//'dk':'Denmark',
//'er':'Estonia',
//'fi':'Finland',
//'fr':'France',
//'gs':'Georgia (Republic)',
//'gw':'Germany',
//'hu':'Hungary',
//'ic':'Iceland',
//'ie':'Ireland',
//'ii':'India',
//'iq':'Iraq',
//'ir':'Iran',
//'is':'Israel',
//'it':'Italy',
//'ja':'Japan',
//'jm':'Jamaica',
//'jo':'Jordan',
//'ke':'Kenya',
//'kn':'Korea (North)',
//'ko':'Korea (South)',
//'kz':'Kazakhstan',
//'le':'Lebanon',
//'lh':'Liechtenstein',
//'li':'Lithuania',
//'lu':'Luxembourg',
//'lv':'Latvia',
//'mc':'Monaco',
//'mm':'Malta',
//'mo':'Montenegro',
//'mr':'Morocco',
//'mv':'Moldova',
//'mx':'Mexico',
//'ne':'Netherlands',
//'no':'Norway',
//'np':'Nepal',
//'nq':'Nicaragua',
//'nr':'Nigeria',
//'nz':'New Zealand',
//'pe':'Peru',
//'pk':'Pakistan',
//'pl':'Poland',
//'pn':'Panama',
//'po':'Portugal',
//'py':'Paraguay',
//'qa':'Qatar',
//'rb':'Serbia',
//'rm':'Romania',
//'ru':'Russia (Federation)',
//'sa':'South Africa',
//'si':'Singapore',
//'sp':'Spain',
//'su':'Saudi Arabia',
//'sw':'Sweden',
//'sy':'Syria',
//'sz':'Switzerland',
//'th':'Thailand',
//'ti':'Tunisia',
//'tk':'Turkmenistan',
//'ts':'United Arab Emirates',
//'tu':'Turkey',
//'ua':'Egypt',
//'un':'Ukraine',
//'uy':'Uruguay',
//'uz':'Uzbekistan',
//'vc':'Vatican City',
//'ve':'Venezuela',
//'vm':'Vietnam',
//'vp':'Various places',
//'xn':'Macedonia',
//'xo':'Slovakia',
//'xr':'Czech Republic',
//'xv':'Slovenia',
//'xx':'No place, unknown, or undetermined',
//'xxc':'Canada',
//'xxk':'United Kingdom',
//'xxu':'United States',
//};

