var f_auth_work = [
//	'header_control_open',
//	'control_number',
//	'latest_transaction',
//	'persistent',
//	'entity_type',//?????
//	'lang',
	'header_public_work',
	'header_work_control_open',
	'entity_type',
	'work_type',
	'control_number',
//'latest_transaction',
//'persistent',
//	'header_sect_work',
	'header_sect_work_basic',
	'hidden_obj_type_work',
	'work_title_preferred',
	'work_title_partNumber',
	'work_title_partName',
	'work_form',
	'work_date',
	'work_place',

	'work_language',
	'work_version',
//	'header_sect_work_contributors',
//	'work_contributors_all',
	'contributors_w',
//	'header_sect_work_subjects',
//	'manif_subject',
	'subject_all',
//	'header_sect_work_manifestations',
//	'manifestations_all',
//	'manif_keywords',
	//'manifestation-relation-workOf',
	'header_sect_work_additional',
	'work_chronological',
	'work_geographical',
	'work_subject_category',
	'header_sect_work_information',
	'nonpublic_general_note',
	'public_general_note',
	'biographical_work_data',
	'electronic_location',
	'header_sect_work_link',
	'bibliography',
	'national_bibliography_number',
	'number_other',
	'isni_number',
	'viaf_number',
//	'work_notenonpublic',
//	'work_notepublic',
//	'work_biographical_data',
//	'work_url_rel',
	'header_sect_work_relation',
	'work_relation_descriptive',
	'work_relation_derivative',
	'work_relation_wholepart',
	'work_relation_accompanying',
	'work_relation_sequential',
//	'header_sect_expression',
//	'header_sect_expres_basic',
//	'expres_form',
//	'expres_content',
//	'expres_date',
//	'expres_language',
//	'expres_version',
//	'header_sect_expres_specific',
//	'expres_frequency',
//	'expres_note_music',
//	'expres_computer_character',
//	'expres_playing_time',
//	'expres_symbology',
//	'expres_computer_scale',
//	'header_sect_expres_information',
//	'expres_note_content',
//	'expres_note_summary',
//	'expres_note_citation',
//	'expres_url',
//	'header_sect_expres_contributors',
//	'contributors_w',
//	'header_sect_expres_subjects',
//	'manif_subject',
//	'manif_keywords',
//	'header_sect_relation_expression',
//	'expres_relation_descriptive',
//	'expres_relation_derivative',
//	'expres_relation_wholepart',
//	'expres_relation_accompanying',
//	'expres_relation_sequential',
////'expres_relation_work',
	'header_sect_work_thumb',
	'manif_description_thumb',
	'header_work_status',
	'status',
	'sect_reverse_relations_manifestation',
	'reverse_work',
	'sect_reverse_relations_expression',
	'reverse_expressionOf',
	'empty1',
	'header_work_expression_sect',
	'header_work_manifestation_sect',
	'hidden_label',
	//'validate_subjects',
	];


var  f_auth_work_extend = [
	'header_work_public_extented',
	'header_work_control_open_extented',
	'work_type_extented',
	'header_sect_work_basic_extend',
	'hidden_obj_type_work',
	 '__PRIMARY__',
	'work_title_partNumber',
	'work_title_partName',
	'work_form',
	'work_date',
	'work_place',
	'work_language',
	'work_version',
	'contributors_w',
	'subject_all',
	'header_sect_work_additional_extend',
	'work_chronological',
	'work_geographical',
	'work_subject_category',
	'header_sect_work_information_extend',
	'nonpublic_general_note',
	'public_general_note',
	'biographical_work_data',
	'electronic_location',
	'header_sect_work_link_extend',
	'bibliography',
	'national_bibliography_number',
	'number_other',
	'isni_number',
	'viaf_number',
	'header_work_status_extented',
	'status_finish',
	'hidden_obj_type_work',
	'hidden_label',
//	'empty1',
//	'header_work_expression_sect_extented',
//	'header_work_manifestation_sect_extented',
];


var f_auth_work_extend_subj = [
'header_work_public_extented',
'header_work_control_open_extented',
'work_type_extented',
'header_sect_work_basic_extend',
'hidden_obj_type_work',
'work_title_preferred',
'work_title_partNumber',
'work_title_partName',
'work_form',
'work_date',
'work_place',
'work_language',
'work_version',
'contributors_w',
'subject_all',
'header_sect_work_additional_extend',
'work_chronological',
'work_geographical',
'work_subject_category',
'header_sect_work_information_extend',
'nonpublic_general_note',
'public_general_note',
'biographical_work_data',
'electronic_location',
'header_sect_work_link_extend',
'bibliography',
'national_bibliography_number',
'number_other',
'isni_number',
'viaf_number',
'header_work_status_extented',
'status_finish',
'hidden_obj_type_work',
'hidden_label',
//'empty1',
//'header_work_expression_sect_extented',
//'header_work_manifestation_sect_extented',
	];
