var f_auth_family = [
'header_family_public',
'header_family_control',
//'latest_transaction',
//'persistent',
'entity_type',
'kind_record',
'control_number',
'authority_level_establish',
'header_sect_family_basic',
'entity_language',
//'personal_type',
'family_name_simple',
'family_type',
'family_titles_place',
'family_dates_associated',
'header_sect_family_additional',
//'country_name',
//'family_information',
'family_other_place',
'family_participation_in_events',
//'family_associated_language',
'nationality',
'date_start_period',
'date_end_period',
'header_sect_family_information',
'nonpublic_general_note',
'public_general_note',
'biographical_data',
'electronic_location',
'header_sect_family_link',
'lccn_number',
'national_bibliography_number',
'number_other',
'isni_number',
'viaf_number',
'header_sect_family_cataloging',
//'lc_classification',
'lc_classification_simple',
//'ddc_number',
'ddc_number_simple',
//'other_classification',
'other_classification_simple',
'cataloging_source_original',
'header_sect_family_subjects',
//'subject_title',
//'auth_subject',
'subject_all',
//'auth_keywords',
'header_sect_family_relations',
'relation_family_see_also',
'relation_see_alter',
'relation_family_see_also_family',
'relation_family_see_also_organization',
'relation_family_see_also_person',
'relation_family_other_language',
'header_family_status',
'status',
'hidden_label',
];


var f_auth_family_extend = [
'header_family_public_extented',
'header_family_control_extented',
'kind_record_extented',
'authority_level_establish',
'header_sect_family_basic_extented',
'entity_language',
'__PRIMARY__',
'family_type',
'family_titles_place',
'family_dates_associated',
'header_sect_family_additional_extented',
//'country_name',
//'family_information',
'family_other_place',
'family_participation_in_events',
//'family_associated_language',
'other_place',
'associated_language',
'nationality',
'date_start_period',
'date_end_period',
'header_sect_family_information_extented',
'nonpublic_general_note',
'public_general_note',
'biographical_data',
'electronic_location',
'header_sect_family_link_extented',
'lccn_number',
'national_bibliography_number',
'number_other',
'isni_number',
'viaf_number',
'header_sect_family_cataloging_extented',
'lc_classification_simple',
'ddc_number_simple',
'other_classification_simple',
'cataloging_source_original',
'header_sect_family_subjects_extented',
'subject_all',
'header_family_status_extented',
'status_finish',
"hidden_obj_type_family",
'hidden_label',
];  


var f_auth_family_extend_subj = [
'header_family_public_extented',
'header_family_control_extented',
'kind_record_extented',
'authority_level_establish',
'header_sect_family_basic_extented',
'entity_language',
'family_name_simple',
'family_type',
'family_titles_place',
'family_dates_associated',
'header_sect_family_additional_extented',
//'country_name',
//'family_information',
'family_other_place',
'family_participation_in_events',
//'family_associated_language',
'other_place',
'associated_language',
'nationality',
'date_start_period',
'date_end_period',
'header_sect_family_information_extented',
'nonpublic_general_note',
'public_general_note',
'biographical_data',
'electronic_location',
'header_sect_family_link_extented',
'lccn_number',
'national_bibliography_number',
'number_other',
'isni_number',
'viaf_number',
'header_sect_family_cataloging_extented',
'lc_classification_simple',
'ddc_number_simple',
'other_classification_simple',
'cataloging_source_original',
'header_sect_family_subjects_extented',
'subject_all',
'header_family_status_extented',
'status_finish',
"hidden_obj_type_family",
'controled_subject_false',
'hidden_label',
];









