var f_auth_concept = [
'header_concept_public',
'header_concept_control_open',
//'latest_transaction',
//'persistent',
'entity_type',
'kind_record',
'control_number',
'authority_level_establish',
//'lang',
'header_sect_concept_basic',
'entity_language',
'concept_term',
'header_sect_concept_additional',
'concept_type',
'concept_start_date',
'concept_expiry_date',
'concept_place',
'contributors_concept',
'header_sect_concept_information',
'nonpublic_general_note',
'public_general_note',
'biographical_work_data',
'electronic_location',
'header_sect_concept_link',
'lccn_number',
'national_bibliography_number',
'number_other',
'isni_number',
'viaf_number',
'header_sect_concept_cataloging',
//'lc_classification',
//'ddc_number',
//'other_classification',
//'cataloging_source_original',
'lc_classification_simple',
'ddc_number_simple',
'other_classification_simple',
'cataloging_source_original',
//'auth_keywords',
'header_sect_concept_relations',
'relation_concept_see_alter',
'relation_concept_see_also',
'relation_other_entity_see_also',
'relation_concept_other_language',
'header_concept_status',
'status_finish',
'controled_subject_true',
'hidden_label',
];


var f_auth_concept_extend = [
'header_concept_public_extented',
'header_concept_control_open_extented',
'kind_record_extented',
'authority_level_establish',
'header_sect_concept_basic_extented',
'entity_language',
'__PRIMARY__',
'header_sect_concept_additional_extented',
'concept_type',
'concept_start_date',
'concept_expiry_date',
'concept_place',
'contributors_concept',
'header_sect_concept_information_extented',
'nonpublic_general_note',
'public_general_note',
'biographical_work_data',
'electronic_location',
'header_sect_concept_link_extented',
'lccn_number',
'national_bibliography_number',
'number_other',
'isni_number',
'viaf_number',
'header_sect_concept_cataloging_extented',
'lc_classification_simple',
'ddc_number_simple',
'other_classification_simple',
'cataloging_source_original',
'header_concept_status_extented',
'status_finish',
'hidden_obj_type_concept',
'hidden_label',
];


var f_auth_concept_extend_subj = [
'header_concept_public_extented',
'header_concept_control_open_extented',
'kind_record_extented',
'authority_level_establish',
'header_sect_concept_basic_extented',
'entity_language',
'concept_term',
'header_sect_concept_additional_extented',
'concept_type',
'concept_start_date',
'concept_expiry_date',
'concept_place',
'contributors_concept',
'header_sect_concept_information_extented',
'nonpublic_general_note',
'public_general_note',
'biographical_work_data',
'electronic_location',
'header_sect_concept_link_extented',
'lccn_number',
'national_bibliography_number',
'number_other',
'isni_number',
'viaf_number',
'header_sect_concept_cataloging_extented',
'lc_classification_simple',
'ddc_number_simple',
'other_classification_simple',
'cataloging_source_original',
'header_concept_status_extented',
'status_finish',
'hidden_obj_type_concept',
'controled_subject_false',
'hidden_label',
];


//f_auth_concept_extend= [
//'header_public',
//'header_sect_concept_basic',
//'concept_term',
//'header_sect_concept_information',
//'nonpublic_general_note',
//'public_general_note',
//'biographical_data',
//'electronic_location',
//'status_finish',
//'hidden_obj_type_concept',
//'controled_subject_false',
//];

//var concept_relation_extend_commands = [
//'header_concept_control_open',
//'kind_record_extend',
//'authority_level_establish_extend',                                                                           
//'extend_header_public',
//'header_sect_concept_basic',
//'entity_language',
//'__PRIMARY__',
//'header_status',
//'status_finish',
//];  
//
//var concept_relation_extend_commands_see_also = [
//'header_concept_control_open',
//'kind_record',
//'authority_level_establish_extend',                                                                          
//'extend_header_public',
//'header_sect_concept_basic',
//'entity_language',
//'__PRIMARY__',
//'header_status',
//'status_finish',
//]; 





