var f_auth_genre = [
'header_genre_public',
'header_genre_control_open',
//'latest_transaction',
//'persistent',
'entity_type',
'kind_record',
'control_number',
'authority_level_establish',
//'lang',
'header_sect_genre_basic',
'entity_language',
'genre_term',
//'subject_title',
'header_sect_genre_additional',
'genre_type',
'genre_start_date',
'genre_expiry_date',
'genre_place',
'contributors_genre',
'header_sect_genre_information',
'nonpublic_general_note',
'public_general_note',
'biographical_work_data',
'electronic_location',
'header_sect_genre_link',
'lccn_number',
'national_bibliography_number',
'number_other',
'isni_number',
'viaf_number',
'header_sect_genre_cataloging',
//'lc_classification',
//'ddc_number',
//'other_classification',
//'cataloging_source_original',
'lc_classification_simple',
'ddc_number_simple',
'other_classification_simple',
'cataloging_source_original',
//'auth_keywords',
'header_sect_genre_relations',
'relation_genre_see_alter',
'relation_genre_see_also',
'relation_other_entity_see_also',
'relation_genre_other_language',
'header_genre_status',
'status_finish',
'controled_subject_true',
'hidden_label',
];


var f_auth_genre_extend = [
'header_genre_public_extented',
'header_genre_control_open_extented',
'kind_record_extented',
'authority_level_establish',
'header_sect_genre_basic_extented',
'entity_language',
'__PRIMARY__',
'header_sect_genre_additional_extented',
'genre_type',
'genre_start_date',
'genre_expiry_date',
'genre_place',
'contributors_genre',
'header_sect_genre_information_extented',
'nonpublic_general_note',
'public_general_note',
'biographical_work_data',
'electronic_location',
'header_sect_genre_link_extented',
'lccn_number',
'national_bibliography_number',
'number_other',
'isni_number',
'viaf_number',
'header_sect_genre_cataloging_extented',
'lc_classification_simple',
'ddc_number_simple',
'other_classification_simple',
'cataloging_source_original',
'header_genre_status_extented',
'status_finish',
'hidden_obj_type_genre',
'controled_subject_true',
'hidden_label',
];


var f_auth_genre_extend_subj = [
'header_genre_public_extented',
'header_genre_control_open_extented',
'kind_record_extented',
'authority_level_establish',
'header_sect_genre_basic_extented',
'entity_language',
'genre_term',
'header_sect_genre_additional_extented',
'genre_type',
'genre_start_date',
'genre_expiry_date',
'genre_place',
'contributors_genre',
'header_sect_genre_information_extented',
'nonpublic_general_note',
'public_general_note',
'biographical_work_data',
'electronic_location',
'header_sect_genre_link_extented',
'lccn_number',
'national_bibliography_number',
'number_other',
'isni_number',
'viaf_number',
'header_sect_genre_cataloging_extented',
'lc_classification_simple',
'ddc_number_simple',
'other_classification_simple',
'cataloging_source_original',
'header_genre_status_extented',
'status_finish',
'hidden_obj_type_genre',
'controled_subject_true',
'hidden_label',
];



//var genre_relation_extend_commands = [
//'header_control_open',
//'kind_record_extend',
//'authority_level_establish_extend',
//'extend_header_public',
////'header_sect_basic',
//'entity_language',
//'__PRIMARY__',
//'header_status',
//'status_finish',
//];  

//var genre_relation_extend_commands_see_also = [
//'header_control_open',
//'kind_record',
//'authority_level_establish_extend',
//'extend_header_public',
////'header_sect_basic',
//'entity_language',
//'__PRIMARY__',
//'header_status',
//'status_finish',
//];



//var f_auth_genre_extend = [
//'extend_header_public',
//'header_sect_genre_basic',
//'genre_term',
//'header_sect_genre_information',
//'nonpublic_general_note',
//'public_general_note',
//'biographical_data',
//'electronic_location',
//'status_finish',
//'hidden_obj_type_genre',
//'controled_subject_false',
//];