var f_auth_obj_collection = [
'header_control',
//'control_number',
//'latest_transaction',
//'persistent',
'entity_type',
'kind_record',
'authority_level_establish',
'lang',
'header_public',
'header_sect_obj_collection_basic',
'entity_language',
'obj_collection_term',
'subject_title',
'header_sect_obj_collection_information',
'nonpublic_general_note',
'public_general_note',
'biographical_data',
'electronic_location',
'header_sect_obj_collection_link',
'lccn_number',
'national_bibliography_number',
'number_other',
'isni_number',
'viaf_number',
'header_sect_obj_collection_cataloging',
'lc_classification',
'ddc_number',
'other_classification',
'cataloging_source_original',
'auth_keywords',
'header_sect_obj_collection_relations',
'relation_concept_see_alter',
'relation_concept_see_also',
'relation_concept_see_also_concept',
'relation_concept_other_language',
'header_status',
'status_finish',
'controled_subject_true',
'hidden_label',
];


f_auth_obj_collection_extend= [
'header_public',
'header_sect_obj_collection_basic',
'obj_collection_term',
'header_sect_obj_collection_information',
'nonpublic_general_note',
'public_general_note',
'biographical_data',
'electronic_location',
'status_finish',
'hidden_obj_type_object_collection',
'controled_subject_false',
'hidden_label',
];



