var f_auth_manifestation = [
'header_manifestation_public',
	'header_manif_control_open',
//	'latest_transaction',
//	'persistent',
	'entity_type',
	'manif_type',
	'control_number',
//	'lang',
	'header_sect_manifestation_title',
//	'manif_publication_name',
	//'manif_title',
	'title_manif_proper',
	'title_manif_medium',
	'title_manif_remainder',
	'title_manif_responsibility',
	'title_manif_partnumber',
	'title_manif_partName',
//	'header_manif_imprint_with_add',
//	'header_manif_edition',
	'header_sect_manifestation_basic',
	'manif_edition',
	'manif_publications',
	'manif_physical_description',
	'manif_series',
	'manif_isbn',
	'header_sect_manifestation_additional',
	'manif_additional_title',
	'manif_media_type',
	'manif_carrier_type',
	'manif_note',
	'manif_serials_numbering',
	'manif_country_code',
//	'manif_url_rel',
	'header_sect_manifestation_information',
	'manif_availability_library',
	'expres_note_content',
	'expres_note_summary',
	'expres_note_citation',
	'expres_url',
	'header_sect_manifestation_cataloging',
	'lc_classification_simple',
	'ddc_number_simple',
	'other_classification_simple',
	'cataloging_source_original',
	'header_sect_manifestation_work_expression',
	'works2_all',
	'header_sect_digital_item',
	'manif_digital_item',
//	'works2_work',
//	'works2_expression',
//	'header_sect_manifestation_expression',
//	'expres_language',
//	'contributors_e',
////	'manif_work_expression',
		'header_sect_manifestation_contributors',
////	'contributors_all',
	'contributors_m',
	'header_sect_manifestation_subjects',
	'subject_all',
	'subject_js',
//	'manif_keywords',
	'header_sect_manifestation_relations',
//	'relations_folder',
	'manif_relation_equivalent',
	'manif_relation_descriptive',
	'manif_relation_wholepart',
	'manif_relation_accompanying',
//	'header_sect_manifestation_thumb',
//	'manif_description_thumb',
	'header_manifestation_status',
	'status_finish',
	'hidden_label',
//	'manif_relation_expression_with_work',
//	'manif_relation_expression_other_work',
//	'manif_relation_manifestation_other_manifestation',
//	'manif_relation_whole_part',
//	'manif_relation_contributors_expression',
//	'manif_relation_contributors_manifestation',
//	'manif_relation_subject_manifestation',
//	'manif_relation_subject_expression',
	];


var f_auth_manifestations_extend = [
'header_manifestation_public_extented',
'header_sect_manifestation_title',
'__PRIMARY__',
'title_manif_medium',
'title_manif_remainder',
'title_manif_responsibility',
'title_manif_partnumber',
'title_manif_partName',
'header_sect_manifestation_basic_extented',
'manif_edition',
'manif_publications',
'manif_physical_description',
'manif_series',
'manif_isbn',
'header_sect_manifestation_additional_extented',
'manif_additional_title',
'manif_media_type',
'manif_carrier_type',
'manif_note',
'manif_serials_numbering',
'manif_country_code',
'header_sect_manifestation_information_extented',
'manif_availability_library',
'expres_note_content',
'expres_note_summary',
'expres_note_citation',
'expres_url',
'header_sect_manifestation_cataloging_extented',
'lc_classification_simple',
'ddc_number_simple',
'other_classification_simple',
'cataloging_source_original',
'header_sect_manifestation_work_expression_extented',
'works2_all',
'header_sect_manifestation_contributors_extented',
'contributors_m',
//'header_sect_manifestation_subjects_extented',
//'subject_all',
//'subject_js',
'header_manifestation_status_extented',
'status_finish',
'hidden_label',
];


var f_auth_manifestation_work = [
'header_manif_control_open',
'manif_type',
'header_sect_manifestation_title_w',
'manifestation_work_extend_primary',
'title_manif_medium',
'title_manif_remainder',
'title_manif_responsibility',
'title_manif_partnumber',
'title_manif_partName',
'header_sect_manifestation_basic',
'manif_edition',
'manif_publications',
'manif_physical_description',
'manif_series',
'manif_isbn',
'header_sect_manifestation_additional',
'manif_additional_title',
'manif_media_type',
'manif_carrier_type',
'manif_note',
'manif_serials_numbering',
'manif_country_code',
'manif_url_rel',
'header_sect_manifestation_information_extented',
'manif_availability_library',
'expres_note_content',
'expres_note_summary',
'expres_note_citation',
'expres_url',
'header_sect_manifestation_cataloging_extented',
'lc_classification_simple',
'ddc_number_simple',
'other_classification_simple',
'cataloging_source_original',
'header_sect_manifestation_contributors_w',
'contributors_m',
//'header_sect_manifestation_subjects',
//'subject_all',
//'subject_js',
//'header_sect_manifestation_expression',
//'expres_language',
//'contributors_e',
//'status_finish',
'hidden_status_finish',
'manifestation_work_extend_ot',
'hidden_label',
];



