var f_auth_work = [
	'header_control_open',
	'work_type',
	'header_public_work',
	'contributors_w',
	'work_title_preferred',
	'work_variant_title',
	'other_agents_associated',
//	'work_form',
	'work_date',
	'work_place',
	'work_version',
	'work_nature_content',
	'subject_all',
	'header_work_expression_sect',
	'header_work_manifestation_sect',
	'hidden_label',
	];


var f_auth_work_audioCd = [
	'header_control_open',
	'work_type',
	'header_public_work_audioCd',
	'contributors_w',
	'work_title_preferred',
	'work_variant_title_audioCd',
	'other_agents_associated',
//	'work_form',
	'work_date',
	'work_place',
	'work_version',
	'work_nature_content',
	'subject_all',
	'header_work_expression_sect_audioCd',
	'header_work_manifestation_sect',
	'hidden_label',
 	];


var f_auth_work_featureFilm = [
	'header_control_open',
	'work_type',
	'header_public_work_featureFilm',
	'contributors_w',
	'work_title_preferred',
	'work_variant_title',
	'other_agents_associated',
//	'work_form',
	'work_date',
	'work_place',
	'work_version',
	'work_nature_content',
	'subject_all',
	'header_work_expression_sect_featureFilm',
	'header_work_manifestation_sect',
	'hidden_label',
 	];



var  f_auth_work_extend = [
	'header_work_public_extented',
	'header_work_control_open_extented',
	'work_type_extented',
	'header_sect_work_basic_extend',
	'hidden_obj_type_work',
	 '__PRIMARY__',
	'work_title_partNumber',
	'work_title_partName',
	'work_form',
	'work_date',
	'work_place',
	'work_language',
	'work_version',
	'contributors_w',
//	'subject_all',
	'header_sect_work_additional_extend',
	'work_chronological',
	'work_geographical',
	'work_subject_category',
	'header_sect_work_information_extend',
	'nonpublic_general_note',
	'public_general_note',
	'biographical_work_data',
	'electronic_location',
	'header_sect_work_link_extend',
	'bibliography',
	'national_bibliography_number',
	'number_other',
	'isni_number',
	'viaf_number',
	'header_work_status_extented',
	'status_finish',
	'hidden_obj_type_work',
	'hidden_label',
//	'empty1',
//	'header_work_expression_sect_extented',
//	'header_work_manifestation_sect_extented',
];


var f_auth_work_extend_subj = [
'header_work_public_extented',
'header_work_control_open_extented',
'work_type_extented',
'header_sect_work_basic_extend',
'hidden_obj_type_work',
'work_title_preferred',
'work_title_partNumber',
'work_title_partName',
'work_form',
'work_date',
'work_place',
'work_language',
'work_version',
'contributors_w',
//'subject_all',
'header_sect_work_additional_extend',
'work_chronological',
'work_geographical',
'work_subject_category',
'header_sect_work_information_extend',
'nonpublic_general_note',
'public_general_note',
'biographical_work_data',
'electronic_location',
'header_sect_work_link_extend',
'bibliography',
'national_bibliography_number',
'number_other',
'isni_number',
'viaf_number',
'header_work_status_extented',
'status_finish',
'hidden_obj_type_work',
'hidden_label',
//'empty1',
//'header_work_expression_sect_extented',
//'header_work_manifestation_sect_extented',
	];
