var f_auth_place = [
'header_place_public',
'header_place_control',
//'latest_transaction',
//'persistent',
'entity_type',
'kind_record',
'control_number',
'authority_level_establish',
//'lang',
'header_sect_place_basic',
'entity_language',
'place_term',
'place_type',
//'subject_title',
'header_sect_place_information',
'nonpublic_general_note',
'public_general_note',
'biographical_work_data',
'electronic_location',
'header_sect_place_link',
'lccn_number',
'national_bibliography_number',
'number_other',
'geonames',
'viaf_number',
'header_sect_place_cataloging',
'lc_classification_simple',
'ddc_number_simple',
'other_classification_simple',
'cataloging_source_original',
'header_sect_place_relations',
'relation_place_see_alter',
'relation_place_see_also',
'relation_place_other',
'relation_place_organization',
'relation_place_other_language',
'header_place_status',
'status_finish',
'controled_subject_true',
'hidden_label',
];


var f_auth_place_extend = [
'header_place_public_extented',
'header_place_control_extented',
'kind_record_extented',
'authority_level_establish',
'header_sect_place_basic_extented',
'entity_language',
'__PRIMARY__',
'place_type',
'header_sect_place_information_extented',
'nonpublic_general_note',
'public_general_note',
'biographical_work_data',
'electronic_location',
'header_sect_place_link_extented',
'lccn_number',
'national_bibliography_number',
'number_other',
'geonames',
'viaf_number',
'header_sect_place_cataloging_extented',
'lc_classification_simple',
'ddc_number_simple',
'other_classification_simple',
'cataloging_source_original',

'header_sect_place_relations',
'relation_place_see_alter',
'relation_place_see_also',
'relation_place_other',
'relation_place_organization',

'header_place_status_extented',
'status_finish',
'hidden_obj_type_place',
'hidden_label',
];


var f_auth_place_extend_subj = [
'header_place_public_extented',
'header_place_control_extented',
'kind_record_extented',
'authority_level_establish',
'header_sect_place_basic_extented',
'entity_language',
'place_term',
'place_type',
'header_sect_place_information_extented',
'nonpublic_general_note',
'public_general_note',
'biographical_work_data',
'electronic_location',
'header_sect_place_link_extented',
'lccn_number',
'national_bibliography_number',
'number_other',
'geonames',
'viaf_number',
'header_sect_place_cataloging_extented',
'lc_classification_simple',
'ddc_number_simple',
'other_classification_simple',
'cataloging_source_original',
'header_place_status_extented',
'status_finish',
'hidden_obj_type_place',
'controled_subject_false',
'hidden_label',
];




