var f_auth_expression = [
 	'header_expression_public',
	'header_expression_control_open',
//	'latest_transaction',
//	'persistent',
	'entity_type',
	'control_number',
//	'header_sect_expression',
	'header_sect_expres_basic',
	'express_title',
	'expres_content',
	'expres_language',
	'expres_version',
	'expres_form',
	'expres_date',
	'contributors_e',
	'subject_all',
	'header_sect_expres_specific',
	'expres_frequency',
	'expres_note_music',
	'expres_computer_character',
	'expres_playing_time',
	'expres_symbology',
	'expres_computer_scale',
	'header_sect_expres_information',
	'expres_note_content',
	'expres_note_summary',
	'expres_note_citation',
	'expres_url',
//	'header_sect_expres_contributors',
//	'contributors_e',
//	'header_sect_expres_subjects',
//	'subject_all',
	'header_sect_relation_expression',
	'expres_relation_descriptive',
	'expres_relation_derivative',
	'expres_relation_wholepart',
	'expres_relation_accompanying',
	'expres_relation_sequential',
//	'expres_relation_work',
	'header_sect_work_expression',
	'works_of_expression',
	'header_sect_expresion_manifs',
	'reverse_work',
	'header_expression_status',
	'status',
	'hidden_obj_type_expression',

	'header_work_manifestation_sect',
	'hidden_label',
	];


var  f_auth_expression_extend = [
'header_expression_public_extented',
'header_sect_expres_basic_extented',
'__PRIMARY__',
'expres_content',
'expres_language',
'expres_version',
'expres_form',
'expres_date',
'contributors_e',
//'subject_all',
'header_sect_expres_specific_extented',
'expres_frequency',
'expres_note_music',
'expres_computer_character',
'expres_playing_time',
'expres_symbology',
'expres_computer_scale',
'header_sect_expres_information_extented',
'expres_note_content',
'expres_note_summary',
'expres_note_citation',
'expres_url',
'header_sect_work_expression_extented',
'works_of_expression',
'header_expression_status_extented',
'status',
'hidden_obj_type_expression',
'hidden_label',
];


var f_auth_expression_work = [
'expression_work_extend_primary',
'expres_content',
'expres_date',
'expres_language',
'expres_note_content',
'contributors_e',
'hidden_status_finish',
'expression_work_extend_ot',
'hidden_label',
];


var f_auth_expression_work_audioCd  = [
'expression_work_extend_primary',
//'expres_content',
'expres_date',
//'expres_language',
//'expres_note_content',
'contributors_e',
'hidden_status_finish',
'expression_work_extend_ot',
'hidden_label',
];

var f_auth_expression_work_featureFilm = [
'expression_work_extend_primary',
//'expres_content',
//'expres_date',
//'expres_language',
//'expres_note_content',
//'contributors_e',
'hidden_status_finish',
'expression_work_extend_ot',
'hidden_label',
];



