
var key_labels = {
'public':'Δημόσια Πεδία',
'status':'Κατάσταση Εγγραφής',
'ea:Contributor':'Συντελεστές',
'dc:contributor':'Contributor',
'dc:contributor:advisor':'Advisor',
//'dc:contributor:author':'Author',
'dc:contributor:author':'Author',//'Συγγραφέας',
//'dc:contributor:editor':'Συντάκτης',
'dc:contributor:illustrator':'Illustrator',
'dc:contributor:other':'Contributor other',
'ea:relation:other':'Relation other',
'ea:contributor:editor':'Editor',// 'Επιμελητής',
'ea:contributor:responsible':'Responsible',//'Υπεύθυνος έκδοσης',
'ea:contributor:translator':'Translator',//'Μεταφραστής',
'dc:description:abstract':'abstract',
'dc:description:':'description',
'dc:identifier:isbn':'isbn',
'dc:identifier:issn':'issn',
'dc:language:iso':'Language',
'dc:publisher:':'publisher',
'dc:subject:': 'Θέματα',
'dc:title:':'name',
'dc:title:':'Τίτλος',
'ea:collection:name':'collection name',
'ea:collection:place':'collection place',
'ea:comment:':'Σχόλιο',
'comment':'Σχόλιο',
'ea:comment:internal':'Εσωτερικό σχόλιο',
'ea:contributor-type:':'type',
'ea:date:end':'Τελική περίοδος',
'ea:date:orgissued':'publication date',//'ημ/νια εκδοσης',
'ea:date:start':'Αρχική περίοδος',
'ea:issue:':'Issue',
'issue':'Issue',
'ea:marc:dates':'dates',
'ea:obj-type:':'type',
'ea:origin:comment':'Origin',
'ea:person:name-titles':'titles & other',
'ea:publication:place':'publication place',
'ea:size:pages':'Number of Pages',
'ea:status:comment':'status',
'ea:status:':'status',
'ea:subtitle:':'subtitle',
'ea:title:uniform':'title uniform  dfg fgfd gdf gdfg dfg df g dgfd ',
'ea:url:origin': 'URL πηγής',
'ea:url:related':'Σχετικό URL',
'ea:website:url-base':'site url-base',
'ea:website:url':'site url',
'ea:work:':'title',
'tmp:comment:':'Σχόλιο',
'tmp:description:':'Περιγραφή',
'ea:call_number:ddc':'DDC',
'ea:dimensions:extent':'extent',
'ea:dimensions:dimensions':'dimensions',
'ea:dimensions:other-psysical-datails':'other-psysical-datails',
'ea:country:name':'country',
'ea:country:iso':'country iso',
'ea:linkeddata:url':'linked data url',
'ea:date:insert':'insert date',
'ea:publication:printer-name':'printer',
'ea:publication:printing-place':'Printing Place',
'ea:issue-of:':'issue of',
'ea:relation:other':'relation-other',
'ea:item-of:':'item of',
'ea:dating:':'Χρονολόγηση',
'ea:inventory:id':'Αριθμός',
'ea:material:type':'Ύλη',
'ea:bookbinding:type':'Bιβλιοδεσία',
'ea:content:transcription':'Μεταγραφή',
'ea:manuscript:source':'Χειρόγραφο',
'ea:situation:':'Κατάσταση',
'ea:material:':'Yλικό',
'ea:process:':'Διαδικασία',
'ea:symbol:':'Σύμβoλο',
'ea:instrument:':'Όργανο',
'marc:contributor:scribe' : 'κωδικογράφος',
'marc:contributor:collector':'Συλλέκτης',
'marc:contributor:conservator':'Συντηρητής',
'marc:contributor:commentatorwt':'Σχολιαστής',
'marc:contributor:autographer':'Αutographer',
'marc:contributor:annotator':'Yπομνηματογράφος',
'marc:contributor:rubricator':'Rubricator',
'ea:owner:': 'Ιδιοκτήτης',
'ea:work:title':'title',
'status_field':'Κατάσταση',
'language':'Γλώσσα',

/*********** Auth_person **********/
'Person_fields':'Πεδία Person',
'Person_controls_fields':'Person - Πεδία Ελέγχου',
'ea:auth:Person_Work_Header':'Person -Work Fields',
'ea:auth:Person_Header_Basic':'Person - Βασικά πεδία',
'ea:auth:Person_Header_Additional':'Person - Προσωπικά στοιχεία',
'ea:auth:Person_Header_Local':'Person - Τοπικά στοιχεία',
'ea:auth:Person_Header_Information':'Person -  Πληροφοριακά πεδία',
'ea:auth:Person_Header_Link':'Person - Link με άλλα καθιερωμένα αρχεία, θησαυρούς κλπ.',
'ea:auth:Person_Header_Cataloging':'Person - Ταξινόμηση & Καταλογογράφηση',
'ea:auth:Person_Header_Subjects':'Person - Θέματα',
'ea:auth:Person_Header_Relations':'Person - Σχέσεις',
'ea:auth:Person_Entity_Language':'Γλώσσα όρου',
'ea:auth:Person_Ind1':'Τύπος του ονόματος',
'ea:auth:person_name_other_lang':'Όνομα σε άλλη γλώσσα',
'ea:authPerson:AttributesTitle':'Τίτλος',
'ea:authPersonAssociated:Place_Birth':'Τόπος γέννησης',
'ea:authPersonAssociated:Place_Death':'Τόπος θανάτου',
'ea:auth:CountryName':'Χώρα',
'ea:auth:CountryName_assoc':'Συνδεδεμένη χώρα',
'ea:authAssociated:Residence_Place':'Τόπος Κατοικία',
'ea:authAssociated:Residence_Place_Organization':'Έδρα Organization',
'ea:authAssociated:Residence_Place_Simple':'Τόπος',
'ea:authAssociated:OtherPlace_Place':'Τόπος δράσης',
'ea:authAssociated:OtherPlace_Place2':'Τόπος',
'ea:auth:Activity_Field':'Συγγραφική ιδιότητα',
'ea:auth:Activity_Field3':'Μουσική ιδιότητα',
'ea:auth:Relation_Civil_War':'Σχέση με εμφύλιο πόλεμο',
'ea:auth:Commission':'Αξίωμα',
'ea:auth:Activity_Field2':'Πεδίο',
'ea:authPerson:Group_Group':'Συνδεδεμένοι φορείς',
'ea:authPerson:Group_Group2':'Φορέας',
'ea:authPerson:Occupation_Name':'Επάγγελμα',
'ea:authPerson:Gender_Name':'Φύλο',
'ea:authAssociated:Language':'Γλώσσες',
'ea:auth:Nationality':'Εθνικότητα',
'ea:authPersonCoded:Dates_Birth':'Ημερομηνία γέννησης',
'ea:authPersonCoded:Dates_Death':'Ημερομηνία θανάτου',
'ea:auth:NoteNonpublic':'Μη δημόσια  σημείωση',
'ea:auth:NotePublic':'Δημόσια σημείωση',
'ea:authBiographical:Data_Text':'Βιογραφικά στοιχεία',
'ea:authBiographical_Work:Data_Text':'Πληροφοριακά  στοιχεία',
'ea:authElectronic:Location':'Σχετικές ιστοσελίδες',
'ea:auth:Address_Address':'Διεύθυνση',
'ea:auth:Address_Address2':'Διεύθυνση',
'ea:auth:Citizenship':'Υπηκοότητα',
'ea:auth:Address_City':'Πόλη',
'ea:auth:Address_Jurisdiction':'Νομός',
'ea:auth:Address_Post':'Ταχυδρομικός Κώδικας',
'ea:auth:Address_Mail':'E-mail',
'authPersonSee':'Relation with not use terms (see)',
'ea:authPersonSee:Id':'Personal name (not use)',
'ea:auth:Person_Name':'Όνομα Person',
'ea:auth:Person_Numeration':'Αρίθμηση',
'ea:auth:Person_TitlesAssociated':'Τίτλοι Person',
'ea:auth:Person_DatesAssociated':'Ημερομηνίες Person',
'ea:auth:Person_FullerName':'Επέκταση Αρχικών Ονόματος',
'ea:auth:Person_FormSubdivision':'Form subdivision',
'ea:auth:Person_GeneralSubdivision':'General subdivision',
'ea:auth:Person_ChronoSubdivision':'Chronological subdivision',
'ea:auth:Person_GeographicSubdivision':'Geographic subdivision',
'ea:auth:Participation_in_events':'Συμμετοχή στον Εμφύλιο',
'ea:auth:personalCourseLeftist':'Προσωπική πορεία Αριστερών',
'ea:auth:participationNationalists':'Συμμετοχή Εθνικοφρόνων',
'ea:auth:personSee':'Μη χρησιμοποιούμενο όνομα',
'ea:auth:personSeeAlso':'Εναλλακτικό όνομα που χρησιμοποιείται',
'ea:auth:personΑlternativesNames':'Εναλλακτικό όνομα',
'ea:auth:personSeealsoPerson':'Συγγενικές σχέσεις',
'ea:auth:personSeealsoOrganization':'Σχέσεις με οργανισμούς',
'ea:auth:personSeealsoFamily':'Οικογενειακές σχέσεις',
'ea:auth:personOtherlanguage':'Person σε άλλη γλώσσα',
'ea:auth:Subject':'Θέμα',
'ea:auth:Keywords':'Λέξεις κλειδιά',
'ea:auth:person_name_other_lang':'Όνομα σε άλλη γλώσσα',

/*********** Auth_family **********/
'ea:auth:Family_Header_Fields':'Πεδία Family',
'ea:auth:Family_Header_Basic':'Family - Βασικά πεδία',
'ea:auth:Family_Header_Additional':'Family - Πρόσθετα στοιχεία',
'ea:auth:Family_Header_Information':'Family - Πληροφοριακά πεδία',
'ea:auth:Family_Header_Control': 'Family - Πεδία Ελέγχου',
'ea:auth:Family_Header_Link':'Family - Link με άλλα καθιερωμένα αρχεία, θησαυρούς κλπ.',
'ea:auth:Family_Header_Cataloging':'Family - Ταξινόμηση & Καταλογογράφηση',
'ea:auth:Family_Header_Subjects':'Family - Θέματα',
'ea:auth:Family_Header_Relations':'Family - Σχέσεις',
'ea:auth:Family_Ind1':'Type of personal name',
'ea:auth:Family_Titles_Place':'Τόπος συνδεδεμένος με Οικογένεια',
'ea:auth:Family_Type':'Τύπος οικογένειας',
'ea:auth:family_DatesAssociated':'Ημερομηνία σχετική με Οικογένεια',
'authFamily':'Όνομα Οικογένειας',
'ea:auth:FamilyCodedDates_StartPeriod':'Ίδρυση - Δημιουργία',
'ea:auth:FamilyCodedDates_EndPeriod':'Διάλυση - Παύση',
'authFamilyInformation':'Πληροφορίες σχετικές με Family',
'ea:auth:FamilyInformation_Type':'Τύπος Family',
'ea:auth:FamilyInformation_Member':'Όνομα εξέχοντος μέλους',
'authFamilyInformation_StartPeriod':'Αρχική περίοδος',
'authFamilyInformation_EndPeriod':'Τελική περίοδος',
'ea:auth:Family_see':'Εναλλακτικό όνομα που χρησιμοποιείται',
'ea:auth:Family_see_also':'Μη χρησιμοποιούμενο όνομα',
'ea:auth:FamilySeeAlsoFamily':'Σχέσεις με οικογένειες',
'ea:auth:FamilySeealsoPerson':'Σχέσεις με πρόσωπα',
'ea:auth:Family_Other_Language':'Family σε άλλη γλώσσα',

/*********  Organization  ********/
'Header_Organization':'Πεδία Organization',
'ea:control:Header_Organization_Control':'Organization - Πεδία Ελέγχου',
'ea:auth:Organization_Header_Basic':'Organization - Βασικά πεδία',
'ea:auth:Organization_Header_Additional':'Organization - Πρόσθετα στοιχεία',
'ea:auth:Organization_Header_Local':'Organization - Τοπικά στοιχεία',
'ea:auth:Organization_Header_Information':'Organization- Πληροφοριακά πεδία',
'ea:auth:Organization_Header_Link':'Organization - Link με άλλα καθιερωμένα αρχεία, θησαυρούς κλπ.',
'ea:auth:Organization_Header_Cataloging':'Organization -  Ταξινόμηση & Καταλογογράφηση',
'ea:auth:Organization_Header_Subjects':'Organization - Θέματα',
'ea:auth:Organization_Header_Relations':'Organization - Σχέσεις',
'ea:auth:Organization_Subdivision':'Υποδιαίρεση Οργανισμού',
'ea:auth:Organization_Addition':'Προσθήκες στο όνομα',
'ea:auth:Organization_Number':'Αριθμός συνάντησης',
'ea:auth:Organization_Date':'Ημερομηνία συνάντησης',
'ea:auth:Organization_Location':'Τόπος συνάντησης',
'ea:auth:Organization_Attributes_StartPeriod':'Ίδρυση – Δημιουργία',
'ea:auth:Organization_Attributes_EndPeriod':'Διάλυση - Παύση',
'ea:auth:Organization_Reopening':'Επαναλειτουργία',
'establish_place':'Τόπος ίδρυσης',
'organization_Activity_Field':'Κατηγορία οργανισμού',
'ea:auth:Organization_see_also':'Εναλλακτικό όνομα που χρησιμοποιείται',
'ea:auth:OrganizationSeeAlsoOrganization':'Σχέσεις με οργανισμούς',
'ea:auth:Relation_Organization_Family':'Relationship with Family (See Also)',
'ea:auth:Relation_Organization_Person':'Relationship with Person (See Also)',
'ea:auth:OrganizationSeealsoFamily':'Σχέση με οικογένειες',
'authOrganization':'Organization',
'authOrganization_Name':'Όνομα Οργανισμού',
'ea:auth:Organization_Subordinate_Unit':'Subordinate unit',
'authOrganizationAttributes':'Τύπος Οργανισμού',
'ea:auth:Organization_Attributes_Type':'Type',
'OrganizationCodedDates_Start_Period':'Organization Start period',
'OrganizationCodedDates_End_Period':'Organization End period',
'ea:auth:Organization_Ind1':'Τύπος ονόματος',
'ea:auth:Organization_Other_Language':'Organization σε άλλη γλώσσα',
'relation_geographical_location':'Γεωγραφικός τόπος',

/*********** Auth_Manifestation **********/
'ea:manif:editorVersion':'Επιμελητή έκδοσης',
'ea:manif:authorPreface':'Συγγραφέας Προλόγου',
'ea:manif:admissionAuthor':'Συγγραφέας Εισαγωγής',
'ea:manif:distributor':'Διαθέτης',
'ea:manif:filmDistributor':'Διαθέτης κινηματογραφικών ταινιών',
'ea:manif:publisher':'Εκδότης',
'ea:manif:broadcaster':'Εκφωνητής',
'ea:manif:manufacturer':'Κατασκευαστής',
'ea:manif:lithographer':'Λιθογράφος',
'ea:manif:etcher':'Οξυγράφος',
'ea:manif:bookDesigner':'Σχεδιαστής βιβλίου',
'ea:manif:printer':'Τυπογράφος',
'ea:manif:engraver':'Χαράκτης',
'ea:manif:brailleEmbosser':'Braille embosser',
'ea:manif:caster':'Caster',
'ea:manif:collotyper':'Collotyper',
'ea:manif:platemaker':'Platemaker',
'ea:manif:printmaker':'Printmaker',
'Header_Manifestation':'Πεδία Manifestation',
'Header_Manifestation_Music':'Πεδία Μουσικού Manifestation',
'Header_Manifestation_Control':'Manifestation - Πεδία Ελέγχου',
'ea:manif:Header':'Manifestation',
'ea:manif:Header_Title':'Manifestation - Πεδία Τίτλου',
'ea:manif:Header_Basic':'Manifestation - Βασικά πεδία',
'ea:manif:Header_Additional':'Manifestation - Πρόσθετα στοιχεία',
'ea:manif:Header_Information':'Manifestation -  Πληροφοριακά πεδία',
'ea:auth:Manifestation_Header_Cataloging':'Manifestation - Ταξινόμηση & Καταλογογράφηση',
'ea:manif:Header_Work_Manifestation':'Work – Expression του Manifestation',
'ea:manif:Header_Digital_Item':'Ψηφιακά τεκμήρια',
'ea:manif:Header_Expression':'Expression',
'ea:manif:Header_Contributors':'Manifestation - Συντελεστές',
'ea:manif:Header_Subjects':'Manifestation - Θέματα',
'ea:manif:Header_Relations':'Manifestation - Σχέσεις',
'ea:manif:Type':'Τύπος Manifestation',
'ea:manif:Title':'Τίτλος',
'ea:manif:Title_manif':'Τίτλος Manifestation',
'ea:manif:Title_Proper':'Κύριος Τίτλος',
'ea:manif:Title_Medium':'Προσδιορισμός υλικού',
'ea:manif:Title_Remainder':'Υπότιτλος',
'ea:manif:Title_Responsibility':'Δηλώσεις υπευθυνότητας',
'ea:manif:Title_PartNumber':'Αριθμός μέρους',
'ea:manif:Title_PartName':'Όνομα μέρους',
'ea:manif:Edition':'Έκδοση',
'ea:manif:Edition_Statement':'Δήλωση έκδοσης',
'ea:manif:Edition_Remainder':'Υπόλοιπο δήλωσης έκδοσης',
'ea:manif:AbbreviatedTitle':'Abbreviated title',
'ea:manif:KeyTitle':'Key title',
'ea:manif:Additional_Title':'Πρόσθετοι Τίτλοι',
'ea:manif:Additional_Title_Display':'Εμφάνιση κειμένου',
'ea:manif:Additional_Title_Proper':'Τίτλος',
'ea:manif:Additional_Title_Remainder':'Υπότιτλος',
'ea:manif:Additional_Title_PartNumber':'Αριθμός μέρους / τμήματος',
'ea:manif:Additional_Title_PartName':'Όνομα μέρους / τμήματος',
'ea:manif:availability':'Διαθεσιμότητα Manifestation',
'ea:manif:availability_library':'Διαθεσιμότητα (Βιβλιοθήκη/Αρχείο)',
'ea:manif:availability_url':'URL OPAC',
'ea:manif:publications':'Δημοσιεύσεις',
'ea:manif:Publication':'Δημοσίευση',
'ea:manif:Publication_Place':'Τόπος έκδοσης',
'ea:manif:Publisher_Name':'Όνομα εκδότη',
'ea:manif:Publication_Date':'Ημερομηνία έκδοσης',
'ea:manif:Distribution':'Διάθεση',
'ea:manif:Distribution_Place':'Τόπος διάθεσης',
'ea:manif:Distribution_Name':'Όνομα διαθέτη',
'ea:manif:Distribution_Date':'Ημερομηνία διάθεσης',
'ea:manif:Production':'Παραγωγή',
'ea:manif:Production_Place':'Τόπος παραγωγής',
'ea:manif:Production_Name':'Όνομα παραγωγού',
'ea:manif:Production_Date':'Ημερομηνία παραγωγής',
'ea:manif:Manufactur':'Κατασκευή',
'ea:manif:Manufactur_Place':'Τόπος κατασκευής',
'ea:manif:Manufactur_Name':'Όνομα κατασκευαστή',
'ea:manif:Manufactur_Date':'Ημερομηνία κατασκευής',
'ea:manif:Physical_Description':'Φυσική περιγραφή',
'ea:manif:Physical_Description_Extent':'Έκταση',
'ea:manif:Physical_Description_Details':'Άλλες φυσικές λεπτομέρειες',
'ea:manif:Physical_Description_Dimensions':'Διαστάσεις',
'ea:manif:Physical_Description_Accompanying':'Συνοδευτικό υλικό',
'ea:manif:Media_Type':'Τύπος Media',
'ea:manif:Carrier_Type':'Τύπος Carrier',
'ea:manif:Series':'Σειρά',
'ea:manif:Series_Title':'Τίτλος σειράς',
'ea:manif:Series_Remainder':'Υπότιτλος',
'ea:manif:Series_Responsibility':'Δηλώσεις υπευθυνότητας',
'ea:manif:Series_Volume':'Προσδιορισμός τόμου',
'ea:manif:Series_ISSN':'ISSN',
'ea:manif:isbn_issn_ismn':'ISBN,ISSN,ISMN',
'ea:manif:ISBN':'ISBN',
'ea:manif:ISBN_Terms':'Όροι διαθεσιμότητας',
'ea:manif:ISBN_Qualify':'Προσδιορισμός πληροφορίας',
'ea:manif:ISBN_Canceled':'Λανθασμένο/Ακυρωμένο ISBN',
'ea:manif:ISMN':'ISMN',
'ea:manif:ISMN_Terms':'Όροι διαθεσιμότητας',
'ea:manif:ISMN_Qualify':'Προσδιορισμός πληροφορίας',
'ea:manif:ISMN_Canceled':'Λανθασμένο/Ακυρωμένο ISMN',
'ea:manif:ISSN':'ISSN',
'ea:manif:ISSN_Cancelled':'Λανθασμένο ISSN',
'ea:manif:ISSN_Incorrect':'Ακυρωμένο ISSN',
'ea:manif:ISSN_LNumber':'Linking ISSN',
'ea:manif:ISSN_LCanceled':'Ακυρωμένο Linking ISSN',
'ea:manif:note':'Σημειώσεις',
'ea:manif:Serials_Numbering':'Αρίθμηση Περιοδικών',
'ea:manif:Country_Code':'Χώρα έκδοσης ή παραγωγής',
'ea:manif:Subject':'Θέμα',
'ea:manif:Work':'Work',
'ea:manif:Keywords':'Λέξεις Κλειδιά',
'ea:manif:Work_Expression':'Work/Expression ',
'ea:manif:Relation_Equivalent':'Ισοδύναμες σχέσεις',
'ea:manif:Relation_Descriptive':'Περιγραφικές σχέσεις',
'ea:manif:Relation_Wholepart':'Σχέσεις συνόλου / μέρους',
'ea:manif:Accompanying':'Συνοδευτικές σχέσεις',
'ea:manif:Header_Thumb':'Πληροφορίες Thumbnail',
'ea:manif:digital-item':'Ψηφιακό τεκμήριο',
'ea:manif:item':'Τεκμήριο',

/* ****************** Relation Firtst Version ******************** */
//'ea:manif:Relation_Expression_Work':'Expression με Work',
//'ea:manif:Relation_Expression_Other_Work':'Expression με άλλα Works',
//'ea:manif:Relation_Manifestation_Other_Manifestation':'Manifestation με άλλα Manifestation',
//'ea:manif:Relation_Whole_Part':'Σχέσεις συνόλου / μέρους',
//'ea:manif:Relation_Contributors_Expression':'Συντελεστές Expression',
//'ea:manif:Relation_Contributors_Manifestation':'Συντελεστές Manifestation',
//'ea:manif:Relation_Subject_Manifestation':'Θέματα Manifestation',
//'ea:manif:Relation_Subject_Expression':'Θέματα Expression',
/* ************************************************************** */
/*********  Work ********/
'work-expression':'Work – Expression',
'ea:work:Header':'Πεδία Work',
'ea:work:Header_Music':'Πεδία Μουσικού Work',
'ea:work:Header_Control':'Work - Πεδία ελέγχου',
'ea:work:Header_Basic':'Work - Βασικά πεδία',
'ea:work:Header_Additional':'Work - Πρόσθετα στοιχεία',
'ea:work:Header_Local':'Work - Τοπικά στοιχεία',
'ea:work:Header_Information':'Work - Πληροφοριακά πεδία',
'ea:auth:Work_Header_Cataloging':'Work - Ταξινόμηση & Καταλογογράφηση',
'ea:work:Header_Contributors':'Work - Συντελεστές',
'ea:work:Header_Subjects':'Work - Θέματα',
'ea:work:Header_Link':'Work - Link με άλλα καθιερωμένα αρχεία, θησαυρούς κλπ.',
'ea:work:Header_Relation':'Work - Σχέσεις',
'ea:work:Type':'Τύπος work',
'ea:work:Title_Preferred':'Τίτλος work',
'ea:work:Title_PartNumber':'Αριθμός μέρους',
'ea:work:Title_PartName':'Όνομα μέρους',
'ea:work:Form':'Μορφή work',
'ea:work:Form_Music':'Μορφή μουσικού work',
'ea:work:Date':'Ημερομηνία work',
'ea:work:Version':'Άλλα χαρακτηριστικά work',
'ea:work:Language':'Γλώσσα Work',
'ea:work:Place':'Τόπος προέλευσης work',
'ea:work:TypologyWork':'Τυπολογία έργου',
'ea:work:TypologyWork_Music':'Τυπολογία μουσικού work',
'ea:work:PoliticalSupport':'Πολιτική υποστήριξη',
'ea:work:chronological':'Χρονολογική κάλυψη',
'ea:work:geographical':'Γεωγραφική κάλυψη',
'ea:work:subjectCategory':'Θεματική κατηγορία',
'ea:work:noteNonpublic':'Nonpublic General Note',
'ea:work:notePublic':'Public General Note',
'ea:work:biographicalData_Text':'Biographical Data',
'ea:work:biographicalData_URL':'Related URL',
'ea:work:Relation_Descriptive':'Περιγραφικές σχέσεις',
'ea:work:Relation_Derivative':'Παράγωγες σχέσεις',
'ea:work:Relation_Wholepart':'Σχέσεις συνόλου / μέρους',
'ea:work:Relation_Accompanying':'Συνοδευτικές σχέσεις',
'ea:work:Relation_Sequential':'Διαδοχικές σχέσεις',
'ea:work:dedicateeWork':'Dedicatee',
'ea:work:landscapeArchitectWork':'Landscape architect',
'ea:work:architectWork':'Architect',
'ea:work:sculptorWork ':'Sculptor',
'ea:work:directorOfPhotographyWork':'Director of photography',
'ea:work:judgeWork':'Judge',
'ea:work:defendantWork':'Defendant',
'ea:work:plaintiffWork':'Plaintiff',
'ea:work:productionCompanyWork':'Production company',
'ea:work:inventorWork':'Inventor',
'ea:work:hostInstitutionWork':'Host institution',
'ea:work:degreeGrantingInstitutionWork':'Degree granting institution',
'ea:work:artistWork':'Artist',
'ea:work:filmmakerWork':'Filmmaker',
'ea:work:interviewerWork':'Interviewer',
'ea:work:librettistWork':'Librettist',
'ea:work:issuingBodyWork':'Issuing body',
'ea:work:sponsoringBodyWork':'Sponsoring body',
'ea:work:producerWork':'Producer',
'ea:work:filmProducerWork':'Film producer',
'ea:work:radioProducerWork':'Radio producer',
'ea:work:televisionProducerWork':'Television producer',
'ea:work:programmerWork':'Programmer',
'ea:work:screenwriterWork':'Screenwriter',
'ea:work:directorWork':'Director',
'ea:work:filmDirectorWork':'Film director',
'ea:work:radioDirectorWork':'Radio director',
'ea:work:televisionDirectorWork':'Television director',
'ea:work:lyricistWork':'Lyricist',
'ea:work:authorWork':'Author',
'ea:work:thesisAdvisor':'Thesis Advisor',
'ea:work:composerWork':'Composer',
'ea:work:compilerWork':'Compiler',
'ea:work:designerWork':'Designer',
'ea:work:honoureeWork':'Honouree',
'ea:work:photographerWork':'Photographer',
'ea:work:cartographerWork':'Cartographer',
'ea:work:choreographerWork':'Choreographer',
'ea:work:courtGovernedWork':'Court governed',
'ea:work:enactingJurisdictionWork':'Enacting jurisdiction',
'ea:work:jurisdictionGovernedWork':'Jurisdiction governed',
'ea:work:praesesWork':'Praeses',
'ea:work:respondentWork':'Respondent',
'ea:work:music_event':'Σχετικά μουσικά γεγονότα',

'Expressions_of_Work':'Διαθέσιμα Expressions του Work',
'Manifestation_of_Work':'Manifestation του πρωτότυπου Work',

'status_work':'Work - Κατάσταση εγγραφής',
'ea:work:Header_Thumb':'Work - Πληροφορίες Thumbnail',

/*********  Expression ********/
'expression_header_public': 'Πεδία Expression',
'expression_header_public_music': 'Πεδία Μουσικού Expression',
'expression_header_Control':'Expression - Πεδία Ελέγχου',
'status_expression':'Expression - Κατάσταση εγγραφής',
'ea:manif:Header_Work_Expression':'Work του Expression',
'ea:expression:Header':'Expression',
'ea:expression:Header_Relation_Expression':'Expression - Σχέσεις',
'ea:expres:Header_Basic':'Expression - Βασικά πεδία',
'ea:expres:Relation_Work':'Relation Expression-Work',
'ea:expres:Header_Specific':'Expression - Ειδικά πεδία',
'ea:expres:Header_Information':'Expression - Πληροφοριακά πεδία',
'ea:expres:Header_Contributors':'Expression - Συντελεστές',
'ea:expres:Header_Subjects':'Expression - Θέματα',
'ea:expres:title':'Τίτλος Expression',
'ea:expres:Form':'Μορφή Expression',
'ea:expres:Content':'Τύπος περιεχομένου',
'ea:expres:Language':'Γλώσσα Expression',
'ea:expres:Dates':'Ημερομηνία Expression',
'ea:expres:Version':'Άλλα χαρακτηριστικά Expression',
'ea:expres:Note_Content':'Περιεχόμενα',
'ea:expres:Note_Summary':'Περίληψη ',
'ea:expres:Note_Citation':'Κριτικές - Παρουσιάσεις',
'ea:expres:Note_Citation_Sourse':'Πηγή',
'ea:expres:Frequency':'Συχνότητα περιοδικών',
'ea:expres:Notated_Music':'Μορφή παρτιτούρας',
'ea:expres:Computer_Character':'Χαρακτηριστικά αρχείων υπολογιστών',
'ea:expres:Playing_Time':'Διάρκεια Expression',
'ea:expres:Symbology':'Συμβολισμός υλικών αφής',
'ea:expres:Scale':'Κλίμακα',
'ea:expres:Note_Citation_Url':'URL',
'ea:expres:Url':'URL',

/********* Concept Fields ********/
'concept_header_public': 'Πεδία Concept',
'ea:auth:Concept_Term':'Όρος Concept',
'ea:auth:Concept_Type':'Τύπος Concept',
'ea:auth:Concept_Header_Control':'Concept - Πεδία Ελέγχου',
'ea:auth:Concept_Header_Basic':'Concept - Βασικά πεδία',
'ea:auth:Concept_Header_Additional':'Concept - Πρόσθετα στοιχεία',
'ea:auth:Concept_Header_Information':'Concept- Πληροφοριακά πεδία',
'ea:auth:Concept_Header_Link':'Concept - Link με άλλα καθιερωμένα αρχεία, θησαυρούς κλπ. ',
'ea:auth:Concept_Header_Cataloging':'Concept - Ταξινόμηση & Καταλογογράφηση',
'ea:auth:Concept_Header_Subjects':'Concept - Subjects',
'ea:auth:Concept_Header_Relations':'Concept - Σχέσεις',
'ea:auth:conceptSee':' Μη χρησιμοποιούμενο όνομα',
'ea:auth:Concept_See_Also':'Εναλλακτικό όνομα που χρησιμοποιείται',
'ea:auth:Relation_Concept_Concept':'Σχέσεις με άλλους όρους',
'ea:auth:Concept_Other_Language':'Concept σε άλλη γλώσσα',

/********* Obj_collection Fields ********/
'ea:auth:Obj_collection_Term':'Όρος Συλλογής Αντικειμένων',
'ea:auth:Obj_collection_Header_Basic':'Συλλογή Αντικειμένων - Βασικά πεδία',
'ea:auth:Obj_collection_Header_Additional':'Συλλογή Αντικειμένων - Πρόσθετα στοιχεία',
'ea:auth:Obj_collection_Header_Information':'Συλλογή Αντικειμένων- Πληροφοριακά πεδία',
'ea:auth:Obj_collection_Header_Link':'Συλλογή Αντικειμένων - Link με άλλα καθιερωμένα αρχεία, θησαυρούς κλπ. ',
'ea:auth:Obj_collection_Header_Cataloging':'Συλλογή Αντικειμένων - Ταξινόμηση & Καταλογογράφηση',
'ea:auth:Obj_collection_Header_Subjects':'Συλλογή Αντικειμένων - Subjects',
'ea:auth:Obj_collection_Header_Relations':'Συλλογή Αντικειμένων - Σχέσεις',


/**********  Place  **************/
'ea:auth:Place_Term':'Όρος Place',
'ea:auth:Place_Type':'Τύπος Place',
'place_header_public': 'Πεδία Place',
'place_header_control': 'Place - Πεδία Ελέγχου',
'ea:auth:Place_Header_Basic':'Place - Βασικά πεδία',
'ea:auth:Place_Header_Additional':'Place - Πρόσθετα στοιχεία',
'ea:auth:Place_Header_Information':'Place- Πληροφοριακά πεδία',
'ea:auth:Place_Header_Link':'Place -Link με άλλα καθιερωμένα αρχεία, θησαυρούς κλπ. ',
'ea:auth:Place_Header_Cataloging':'Place - Ταξινόμηση & Καταλογογράφηση',
'ea:auth:Place_Header_Subjects':'Place - Θέματα',
'ea:auth:Place_Header_Relations':'Place - Σχέσεις',
'ea:auth:Place_not_use':'Μη χρησιμοποιούμενο όνομα',
'ea:auth:Place_Αlternatives':'Εναλλακτικό όνομα που χρησιμοποιείται',
'ea:auth:Place_Other':'Σχέσεις με άλλα Place',
'ea:auth:Place_Other_Language':'Place σε άλλη γλώσσα',
'relation_place_organization':'Σχέσεις με Organization',


/********* Event Fields ********/
'ea:auth:Event_Term':'Όρος Event',
'event_header_public': 'Πεδία Event',
'ea:auth:Event_Type':'Τύπος Event',
'ea:auth:Event_Start_Date':'Ημερομηνία έναρξης',
'ea:auth:Event_Expiry_Date':'Ημερομηνία λήξης',
'ea:auth:Event_Place':'Τόπος',
'ea:event:musical_work':'Μουσικά έργα',
'ea:auth:Event_Involved':'Εμπλεκόμενοι',
'ea:auth:Event_Header_Control':'Event - Πεδία Ελέγχου',
'ea:auth:Event_Header_Basic':'Event - Βασικά πεδία',
'ea:auth:Event_Header_Additional':'Event - Πρόσθετα στοιχεία',
'ea:auth:Event_Header_Information':'Event - Πληροφοριακά πεδία',
'ea:auth:Event_Header_Link':'Event - Link με άλλα καθιερωμένα αρχεία, θησαυρούς κλπ. ',
'ea:auth:Event_Header_Cataloging':'Event - Ταξινόμηση & Καταλογογράφηση',
'ea:auth:Event_Header_Relations':'Event - Σχέσεις',
'ea:auth:Event_Other_Language':'Event σε άλλη γλώσσα',
'ea:auth:Event_not_use':'Μη χρησιμοποιούμενο όνομα',
'ea:auth:Event_See_Also':'Εναλλακτικό όνομα που χρησιμοποιείται',

/********* Genre Fields ********/
'ea:auth:Genre_Term':'Όρος Genre',
'genre_header_public': 'Πεδία Genre',
'ea:auth:Genre_Type': 'Τύπος Genre',
'ea:auth:Genre_Header_Control':'Genre - Πεδία Ελέγχου',
'ea:auth:Genre_Header_Basic':'Genre - Βασικά πεδία',
'ea:auth:Genre_Header_Additional':'Genre - Πρόσθετα στοιχεία',
'ea:auth:Genre_Header_Information':'Genre - Πληροφοριακά πεδία',
'ea:auth:Genre_Header_Link':'Genre - Link με άλλα καθιερωμένα αρχεία, θησαυρούς κλπ. ',
'ea:auth:Genre_Header_Cataloging':'Genre - Ταξινόμηση & Καταλογογράφηση',
'ea:auth:Genre_Header_Relations':'Genre - Σχέσεις',
'ea:auth:Genre_Other_Language':'Genre σε άλλη γλώσσα',
'ea:auth:Genre_See_Also':'Εναλλακτικό όνομα που χρησιμοποιείται',


/********* Object Fields ********/
'ea:auth:Object_Term':'Όρος Object',
'ea:auth:Object_Type':'Τύπος Object',
'object_header_public': 'Πεδία Object',
'ea:auth:Object_Header_Control':'Object - Πεδία Ελέγχου',
'ea:auth:Object_Header_Basic':'Object - Βασικά πεδία',
'ea:auth:Object_Header_Additional':'Object - Πρόσθετα στοιχεία',
'ea:auth:Object_Header_Information':'Object - Πληροφοριακά πεδία',
'ea:auth:Object_Header_Link':'Object - Link με άλλα καθιερωμένα αρχεία, θησαυρούς κλπ. ',
'ea:auth:Object_Header_Cataloging':'Object - Ταξινόμηση & Καταλογογράφηση',
'ea:auth:Object_Header_Relations':'Object - Σχέσεις',
'ea:auth:Object_Other_Language':'Object σε άλλη γλώσσα',
'ea:auth:Object_See_Also':'Εναλλακτικό όνομα που χρησιμοποιείται',
'ea:auth:Object_not_use':'Μη χρησιμοποιούμενο όνομα',

/********* General Fields ********/
'ea:auth:General_Term':'Όρος Subject',
'ea:auth:General_Header_Basic':'Subject - Βασικά πεδία',
'ea:auth:General_Header_Additional':'Subject - Πρόσθετα στοιχεία',
'ea:auth:General_Header_Information':'Subject- Πληροφοριακά πεδία',
'ea:auth:General_Header_Link':'Subject - Link με άλλα καθιερωμένα αρχεία, θησαυρούς κλπ. ',
'ea:auth:General_Header_Cataloging':'Subject - Ταξινόμηση & Καταλογογράφηση',
'ea:auth:General_Header_Relations':'Subject - Σχέσεις',
'ea:auth:General_Other_Language':'Subject σε άλλη γλώσσα',
'ea:auth:General_See_Also':'Εναλλακτικό όνομα Subject (See Also)',
'ea:auth:General_not_use':'Όρος που δε χρησιμοποιείται (See)',

/********* Control Fields ********/
'ea:control:Header_Control':'Πεδία ελέγχου',
'ea:control:Control_Number':'Αριθμός εγγραφής',
'ea:control:Latest_Transaction':'Τελευταία ενημέρωση',
'ea:control:Persistent':'Persistent Record Identifier',
'ea:control:Entity_Type':'Είδος Οντότητας',
'ea:control:Kind_Record':'Είδος της εγγραφής',
'ea:control:Level_Establish':'Επίπεδο καθιέρωσης',

/********* Link Fields ********/
'ea:link:bibliography':'Βιβλιοθήκη του Κογκρέσου',
'ea:link:bibliographyNumber':'Αριθμός Βιβλιογραφίας',
'ea:link:bibliographyInformation':'Πληροφορίες Βιβλιογραφίας',
'ea:link:Lccn_Number':'Βιβλιοθήκη του Κογκρέσου',
'ea:link:Lccn_Number2':'Αριθμός LC',
'ea:link:Lccn_Canceled':'Canceled or invalid number',
'ea:link:NationalBibliographyNumber_Number':'Εθνική Βιβλιοθήκη της Ελλάδας',
'ea:link:NationalBibliographyNumber_Number2':'Αριθμός EBE',
'ea:link:NationalBibliographyNumber_Canceled':'Canceled or invalid number',
'ea:link:Other_Number':'Wikidata',
'ea:link:Other_Number_Simple':'Αριθμός εγγραφής',
'ea:link:Other_Canceled':'Canceled or invalid number',
'ea:link:ISNI_Number':'ISNI',
'ea:link:ISNI_Number2':'Αριθμός ISNI',
'ea:link:ISNI_Canceled':'Canceled or invalid number',
'ea:link:VIAF_Number':'VIAF',
'ea:link:VIAF_Number2':'Αριθμός VIAF',
'ea:link:VIAF_Canceled':'Canceled or invalid number',
'ea:link:Lccn_Url':'Lccn Url',
'ea:link:NationalBibliographyNumber_Url':'URL ΕΒΕ',
'ea:link:Other_Url':'Url',
'ea:link:ISNI_Url':'ISNI Url',
'ea:link:VIAF_Url':'VIAF Url',

'ea:link:GeoNames':'GeoNames',
'ea:link:GeoNames_Number':'Αριθμός GeoNames',
'ea:link:GeoNames_Url':'GeoNames Url',

/********* Cataloging Fields ********/
'ea:classification:CatalogingSource':'Στοιχεία καταλογογράφησης',
'ea:classification:CatalogingSource_Original':'Φορέας πρωτότυπης καταλογογράφησης',
'ea:classification:CatalogingSource_Modifying':'Φορέας τροποποιημένης καταλογογράφησης',
'ea:classification:CatalogingSource_Language':'Γλώσσα της καταλογογράφησης',
'ea:classification:CatalogingSource_Rules':'Κανόνες καταλογογράφησης',
'ea:classification:LCClassification':'Ταξινομικός αριθμός LC',
'ea:classification:LCClassification2':'Ταξινόμηση LC',
'ea:classification:LCClassification_Start':'Αρχικός Ταξινομικός αριθμός ',
'ea:classification:LCClassification_End':'Τελικός Ταξινομικός αριθμός ',
'ea:classification:DDC':'Ταξινομικός αριθμός Dewey',
'ea:classification:DDC2':'Ταξινόμηση Dewey',
'ea:classification:DDC_NumberStart':'Αρχικός Ταξινομικός αριθμός ',
'ea:classification:DDC_NumberEnd':'Τελικός Ταξινομικός αριθμός ',
'ea:classification:DDC_Edition':'Edition number',
'ea:classification:Other_Number':'Τοπικός ταξινομικός αριθμός',
'ea:classification:Other_Number2':'Τοπική ταξινόμηση',
'ea:classification:Other_Number_Start':'Αρχικός Ταξινομικός αριθμός ',
'ea:classification:Other_Number_End':'Τελικός Ταξινομικός αριθμός ',

/********* Subject Fields ********/
'ea:subj:':'Θέματα',
'ea:subj:headers':'Θεματικές επικεφαλίδες',
'ea:subj:Header':'Θέματα',
'ea:subj:person-work':'Person-Work',
'ea:subj:person':'Πρόσωπο',
'ea:subj:work':'Work',
'ea:subj:object-instance':'Αντικείμενο (Μοναδικό)',
'ea:subj:object':'Αντικείμενα',
'ea:subj:event':'Γεγονός',
'ea:subj:concept':'Έννοια',
'ea:subj:object-collection':'Αντικείμενα',
'ea:subj:place':'Περιοχή',
'ea:subj:form':'Είδος',
'ea:subj:general':'Γενικό',
'ea:subj:title':'Τίτλος θέματος',

'ea:subj:person-work:primary':'Person-Work',
'ea:subj:person:primary':'Πρόσωπο',
'ea:subj:work:primary':'Work',
'ea:subj:object-instance:primary':'Αντικείμενο (Μοναδικό)',
'ea:subj:object:primary':'Αντικείμενα',
'ea:subj:event:primary':'Γεγονός',
'ea:subj:concept:primary':'Έννοια',
'ea:subj:object-collection:primary':'Αντικείμενα',
'ea:subj:place:primary':'Περιοχή',
'ea:subj:form:primary':'Είδος',
'ea:subj:general:primary':'Γενικό',

/********* Digital_item Fields ********/
'digital_item_header_public': 'Πεδία Digital Item',
'digital_item_control_fields':'Πεδία Digital Item - Πεδία Ελέγχου',
'ea:item:basic_fields':'Πεδία Digital Item - Βασικά πεδία',
'ea:item:additional_fields':'Πεδία Digital Item - Πληροφοριακά πεδία',
'ea:item:technical_fields':'Πεδία Digital Item - Ψηφιακά χαρακτηριστικά',
'header_digital_item_access':'Πεδία Digital Item - Δικαιώματα χρηστών',
'digital_item_control_status':'Πεδία Digital Item - Κατάσταση Εγγραφής',
'digital_item_contributor_field':'Πεδία Digital Item - Συντελεστές',
'digital_item_subjects_fields':'Πεδία Digital Item - Θέματα',
'digital_item_relations_fields':'Πεδία Digital Item - Σχέσεις',
'ea:item:title':'Πρωτότυπος Τίτλος',
'ea:item:type':'Τύπος item',
'ea:item:type_pdf':'Τύπος pdf',
'ea:item:location':'Location',
'ea:item:sublocation':'Sublocation',
'ea:item:collection':'Collection',
'ea:item:barcode':'Barcode, RFID κλπ.',
'ea:item:copyNumber':'Αριθμός αντιτύπου',
'ea:item:partNumber':'Αριθμός τόμου/μέρους',
'ea:item:parent_item':'Συνδεδεμένο με την οντότητα',
'ea:item:Classification':'Ταξινόμηση',
'ea:item:ClassificationNumber':'Ταξινομικός αριθμός',
'ea:item:ClassificationPrefix':'Πρόθεμα',
'ea:item:ClassificationCutter':'Cutter κλπ.',
'ea:item:accessRestrictions':'Περιορισμοί  πρόσβασης',
'ea:item:reproduction':'Περιορισμοί αναπ/γής',
'ea:item:binding':'Πληροφ.βιβλιοδεσίας',
'ea:item:history':'Ιστορία προέλευσης',
'ea:item:acquisitionMethod':'Μέθοδος απόκτησης',
'ea:item:acquisitionDate':'Ημερομηνία απόκτησης',
'ea:item:info':'Τεχνικές πληροφορίες',
'ea:item:description':'Περιγραφή αρχείου ',
'ea:item:filename':'Όνομα αρχείου Download',
'ea:item:size':'Μέγεθος αρχείου',
'ea:item:software':'Software αναπαραγωγής',
'ea:item:page':'Διαστάσεις αρχείου',
'ea:item:urlPublic':'Δημόσιο Url',
'ea:item:label':'Label',
'ea:item:urlPrivate':'Μη δημόσιο Url',


/********* Physical_item Fields ********/
'physical_item_header_public': 'Πεδία Physical Item',
'physical_item_control_fields':'Πεδία Physical Item - Πεδία Ελέγχου',
'physical_item_basic_fields':'Πεδία Physical Item - Βασικά πεδία',
'physical_item_characteristics_fields':'Πεδία Physical Item - Φυσικά χαρακτηριστικά',
'physical_item_additional_fields':'Πεδία Physical Item - Πληροφοριακά πεδία',
'physical_item_header_access':'Πεδία Physical Item - Δικαιώματα χρηστών',
'physical_item_control_status':'Πεδία Physical Item - Κατάσταση Εγγραφής',
'ea:item:item_loan':'Κανόνας δανεισμού',
'physical_item_contributor_field':'Πεδία Physical Item - Συντελεστές',
'physical_item_subjects_fields':'Πεδία Physical Item - Θέματα',
'physical_item_relations_fields':'Πεδία Physical Item - Σχέσεις',
'ea:item:Relation_Equivalent':'Ισοδύναμες σχέσεις',
'ea:item:Relation_Descriptive':'Περιγραφικές σχέσεις',
'ea:item:Relation_Wholepart':'Σχέσεις συνόλου / μέρους',
'ea:item:Accompanying':'Συνοδευτικές σχέσεις',


/********* Subject-Chain Fields ********/

'subject_chain_fields':'Πεδία Subject Chain',
'subject_chain_control_fields':'Subject Chain - Πεδία Ελέγχου',
'subject_chain_basic_fields':'Subject Chain - Βασικά Πεδία',
'subject_chain_information_fields':'Subject Chain - Πληροφοριακά Πεδία',
'subject_chain_link_fields':'Subject Chain - Link με άλλα καθιερωμένα αρχεία, θησαυρούς κλπ.',
'subject_chain_cataloging_fields':'Subject Chain - Ταξινόμηση & Καταλογογράφηση',
'subject_chain_relations_fields':'Subject Chain - Σχέσεις',
'subject_chain_term':'Θεματική επικεφαλίδα',
'subject_chain_primary_subj':'Πρωτεύον Θέμα',
'subject_chain_secondary_subj':'Υποδιαιρέσεις',
'relation_subject_chain_related':'Συσχετιζόμενοι όροι',
'relation_subject_chain_see_also':'Εναλλακτικό όνομα Subject chain (See Also)',
'relation_subject_chain_other_languages':'Subject chain σε άλλη γλώσσα',

	/********* Others Fields ********/
	'advanced_fields':'Εξειδικευμένα Πεδία',
	'contributor':'Συντελεστής',
	'contributor_w':'Δημιουργός',
	'contributor_e':'Συντελεστής Expression',
	'Add_Expression':'Προσθήκη Expression',
	'Add_Manifestation':'Προσθήκη Manifestation',
	'control_fields':'Πεδία Ελέγχου',
	'ea:auth:thumb_description':'Περιγραφή thumbnail',
	'new_place':'New Place',
	'work_title_specific':'Περιγραφή Work',
	'contributor_title_specific':'Σημείωση σχέσης',
	'note':'Σημείωση',
	'relation_note':'Σημείωση σχέσης',
	'place_title_specific':'Περιγραφή τόπου',
	'note_public':'Σημείωση',
	'ea:relation:Comment':'Σχόλιο',

	/********* Lemma ********/
	'lemma_header_public': 'Πεδία Λήμματος',
	'lemma_header_control':'Λήμμα - Πεδία ελέγχου',
	'lemma_header_basic': 'Λήμμα - Βασικά πεδία',
	'lemma_header_additional': 'Λήμμα - Bιβλιογραφικές αναφορές',
	'ea:lemma:title': 'Τίτλος',
	'ea:lemma:alternative_title': 'Eναλλακτικός τίτλος',
	'ea:lemma:author': 'Συγγραφέας λήμματος',
	'ea:lemma:body': 'Περιεχόμενο',
	'lemma_related_url':'Σχετικό URL',
	'ea:lemma:category': 'Κατηγορία',
	'ea:lemma:work':'Εργο λήμματος',
	'ea:lemma:book':'Book λήμματος',
	'ea:lemma:web_site_instance':'Web site λήμματος',
	'ea:lemma:periodic_publication':'Periodic publication λήμματος',
	'ea:lemma:media':'Media lemma',
	'lemma_manif_citations':'Manifestation λήμματος',
	'citation':'Αναφορά',
	'number_of_page':'Number of page',

	/********* Lemma Category ********/
	'lemma_category_header_public': 'Πεδία Κατηγορίας Λήμματος',
	'lemma_category_header_control':'Κατηγορίας Λήμματος - Πεδία ελέγχου',
	'lemma_category_header_basic': 'Κατηγορίας Λήμματος - Βασικά πεδία',
	'ea:lemma_category:title': 'Τίτλος',
	'lemma_category_relation': 'Σχέσεις κατηγορίας',


	/*********  Web Site Instance ********/
	'web_site_instance_header_public':'Web Site Fields',
	'web_site_instance_header_control':'Web Site - Control Fields',
	'web_site_instance_header_basic':'Web Site - Basic Fields',
	'web_site_instance_header_relation':'Web Site - Relations',
	'web_site_instance_header_information':'Web Site - Information Fields',
	'web_site_instance_header_additional':'Web Site - Additional Fields',
	'web_site_instance_header_subjects':'Web Site - Subjects',
	'web_site_instance_status':'Status',
	'site url-base': 'Site url-base',
	'site url': 'Site url',
	'web_site_instance_title_proper':'Title',
	'web_site_instance_title_remainder':'Title remainder',
	'web_site_instance_related_url':'Related url',
	'web_site_instance_publication_date':'Publication date',
	'other-info':'Other info',
	'web_site_instance_timestamp':'Timestamp captured',
	'web_site_instance_author':'Author',
	'web_site_instance_publication_name':'Publisher',
	'web_site_instance_work':'Work',
	'web_site_relation_other':'Relation other',


	/********* Periodic Publication ********/
	'periodic_publication_header_public':'Periodic Publication Fields',
	'periodic_publication_header_control':'Periodic Publication - Control Fields',
	'periodic_publication_header_basic':'Periodic Publication - Basic Fields',
	'periodic_publication_header_relation':'Periodic Publication - Relations',
	'periodic_publication_header_additional':'Periodic Publication - Additional Fields',
	'periodic_publication_header_information':'Periodic Publication - Information Fields',
	'periodic_publication_header_subjects':'Periodic Publication - Subjects',
	'periodic_publication_status':'Status',
	'ea:periodic_publication:type':'Type',
	'ea:periodic_publication:channel':'Channel',


	/********* Media ********/
	'media_header_public':'Media Fields',
	'media_header_control':'Media - Control Fields',
	'media_header_basic':'Media - Basic Fields',
	'media_header_relation':'Media - Relations',
	'media_header_additional':'Media - Additional Fields',
	'media_header_information':'Media - Information Fields',
	'media_header_subjects':'Media - Subjects',
	'media_status':'Status',

//	'ea:auth:Concept_Term':'Όρος Concept',
//	'ea:auth:Concept_Type':'Τύπος Concept',
//	'ea:auth:Concept_Header_Control':'Concept - Πεδία Ελέγχου',
//	'ea:auth:Concept_Header_Basic':'Concept - Βασικά πεδία',
//	'ea:auth:Concept_Header_Additional':'Concept - Πρόσθετα στοιχεία',
//	'ea:auth:Concept_Header_Information':'Concept- Πληροφοριακά πεδία',
//	'ea:auth:Concept_Header_Link':'Concept - Link με άλλα καθιερωμένα αρχεία, θησαυρούς κλπ. ',
//	'ea:auth:Concept_Header_Cataloging':'Concept - Ταξινόμηση & Καταλογογράφηση',
//	'ea:auth:Concept_Header_Subjects':'Concept - Subjects',
//	'ea:auth:Concept_Header_Relations':'Concept - Σχέσεις',
//	'ea:auth:conceptSee':' Μη χρησιμοποιούμενο όνομα',
//	'ea:auth:Concept_See_Also':'Εναλλακτικό όνομα που χρησιμοποιείται',
//	'ea:auth:Relation_Concept_Concept':'Σχέσεις με άλλους όρους',
//	'ea:auth:Concept_Other_Language':'Concept σε άλλη γλώσσα',


};





