var f_auth_general = [
'header_general_control_open',
//'latest_transaction',
//'persistent',
'entity_type',
'kind_record',
'control_number',
'authority_level_establish',
//'lang',
'header_general_public',
'header_sect_general_basic',
'entity_language',
'general_term',
//'subject_title',
'header_sect_general_information',
'nonpublic_general_note',
'public_general_note',
'biographical_work_data',
'electronic_location',
'header_sect_general_link',
'lccn_number',
'national_bibliography_number',
'number_other',
'isni_number',
'viaf_number',
'header_sect_general_cataloging',
//'lc_classification',
//'ddc_number',
//'other_classification',
//'cataloging_source_original',
'lc_classification_simple',
'ddc_number_simple',
'other_classification_simple',
'cataloging_source_original',
//'auth_keywords',
'header_sect_general_relations',
'relation_general_see_alter',
'relation_general_see_also',
'relation_other_entity_see_also',
'relation_general_other_language',
'header_general_status',
'status_finish',
'controled_subject_true',
'hidden_label',
];

var general_relation_extend_commands = [
'header_control_open',
'kind_record_extend',
'authority_level_establish_extend',
'extend_header_public',
//'header_sect_basic',
'entity_language',
'__PRIMARY__',
'header_status',
'status_finish',
'hidden_label',
];  

var general_relation_extend_commands_see_also = [
'header_control_open',
'kind_record',
'authority_level_establish_extend',
'extend_header_public',
//'header_sect_basic',
'entity_language',
'__PRIMARY__',
'header_status',
'status_finish',
'hidden_label',
];



var f_auth_general_extend = [
'extend_header_public',
'header_sect_general_basic',
'general_term',
'header_sect_general_information',
'nonpublic_general_note',
'public_general_note',
'biographical_data',
'electronic_location',
'status_finish',
'hidden_obj_type_general',
'controled_subject_false',
'hidden_label',
];


