
var f_digital_item = [
                  'header_digital_item_public',
                	'header_digital_item_control_open',
                	'entity_type',
                	'digital_item_control_number',
//                	'artifact_parent_item_label',
                	'digital_item_manif',
                	'header_digital_item_basic',
                	'item_title',
                	'item_type',
                	'item_location',
                	'item_sublocation',
                	'item_collection',
                	'item_partNumber',
                	'header_digital_item_technical',
                	'item_description',
                	'item_size',
                	'item_page',
                	'item_info',
                	'item_filename',
                	'item_software',
//                	'url_public',
//                	'item_url_private',
                	'header_digital_item_access',
                	'item_access_restrictions',
                	'item_reproduction',
                	'header_digital_item_additional',
                	'item_history',
                	'item_binding',
                	'nonpublic_general_note',
                	'public_general_note',
                	'item_acquisition_method',
                	'item_acquisition_date',
                	'electronic_location',
                	'header_digital_item_contributor',
              		'contributors_i',
                 	'header_digital_item_subjects',
                	'subject_all',
                	'subject_js',
                	'header_digital_item_relations',
                	'item_relation_equivalent',
                	'item_relation_descriptive',
                	'item_relation_wholepart',
                	'item_relation_accompanying',
                	'header_digital_item_status',
                	'status_finish',
                	'hidden_label',
//                	'artifact_status',
                ];



var f_digital_item_extend = [
                             'header_digital_item_public',
                           	'header_digital_item_basic',
//                           	'item_title',
                           	'__PRIMARY__',
                           	'item_type',
                           	'item_location',
                           	'item_sublocation',
                           	'item_collection',
                           	'item_partNumber',
                           	'header_digital_item_technical',
                           	'item_description',
                           	'item_size',
                           	'item_page',
                           	'item_info',
                           	'item_filename',
                           	'item_software',
                           	'header_digital_item_access',
                           	'item_access_restrictions',
                           	'item_reproduction',
                           	'header_digital_item_additional',
                           	'item_history',
                           	'item_binding',
                           	'header_digital_item_status',
                           	'status_finish',
                           	'hidden_label',
//                           	'artifact_status',
                           ];