var f_auth_work = [
	'header_public_work',
	'header_work_control_open',
//	'entity_type',
	'work_entity_type',
	'work_type',
	'control_number',
	'header_sect_work_basic',
	'hidden_obj_type_work',
	'work_title_preferred',
	'work_title_partNumber',
	'work_title_partName',
	'work_date',
	'work_place',
	'work_language',
	'work_version',
	'contributors_w',
	'subject_all',
	'header_sect_work_local',
	'work_form',
	'work_typology',
//	'work_political_support',
	'work_chronological',
	'work_geographical',
	'work_subject_category',
//	'bibliography',
	'header_sect_work_information',
	'nonpublic_general_note',
	'public_general_note',
	'biographical_work_data',
	'electronic_location',
	'header_sect_work_link',
	'national_bibliography_number',
	'number_other',
	'isni_number',
	'viaf_number',
	'header_sect_work_cataloging',
	'lc_classification_simple',
	'ddc_number_simple',
	'other_classification_simple',
	'cataloging_source_original',
	'header_sect_work_relation',
	'work_relation_descriptive',
	'work_relation_derivative',
	'work_relation_wholepart',
	'work_relation_accompanying',
	'work_relation_sequential',
	'header_work_status',
	'status',
	'sect_reverse_relations_manifestation',
	'reverse_work',
	'sect_reverse_relations_expression',
	'reverse_expressionOf',
	'empty1',
	'header_work_expression_sect',
	'header_work_manifestation_sect',
	'hidden_label',
	];


var  f_auth_work_extend = [
	'header_work_public_extented',
	'header_work_control_open_extented',
	'work_type_extented',
	'header_sect_work_basic_extend',
	'hidden_obj_type_work',
	 '__PRIMARY__',
	'work_title_partNumber',
	'work_title_partName',
	'work_date',
	'work_place',
	'work_language',
	'work_version',
	'contributors_w',
//	'subject_all',
//	'header_sect_work_additional_extend',
	'header_sect_work_local_extend',
	'work_form',
	'work_typology',
//	'work_political_support',
	'work_chronological',
	'work_geographical',
	'work_subject_category',
//	'bibliography',
	'header_sect_work_information_extend',
	'nonpublic_general_note',
	'public_general_note',
	'biographical_work_data',
	'electronic_location',
	'header_sect_work_link_extend',
	'national_bibliography_number',
	'number_other',
	'isni_number',
	'viaf_number',
	'header_sect_work_cataloging_extend',
	'lc_classification_simple',
	'ddc_number_simple',
	'other_classification_simple',
	'cataloging_source_original',
	'header_work_status_extented',
	'status_finish',
	'hidden_obj_type_work',
	'hidden_label',
//	'empty1',
//	'header_work_expression_sect_extented',
//	'header_work_manifestation_sect_extented',
];


var f_auth_work_music = [
                 	'header_public_work_music',
                 	'header_work_control_open',
                	'work_entity_type',
                 	'work_type',
                 	'control_number',
                 	'header_sect_work_basic',
                 	'hidden_obj_type_work',
                 	'work_title_preferred',
                 	'work_title_partNumber',
                 	'work_title_partName',
                 	'work_date',
                 	'work_place',
                 	'work_language',
                 	'work_version',
                 	'contributors_w',
                 	'subject_all',
                 	'header_sect_work_local',
                 	'work_form_music',
                 	'work_typology_music',
                 	'work_music_event',
                 	'work_chronological',
                 	'work_geographical',
                 	'work_subject_category',
                 	'header_sect_work_information',
                 	'nonpublic_general_note',
                 	'public_general_note',
                 	'biographical_work_data',
                 	'electronic_location',
                 	'header_sect_work_link',
                 	'national_bibliography_number',
                 	'number_other',
                 	'isni_number',
                 	'viaf_number',
                 	'header_sect_work_cataloging',
                 	'lc_classification_simple',
                 	'ddc_number_simple',
                 	'other_classification_simple',
                 	'cataloging_source_original',
                 	'header_sect_work_relation',
                 	'work_relation_descriptive',
                 	'work_relation_derivative',
                 	'work_relation_wholepart',
                 	'work_relation_accompanying',
                 	'work_relation_sequential',
                 	'header_work_status',
                 	'status',
                 	'sect_reverse_relations_manifestation',
                 	'reverse_work',
                 	'sect_reverse_relations_expression',
                 	'reverse_expressionOf',
                 	'empty1',
                 	'header_work_music_expression_sect',
                 	'header_work_manifestation_music_sect',
                 	'hidden_label',
                 	];






var f_auth_work_extend_subj = [
'header_work_public_extented',
'header_work_control_open_extented',
'work_type_extented',
'header_sect_work_basic_extend',
'hidden_obj_type_work',
'work_title_preferred',
'work_title_partNumber',
'work_title_partName',
'work_date',
'work_place',
'work_language',
'work_version',
'contributors_w',
//'subject_all',
//'header_sect_work_additional_extend',
'header_sect_work_local_extend',
'work_form',
'work_typology',
'work_political_support',
'work_chronological',
'work_geographical',
'work_subject_category',
'bibliography',
'header_sect_work_information_extend',
'nonpublic_general_note',
'public_general_note',
'biographical_work_data',
'electronic_location',
'header_sect_work_link_extend',
'national_bibliography_number',
'number_other',
'isni_number',
'viaf_number',
'header_sect_work_cataloging_extend',
'lc_classification_simple',
'ddc_number_simple',
'other_classification_simple',
'cataloging_source_original',
'header_work_status_extented',
'status_finish',
'hidden_label',
//'empty1',
//'header_work_expression_sect_extented',
//'header_work_manifestation_sect_extented',
	];
