
var formSetups = {
	'manuscript':f_manuscript,
	'book':f_book,
	'efimerida-tefxos':f_efimerida_tefxos,
	'mprosoura':f_book,
	'periodiko-tefxos':f_periodiko_tefxos,
	'web-site':f_wsite,
	'edocs':f_book,
	'afisa':f_1_page,
	'autokolito':f_1_page,
	'flyer':f_1_page,
	'image':f_1_page,
	'mprosoura':f_book,
	'other':f_1_page,
	'prokiri3i':f_1_page,
	'web-site-instance':f_web_site_instance,
	'actor':f_actor,
	'work':f_work,
	'place':f_place,
	'recipe':f_recipe,
	'material':f_material,
	'situation':f_situation,
	'process':f_process,
	'symbol':f_symbol,
	'instrument':f_instrument,
	//
	'efimerida':f_serial,
	'periodiko':f_serial,
	'silogi':f_collection,
	'bitstream':f_bitstream,
	'artifact1':f_artifact1,
	'artifact':f_artifact,
	'auth-person':f_auth_person,
	'auth-family':f_auth_family,
	'auth-organization':f_auth_organization,
	'auth-place':f_auth_place,
	'auth-book':f_auth_book,
};


