
var actor_type_map = {
		'undefined': 'undefined',
		'person': 'Person',
		'collective':'Collective',
		'collective_name':'Collective Name',
		'corporate_body':'Corporate Body',
		'family':'Family',
	};


var language_map = {
		'undefined':'Μη προσδιορισμένη',
		'gre':'Ελληνική',
		'grc':'Ελληνική, Αρχαία (μέχρι 1453)',
		'ave':'Αβεστική',
		'eng':'Αγγλική',
		'ang':'Αγγλική, Αρχαία (ca. 450-1100)',
		'enm':'Αγγλική, Μεσαιωνική (1100-1500)',
		'aze':'Αζερική',
		'egy':'Αιγυπτιακή',
		'gez':'Αιθιοπική',
		'akk':'Ακκαδική',
		'alb':'Αλβανική',
		'alg':'Αλγκονκινική',
		'tut':'Αλταϊκή (Άλλες)',
		'und':'Απροσδιόριστη',
		'ara':'Αραβική',
		'arg':'Αραγκονική',
		'arc':'Αραμαϊκή',
		'arm':'Αρμενική',
		'afr':'Αφρικάανς',
		'afa':'Αφροασιατική',
		'wln':'Βαλλωνική',
		'bat':'Βαλτική (Άλλες)',
		'baq':'Βασκική',
		'ber':'Βερβερική (Άλλη)',
		'vie':'Βιετναμέζικη',
		'vol':'Βολαπιούκ',
		'bos':'Βοσνιακή',
		'bul':'Βουλγαρική',
		'glg':'Γαλικιανή',
		'fre':'Γαλλική',
		'fro':'Γαλλική, Αρχαία (π. 842-1300)',
		'frm':'Γαλλική, Μεσαιωνική (π.1300-1600)',
		'gsw':'Γερμανικά, Ελβετικά',
		'ger':'Γερμανική',
		'gem':'Γερμανική (Άλλες)',
		'goh':'Γερμανική, Αρχαία Υψηλή (π. 750-1050)',
		'gmh':'Γερμανική, Μεσαιωνική Υψηλή (π. 1050-1500)',
		'geo':'Γεωργιανή',
		'yid':'Γίντις',
		'yor':'Γιορουμπά',
		'got':'Γοτθική',
		'dan':'Δανική',
		'mis':'Διάφορες γλώσσες',
		'dra':'Δραβιδική (Άλλη)',
		'heb':'Εβραϊκή',
		'est':'Εσθονική',
		'epo':'Εσπεράντο',
		'zza':'Ζαζαϊκή',
		'zul':'Ζουλού',
		'tib':'Θιβετιανή',
		'jpn':'Ιαπωνική',
		'aus':'Ινδογενής αυστραλιανές γλώσσες',
		'ine':'Ινδοευρωπαϊκή (Άλλες)',
		'ind':'Ινδονησιακή',
		'ido':'Ίντο',
		'ira':'Ιρανική (Άλλες)',
		'gle':'Ιρλανδική',
		'sga':'Ιρλανδική, Αρχαία (μέχρι το 1100)',
		'mga':'Ιρλανδική, Μεσαιωνική (π.1100-1550)',
		'iro':'Ιροκουά (Άλλες)',
		'ice':'Ισλανδική',
		'spa':'Ισπανική',
		'ita':'Ιταλική',
		'nap':'Ιταλική, Ναπολίτικη ',
		'scn':'Ιταλική, Σικελική',
		'kaz':'Καζακική',
		'kbd':'Καμπαντική',
		'cat':'Καταλανική',
		'cau':'Καυκάσια (Άλλες)',
		'cel':'Κέλτικες (Άλλες)',
		'que':'Κέτσουα',
		'chi':'Κινεζική',
		'kon':'Κονγκολεζική',
		'cop':'Κοπτική',
		'hrv':'Κορατική',
		'kor':'Κορεατική',
		'cor':'Κορνουαλική',
		'cos':'Κορσικανική',
		'kur':'Κουρδική',
		'cus':'Κουσιτική (Άλλες)',
		'crp':'Κρεολική και Pidgins (Άλλες)',
		'cre':'Κρι',
		'crh':'Κριμαϊκή Ταταρική',
		'kro':'Κρου (Άλλες)',
		'lad':'Λαντίνο (Ισπανοεβραϊκή)',
		'lat':'Λατινική',
		'lav':'Λεττονική',
		'bel':'Λευκορωσική',
		'lit':'Λιθουανική',
		'lim':'Λιμβουργιανή',
		'ltz':'Λουξεμβουργιανή',
		'mlt':'Μαλτεζική',
		'glv':'Μανξ',
		'mao':'Μαορί',
		'mas':'Μασάι ',
		'zxx':'Μη γλωσσικό περιεχόμενο',
		'mon':'Μογγολική',
		'moh':'Μόχακ',
		'bnt':'Μπαντού (Άλλες)',
		'ben':'Μπενγκάλι',
		'bis':'Μπισλάμα',
		'bre':'Μπρετονική',
		'nau':'Ναουρού',
		'nah':'Ναχουάτλ',
		'new':'Νεβάρι',
		'nep':'Νεπαλεζική',
		'sgn':'Νοηματικές γλώσσες',
		'nor':'Νορβηγική',
		'nob':'Νορβηγική (Bokmål)',
		'nno':'Νορβηγική (Nynorsk)',
		'div':'Ντιβέχι',
		'dut':'Ολλανδική',
		'dum':'Ολλανδική, Μεσαιωνική (π. 1050-1350)',
		'oto':'Οξιτανικές γλώσσες',
		'wel':'Ουαλική',
		'hun':'Ουγγαρική',
		'uga':'Ουγκαριτική',
		'uzb':'Ουζμπεκική',
		'ukr':'Ουκρανική',
		'pau':'Παλάου',
		'paa':'Παπούα (Άλλες)',
		'per':'Περσική',
		'peo':'Περσική, Αρχαία (π. 600-400 π.Χ)',
		'mul':'Πολλαπλές γλώσσες',
		'pol':'Πολωνική',
		'por':'Πορτογαλλική',
		'rom':'Ρομάνι',
		'roa':'Ρομανική (Άλλες)',
		'rum':'Ρουμανική',
		'rus':'Ρωσική',
		'smo':'Σαμόα (γλώσσα)',
		'san':'Σανσκριτική',
		'srd':'Σαρδινική',
		'srp':'Σερβική',
		'sem':'Σημιτικές (Άλλες)',
		'sit':'Σινοθιβετική (Άλλες)',
		'non':'Σκανδιναβική, Αρχαία',
		'sco':'Σκωτική',
		'gla':'Σκωτική Γαελική',
		'sla':'Σλαβική (Άλλες)',
		'chu':'Σλαβική εκκλησιαστική',
		'mac':'Σλαβομακεδονική',
		'slo':'Σλοβακική',
		'slv':'Σλοβενική',
		'som':'Σομαλική',
		'wen':'Σορβική (Άλλες)',
		'swa':'Σουαχίλι',
		'swe':'Σουηδική',
		'sux':'Σουμεριακή',
		'syc':'Συριακή, Κλασική',
		'syr':'Συριακή, Σύγχρονη',
		'tgl':'Ταγκαλόγκ',
		'tai':'Τάι (Άλλες)',
		'tha':'Ταϊλανδική',
		'tam':'Ταμίλ',
		'tat':'Ταταρική',
		'tgk':'Τατζικική',
		'tel':'Τελούγκου',
		'art':'Τεχνητή (Άλλη)',
		'tur':'Τουρκική',
		'ota':'Τουρκική, Οθωμανική',
		'tuk':'Τουρκμένικη',
		'cmc':'Τσαμικές γλώσσες',
		'chr':'Τσερόκι',
		'che':'Τσετσενική',
		'cze':'Τσεχική',
		'fil':'Φιλιππινεζική',
		'fin':'Φινλανδική',
		'haw':'Χαβαϊκή',
		'hit':'Χεττιτική',
		'hin':'Χίντι',
		'khm':'Χμερ',
		'aar':'Afar',
		'abk':'Abkhaz',
		'ace':'Achinese',
		'ach':'Acoli',
		'ada':'Adangme',
		'ady':'Adygei',
		'afh':'Afrihili (Artificial language)',
		'ain':'Ainu',
		'aka':'Akan',
		'ale':'Aleut',
		'alt':'Altai',
		'amh':'Amharic',
		'anp':'Angika',
		'apa':'Apache languages',
		'arp':'Arapaho',
		'arw':'Arawak',
		'rup':'Aromanian',
		'asm':'Assamese',
		'ath':'Athapascan (Other)',
		'map':'Austronesian (Other)',
		'ava':'Avaric',
		'awa':'Awadhi',
		'aym':'Aymara',
		'ast':'Bable',
		'ban':'Balinese',
		'bal':'Baluchi',
		'bam':'Bambara',
		'bai':'Bamileke languages',
		'bad':'Banda languages',
		'bas':'Basa',
		'bak':'Bashkir',
		'btk':'Batak',
		'bej':'Beja',
		'bem':'Bemba',
		'bho':'Bhojpuri',
		'bih':'Bihari (Other)',
		'bik':'Bikol',
		'byn':'Bilin',
		'bin':'Bini, Edo',
		'zbl':'Blissymbolics',
		'bra':'Braj',
		'bug':'Bugis',
		'bua':'Buriat',
		'bur':'Burmese',
		'cad':'Caddo',
		'car':'Carib',
		'ceb':'Cebuano',
		'cai':'Central American Indian (Other)',
		'chg':'Chagatai',
		'cha':'Chamorro',
		'chy':'Cheyenne',
		'chb':'Chibcha',
		'chn':'Chinook jargon',
		'chp':'Chipewyan',
		'cho':'Choctaw',
		'chk':'Chuukese',
		'chv':'Chuvash',
		'mus':'Creek',
		'cpe':'Creoles and Pidgins, English-based (Other)',
		'cpf':'Creoles and Pidgins, French-based (Other)',
		'cpp':'Creoles and Pidgins, Portuguese-based (Other)',
		'dak':'Dakota',
		'dar':'Dargwa',
		'day':'Dayak',
		'del':'Delaware',
		'din':'Dinka',
		'doi':'Dogri',
		'dgr':'Dogrib',
		'dua':'Duala',
		'dyu':'Dyula',
		'dzo':'Dzongkha',
		'frs':'East Frisian',
		'efi':'Efik',
		'eka':'Ekajuk',
		'elx':'Elamite',
		'myv':'Erzya',
		'ewe':'Ewe',
		'ewo':'Ewondo',
		'fan':'Fang',
		'fat':'Fanti',
		'fao':'Faroese',
		'fij':'Fijian',
		'fiu':'Finno-Ugrian (Other)',
		'fon':'Fon',
		'fry':'Frisian',
		'fur':'Friulian',
		'ful':'Fula',
		'gaa':'Gã',
		'lug':'Ganda',
		'gay':'Gayo',
		'gba':'Gbaya',
		'gil':'Gilbertese',
		'gon':'Gondi',
		'gor':'Gorontalo',
		'grb':'Grebo',
		'grn':'Guarani',
		'guj':'Gujarati',
		'gwi':'Gwich in',
		'hai':'Haida',
		'hat':'Haitian French Creole',
		'hau':'Hausa',
		'her':'Herero',
		'hil':'Hiligaynon',
		'hmo':'Hiri Motu',
		'hmn':'Hmong',
		'hup':'Hupa',
		'iba':'Iban',
		'ibo':'Igbo',
		'ijo':'Ijo',
		'ilo':'Iloko',
		'smn':'Inari Sami',
		'inc':'Indic (Other)',
		'inh':'Ingush',
		'ina':'Interlingua (International Auxiliary Language Association)',
		'ile':'Interlingue',
		'iku':'Inuktitut',
		'ipk':'Inupiaq',
		'jav':'Javanese',
		'jrb':'Judeo-Arabic',
		'jpr':'Judeo-Persian',
		'kab':'Kabyle',
		'kac':'Kachin',
		'kal':'Kalâtdlisut',
		'kam':'Kamba',
		'kan':'Kannada',
		'kau':'Kanuri',
		'kaa':'Kara-Kalpak',
		'krc':'Karachay-Balkar',
		'krl':'Karelian',
		'kar':'Karen languages',
		'kas':'Kashmiri',
		'csb':'Kashubian',
		'kaw':'Kawi',
		'kha':'Khasi',
		'khi':'Khoisan (Other)',
		'kho':'Khotanese',
		'kik':'Kikuyu',
		'kmb':'Kimbundu',
		'kin':'Kinyarwanda',
		'tlh':'Klingon (Artificial language)',
		'kom':'Komi',
		'kok':'Konkani',
		'kut':'Kootenai',
		'kos':'Kosraean',
		'kpe':'Kpelle',
		'kua':'Kuanyama',
		'kum':'Kumyk',
		'kru':'Kurukh',
		'kir':'Kyrgyz',
		'lah':'Lahndā',
		'lam':'Lamba (Zambia and Congo)',
		'lao':'Lao',
		'lez':'Lezgian',
		'lin':'Lingala',
		'jbo':'Lojban (Artificial language)',
		'nds':'Low German',
		'dsb':'Lower Sorbian',
		'loz':'Lozi',
		'lub':'Luba-Katanga',
		'lua':'Luba-Lulua',
		'lui':'Luiseño',
		'smj':'Lule Sami',
		'lun':'Lunda',
		'luo':'Luo (Kenya and Tanzania)',
		'lus':'Lushai',
		'mad':'Madurese',
		'mag':'Magahi',
		'mai':'Maithili',
		'mak':'Makasar',
		'mlg':'Malagasy',
		'may':'Malay',
		'mal':'Malayalam',
		'mnc':'Manchu',
		'mdr':'Mandar',
		'man':'Mandingo',
		'mni':'Manipuri',
		'mno':'Manobo languages',
		'arn':'Mapuche',
		'mar':'Marathi',
		'chm':'Mari',
		'mah':'Marshallese',
		'mwr':'Marwari',
		'myn':'Mayan languages',
		'men':'Mende',
		'mic':'Micmac',
		'min':'Minangkabau',
		'mwl':'Mirandese',
		'mdf':'Moksha',
		'mkh':'Mon-Khmer (Other)',
		'lol':'Mongo-Nkundu',
		'mos':'Mooré',
		'mun':'Munda (Other)',
		'nqo':'N Ko',
		'nav':'Navajo',
		'nbl':'Ndebele (South Africa)',
		'nde':'Ndebele (Zimbabwe)',
		'ndo':'Ndonga',
		'nwc':'Newari, Old',
		'nia':'Nias',
		'nic':'Niger-Kordofanian (Other)',
		'ssa':'Nilo-Saharan (Other)',
		'niu':'Niuean',
		'nog':'Nogai',
		'nai':'North American Indian (Other)',
		'frr':'North Frisian',
		'sme':'Northern Sami',
		'nso':'Northern Sotho',
		'nub':'Nubian languages',
		'nym':'Nyamwezi',
		'nya':'Nyanja',
		'nyn':'Nyankole',
		'nyo':'Nyoro',
		'nzi':'Nzima',
		'xal':'Oirat',
		'pal':'Pahlavi',
		'pli':'Pali',
		'pam':'Pampanga',
		'pag':'Pangasinan',
		'pan':'Panjabi',
		'pap':'Papiamento',
		'phi':'Philippine (Other)',
		'phn':'Phoenician',
		'pon':'Pohnpeian',
		'pra':'Prakrit languages',
		'pro':'Provençal (to 1500)',
		'pus':'Pushto',
		'roh':'Raeto-Romance',
		'raj':'Rajasthani',
		'rap':'Rapanui',
		'rar':'Rarotongan',
		'run':'Rundi',
		'sal':'Salishan languages',
		'sam':'Samaritan Aramaic',
		'smi':'Sami',
		'sad':'Sandawe',
		'sag':'Sango (Ubangi Creole)',
		'sat':'Santali',
		'sas':'Sasak',
		'sel':'Selkup',
		'srr':'Serer',
		'shn':'Shan',
		'sna':'Shona',
		'iii':'Sichuan Yi',
		'sid':'Sidamo',
		'bla':'Siksika',
		'snd':'Sindhi',
		'sin':'Sinhalese',
		'sio':'Siouan (Other)',
		'sms':'Skolt Sami',
		'den':'Slavey',
		'sog':'Sogdian',
		'son':'Songhai',
		'snk':'Soninke',
		'sot':'Sotho',
		'sai':'South American Indian (Other)',
		'sma':'Southern Sami',
		'srn':'Sranan',
		'suk':'Sukuma',
		'sun':'Sundanese',
		'sus':'Susu',
		'ssw':'Swazi',
		'tah':'Tahitian',
		'tmh':'Tamashek',
		'tem':'Temne',
		'ter':'Terena',
		'tet':'Tetum',
		'tig':'Tigré',
		'tir':'Tigrinya',
		'tiv':'Tiv',
		'tli':'Tlingit',
		'tpi':'Tok Pisin',
		'tkl':'Tokelauan',
		'tog':'Tonga (Nyasa)',
		'ton':'Tongan',
		'tsi':'Tsimshian',
		'tso':'Tsonga',
		'tsn':'Tswana',
		'tum':'Tumbuka',
		'tup':'Tupi languages',
		'tvl':'Tuvaluan',
		'tyv':'Tuvinian',
		'twi':'Twi',
		'udm':'Udmurt',
		'uig':'Uighur',
		'umb':'Umbundu',
		'hsb':'Upper Sorbian',
		'urd':'Urdu',
		'vai':'Vai',
		'ven':'Venda',
		'vot':'Votic',
		'wak':'Wakashan languages',
		'war':'Waray',
		'was':'Washoe',
		'him':'Western Pahari languages',
		'wal':'Wolayta',
		'wol':'Wolof',
		'xho':'Xhosa',
		'sah':'Yakut',
		'yao':'Yao (Africa)',
		'yap':'Yapese',
		'ypk':'Yupik languages',
		'znd':'Zande languages',
		'zap':'Zapotec',
		'zen':'Zenaga',
		'zha':'Zhuang',
		'zun':'Zuni',

		};


		//var language_map = {
		//'undefined':'Μη προσδιορισμένη',
		//'gre':'Ελληνική',
		//'grc':'Ελληνική, Αρχαία (μέχρι 1453)',
		//'alb':'Αλβανική',
		//'ara':'Αραβική',
		//'arm':'Αρμενική',
		//'baq':'Βασκική',
		//'bel':'Λευκορωσική',
		//'bos':'Βοσνιακή',
		//'bul':'Βουργαρική',
		//'cat':'Καταλανική',
		//'chi':'Κινεζική',
		//'cop':'Κοπτική',
		//'cze':'Τσεχική',
		//'dan':'Δανική',
		//'dut':'Ολλανδική',
		//'egy':'Αιγυπτιακή',
		//'eng':'Αγγλική',
		//'ang':'Αγγλική, Αρχαία (ca. 450-1100)',
		//'enm':'Αγγλική',
		//'fin':'Φινλανδική',
		//'fre':'Γαλλική',
		//'geo':'Γεωργιανή',
		//'ger':'Γερμανική',
		//'gle':'Ιρλανδική',
		//'heb':'Εβραϊκή',
		//'hrv':'Κορατική',
		//'hun':'Ουγγαρική',
		//'ice':'Ισλανδική',
		//'ita':'Ιταλική',
		//'jpn':'Ιαπωνική',
		//'kor':'Κορεατική',
		//'kur':'Κουρδική',
		//'lat':'Λατινική',
		//'mis':'Διάφορες γλώσσες',
		//'mul':'Πολλαπλές γλώσσες',
		//'per':'Περσική',
		//'pol':'Πολωνική',
		//'por':'Πορτογαλλική',
		//'rom':'Ρομά',
		//'rum':'Ρουμανική',
		//'rus':'Ρωσική',
		//'slo':'Σλοβακική',
		//'slv':'Σλοβενική',
		//'spa':'Ισπανική',
		//'srp':'Σερβική',
		//'swe':'Σουηδική',
		//'tur':'Τουρκική',
		//'ota':'Τουρκική, Οθωμανική',
		//'ukr':'Ουκρανική',
		//};


		var county_map = {
		'undefined':'Μη προσδιορισμένη',
		'GR':'Ελλάδα',
		'LC':'Αγία Λουκία',
		'BL':'Άγιος Βαρθολομαίος',
		'VC':'Άγιος Βικέντιος και Γρεναδίνες',
		'SM':'Άγιος Μαρίνος',
		'MF':'Άγιος Μαρτίνος (Γαλλία)',
		'SX':'Άγιος Μαρτίνος (Ολλανδία)',
		'KN':'Άγιος Χριστόφορος και Νέβις',
		'AZ':'Αζερμπαϊτζάν',
		'EG':'Αίγυπτος',
		'ET':'Αιθιοπία',
		'HT':'Αϊτή',
		'CI':'Ακτή Ελεφαντοστού',
		'AL':'Αλβανία',
		'DZ':'Αλγερία',
		'VI':'Αμερικανικές Παρθένοι Νήσοι',
		'AS':'Αμερικανική Σαμόα',
		'TL':'Ανατολικό Τιμόρ',
		'AO':'Ανγκόλα',
		'AI':'Ανγκουίλα',
		'AD':'Ανδόρρα',
		'AQ':'Ανταρκτική',
		'AG':'Αντίγκουα και Μπαρμπούντα',
		'UM':'Απομακρυσμένες Νησίδες των Ηνωμένων Πολιτειών',
		'AR':'Αργεντινή',
		'AM':'Αρμενία',
		'AW':'Αρούμπα',
		'AU':'Αυστραλία',
		'AT':'Αυστρία',
		'AF':'Αφγανιστάν',
		'VU':'Βανουάτου',
		'VA':'Βατικανό',
		'BE':'Βέλγιο',
		'VE':'Βενεζουέλα',
		'BM':'Βερμούδες',
		'VN':'Βιετνάμ',
		'BO':'Βολιβία',
		'MP':'Βόρειες Μαριάνες Νήσοι',
		'BA':'Βοσνία και Ερζεγοβίνη',
		'BG':'Βουλγαρία',
		'BR':'Βραζιλία',
		'VG':'Βρετανικές Παρθένοι Νήσοι',
		'IO':'Βρετανικό Έδαφος Ινδικού Ωκεανού',
		'FR':'Γαλλία',
		'TF':'Γαλλικά Νότια και Ανταρκτικά Εδάφη',
		'GF':'Γαλλική Γουιάνα',
		'PF':'Γαλλική Πολυνησία',
		'DE':'Γερμανία',
		'GE':'Γεωργία',
		'GI':'Γιβραλτάρ',
		'GM':'Γκάμπια',
		'GA':'Γκαμπόν',
		'GH':'Γκάνα',
		'GU':'Γκουάμ',
		'GP':'Γουαδελούπη',
		'GT':'Γουατεμάλα',
		'GY':'Γουιάνα',
		'GN':'Γουινέα',
		'GW':'Γουινέα-Μπισσάου',
		'GD':'Γρενάδα',
		'GL':'Γροιλανδία',
		'DK':'Δανία',
		'CG':'Δημοκρατία του Κονγκό',
		'DM':'Δομινίκα',
		'DO':'Δομινικανή Δημοκρατία',
		'EH':'Δυτική Σαχάρα',
		'EC':'Εκουαδόρ',
		'SV':'Ελ Σαλβαδόρ',
		'CH':'Ελβετία',
		'ER':'Ερυθραία',
		'EE':'Εσθονία',
		'ZM':'Ζάμπια',
		'ZW':'Ζιμπάμπουε',
		'AE':'Ηνωμένα Αραβικά Εμιράτα',
		'US':'Ηνωμένες Πολιτείες Αμερικής',
		'JP':'Ιαπωνία',
		'IN':'Ινδία',
		'ID':'Ινδονησία',
		'JO':'Ιορδανία',
		'IQ':'Ιράκ',
		'IR':'Ιράν',
		'IE':'Ιρλανδία',
		'GQ':'Ισημερινή Γουινέα',
		'IS':'Ισλανδία',
		'ES':'Ισπανία',
		'IL':'Ισραήλ',
		'IT':'Ιταλία',
		'KZ':'Καζακστάν',
		'CM':'Καμερούν',
		'KH':'Καμπότζη',
		'CA':'Καναδάς',
		'QA':'Κατάρ',
		'KY':'Κέιμαν Νήσοι',
		'CF':'Κεντροαφρικανική Δημοκρατία',
		'KE':'Κένυα',
		'CN':'Κίνα',
		'KG':'Κιργιζία',
		'KI':'Κιριμπάτι',
		'CO':'Κολομβία',
		'KM':'Κομόρες',
		'KP':'Κορέα, Βόρεια',
		'KR':'Κορέα, Νότια',
		'CR':'Κόστα Ρίκα',
		'CU':'Κούβα',
		'KW':'Κουβέιτ',
		'CW':'Κουρασάο',
		'HR':'Κροατία',
		'CY':'Κύπρος',
		'CD':'Λαϊκή Δημοκρατία του Κονγκό',
		'LA':'Λάος',
		'LS':'Λεσότο',
		'LV':'Λετονία',
		'BY':'Λευκορωσία',
		'LB':'Λίβανος',
		'LR':'Λιβερία',
		'LY':'Λιβύη',
		'LT':'Λιθουανία',
		'LI':'Λιχτενστάιν',
		'LU':'Λουξεμβούργο',
		'YT':'Μαγιότ',
		'MG':'Μαδαγασκάρη',
		'MO':'Μακάου',
		'MY':'Μαλαισία',
		'MW':'Μαλάουι',
		'MV':'Μαλδίβες',
		'ML':'Μάλι',
		'MT':'Μάλτα',
		'MA':'Μαρόκο',
		'MQ':'Μαρτινίκα',
		'MU':'Μαυρίκιος',
		'MR':'Μαυριτανία',
		'ME':'Μαυροβούνιο',
		'GB':'Μεγάλη Βρετανία',
		'MX':'Μεξικό',
		'MM':'Μιανμάρ (Βιρμανία)',
		'FM':'Μικρονησία (Ομόσπονδες Πολιτείες)',
		'MN':'Μογγολία',
		'MZ':'Μοζαμβίκη',
		'MD':'Μολδαβία',
		'MC':'Μονακό',
		'MS':'Μοντσερράτ',
		'BD':'Μπανγκλαντές',
		'BB':'Μπαρμπάντος',
		'BS':'Μπαχάμες',
		'BH':'Μπαχρέιν',
		'BZ':'Μπελίζ',
		'BJ':'Μπενίν',
		'BQ':'Μποναίρ, Άγιος Ευστάθιος και Σάμπα (BES νησιά)',
		'BW':'Μποτσουάνα',
		'BV':'Μπουβέ, Νησί',
		'BF':'Μπουρκίνα Φάσο',
		'BI':'Μπουρούντι',
		'BT':'Μπουτάν',
		'BN':'Μπρουνέι',
		'NA':'Ναμίμπια',
		'NR':'Ναουρού',
		'NZ':'Νέα Ζηλανδία',
		'NC':'Νέα Καληδονία',
		'NP':'Νεπάλ',
		'NF':'Νησί Νόρφολκ',
		'CC':'Νησιά Κόκος (Κήλινγκ)',
		'CK':'Νήσοι Κουκ',
		'MH':'Νήσοι Μάρσαλ',
		'GS':'Νήσοι Νότια Γεωργία και Νότιες Σάντουιτς',
		'PN':'Νήσοι Πίτκαιρν',
		'SB':'Νήσοι Σολομώντα',
		'FO':'Νήσοι Φερόες',
		'FK':'Νήσοι Φώκλαντ (Μαλβίνας)',
		'HM':'Νήσοι Χερντ και Μακντόναλντ',
		'AX':'Νήσοι Ώλαντ',
		'IM':'Νήσος του Μαν',
		'CX':'Νήσος των Χριστουγέννων',
		'NE':'Νίγηρας',
		'NG':'Νιγηρία',
		'NI':'Νικαράγουα',
		'NU':'Νιούε',
		'NO':'Νορβηγία',
		'ZA':'Νότια Αφρική',
		'SS':'Νότιο Σουδάν',
		'NL':'Ολλανδία',
		'OM':'Ομάν',
		'HN':'Ονδούρα',
		'WF':'Ουαλίς και Φουτουνά',
		'HU':'Ουγγαρία',
		'UG':'Ουγκάντα',
		'UZ':'Ουζμπεκιστάν',
		'UA':'Ουκρανία',
		'UY':'Ουρουγουάη',
		'PK':'Πακιστάν',
		'PS':'Παλαιστίνη, Κράτος της',
		'PW':'Παλάου',
		'PA':'Παναμάς',
		'PG':'Παπούα Νέα Γουινέα',
		'PY':'Παραγουάη',
		'PE':'Περού',
		'PL':'Πολωνία',
		'PT':'Πορτογαλία',
		'PR':'Πουέρτο Ρίκο',
		'CV':'Πράσινο Ακρωτήριο',
		'MK':'Πρώην Γιουγκοσλαβική Δημοκρατία της Μακεδονίας',
		'RE':'Ρεϋνιόν',
		'RW':'Ρουάντα',
		'RO':'Ρουμανία',
		'RU':'Ρωσία',
		'PM':'Σαιν Πιερ και Μικελόν',
		'WS':'Σαμόα',
		'ST':'Σάο Τομέ και Πρίνσιπε',
		'SA':'Σαουδική Αραβία',
		'SN':'Σενεγάλη',
		'RS':'Σερβία',
		'SC':'Σεϋχέλλες',
		'SG':'Σιγκαπούρη',
		'SL':'Σιέρα Λεόνε',
		'SK':'Σλοβακία',
		'SI':'Σλοβενία',
		'SO':'Σομαλία',
		'SZ':'Σουαζιλάνδη',
		'SD':'Σουδάν',
		'SE':'Σουηδία',
		'SR':'Σουρινάμ',
		'LK':'Σρι Λάνκα',
		'SY':'Συρία',
		'TW':'Ταϊβάν (Δημοκρατία της Κίνας)',
		'TH':'Ταϊλάνδη',
		'TZ':'Τανζανία',
		'TJ':'Τατζικιστάν',
		'TC':'Τερκς και Κέικος',
		'JM':'Τζαμάικα',
		'JE':'Τζέρσεϊ',
		'DJ':'Τζιμπουτί',
		'TG':'Τόγκο',
		'TK':'Τοκελάου',
		'TO':'Τόνγκα',
		'TV':'Τουβαλού',
		'TR':'Τουρκία',
		'TM':'Τουρκμενιστάν',
		'TT':'Τρινιντάντ και Τομπάγκο',
		'TD':'Τσαντ',
		'CZ':'Τσεχία',
		'TN':'Τυνησία',
		'YE':'Υεμένη',
		'PH':'Φιλιππίνες',
		'FI':'Φινλανδία',
		'FJ':'Φίτζι',
		'CL':'Χιλή',
		'HK':'Χονγκ Κονγκ',
		'GG':'Guernsey',
		'SH':'Saint Helena, Ascension and Tristan da Cunha',
		'SJ':'Svalbard and Jan Mayen',
		};

		var nationality_map = {
		'undefined':'Μη προσδιορισμένη',
		'GRC':'Έλληνας',
		'ENG':'Άγγλος',
		'EGY':'Αιγύπτιος',
		'ETH':'Αιθίοπας',
		'HTI':'Αϊτινός',
		'ALB':'Αλβανός',
		'DZA':'Αλγεριανός',
		'USA':'Αμερικάνος',
		'AND':'Ανδορρανός',
		'ARG':'Αργεντίνος',
		'ARM':'Αρμένιος',
		'AUS':'Αυστραλός',
		'AUT':'Αυστριακός',
		'AFG':'Αφγανός',
		'BEL':'Βέλγος',
		'VEN':'Βενεζουελιανός',
		'VNM':'Βιετναμέζος',
		'MMR':'Βιρμανός',
		'BOL':'Βολιβιανός',
		'NIR':'Βορειοιρλανδός',
		'PRK':'Βορειοκορεάτης',
		'BIH':'Βόσνιος, Ερζεγοβιανός',
		'BGR':'Βούλγαρος',
		'BRA':'Βραζιλιάνος',
		'GBR':'Βρετανός',
		'FRA':'Γάλλος',
		'DEU':'Γερμανός',
		'GEO':'Γεωργιανός',
		'GAB':'Γκαμπονέζος',
		'GHA':'Γκανέζος',
		'DNK':'Δανός',
		'DOM':'Δομινικανός',
		'ECU':'Εκουαδοριανός',
		'CHE':'Ελβετός',
		'EST':'Εσθονός',
		'ZWE':'Ζιμπαμπουανός',
		'JPN':'Ιάπωνας',
		'CIV':'Ιβοριανός',
		'IDN':'Ινδονήσιος',
		'IND':'Ινδός',
		'JOR':'Ιορδανός',
		'IRQ':'Ιρακινός',
		'IRN':'Ιρανός',
		'IRL':'Ιρλανδός',
		'ISL':'Ισλανδός',
		'ESP':'Ισπανός',
		'ISR':'Ισραηλινός',
		'ITA':'Ιταλός',
		'KAZ':'Καζακστανός',
		'CMR':'Καμερουνέζος',
		'KHM':'Καμποτζιανός',
		'CAN':'Καναδός',
		'QAT':'Καταρινός',
		'CAF':'Κεντροαφρικανός',
		'KEN':'Κενυάτης',
		'CHN':'Κινέζος',
		'COG':'Κογκολέζος',
		'COL':'Κολομβιανός',
		'CRI':'Κοσταρικανός',
		'CUB':'Κουβανός',
		'HRV':'Κροάτης',
		'CYP':'Κύπριος',
		'LVA':'Λετονός',
		'BLR':'Λευκορώσος',
		'LBN':'Λιβανέζος',
		'LBR':'Λιβεριανός',
		'LBY':'Λίβυος',
		'LUX':'Λουξεμβούργιος',
		'MYS':'Μαλαισιανός',
		'MLT':'Μαλτέζος',
		'MAR':'Μαροκινός',
		'MRT':'Μαυριτανός',
		'MNE':'Μαυροβούνιος',
		'MEX':'Μεξικάνος',
		'MNG':'Μογγόλος',
		'MDA':'Μολδαβός',
		'BGD':'Μπαγκλαντεσιανός',
		'BHS':'Μπαχαμιανός',
		'NZL':'Νεοζηλανδός',
		'NGA':'Νιγηριανός',
		'NIC':'Νικαραγουανός',
		'NOR':'Νορβηγός',
		'ZAF':'Νοτιοαφρικανός',
		'KOR':'Νοτιοκορεάτης',
		'NLD':'Ολλανδός',
		'WLS':'Ουαλός',
		'HUN':'Ούγγρος',
		'UGA':'Ουγκαντιανός',
		'UZB':'Ουζμπέκος',
		'UKR':'Ουκρανός',
		'URY':'Ουρουγουανός',
		'PAK':'Πακιστανός',
		'PSE':'Παλαιστίνιος',
		'PAN':'Παναμέζος',
		'PRY':'Παραγουανός',
		'PER':'Περουβιανός',
		'POL':'Πολωνός',
		'PRT':'Πορτογάλος',
		'ROU':'Ρουμάνος',
		'RUS':'Ρώσσος',
		'SLV':'Σαλβαδοριανός',
		'SAU':'Σαουδάραβας',
		'SEN':'Σενεγαλέζος',
		'SRB':'Σέρβος',
		'SGP':'Σιγκαπουριανός',
		'SCT':'Σκωτσέζος',
		'MKD':'Σλαβομακεδόνας',
		'SVK':'Σλοβάκος',
		'SVN':'Σλοβένος',
		'SOM':'Σομαλός',
		'SDN':'Σουδανός',
		'SWE':'Σουηδός',
		'LKA':'Σριλανκιανός',
		'SYR':'Σύριος',
		'TWN':'Ταϊβανός',
		'THA':'Ταϊλανδός',
		'TZA':'Τανζανός',
		'JAM':'Τζαμαϊκανός',
		'TKM':'Τουρκμάνος',
		'TUR':'Τούρκος',
		'CZE':'Τσέχος',
		'TUN':'Τυνήσιος',
		'YEM':'Υεμένος',
		'PHL':'Φιλιππινέζος',
		'FIN':'Φινλανδός',
		'CHL':'Χιλιανός',
		'PRI':'Afro-Puerto Rican',
		'AGO':'Angolan',
		'ATG':'Antiguans, Barbudans',
		'AZE':'Azerbaijani',
		'BHR':'Bahraini',
		'BRB':'Barbadian or Bajuns',
		'BLZ':'Belizean',
		'BEN':'Beninese',
		'BTN':'Bhutanese',
		'BRN':'Bruneian',
		'BFA':'Burkinabe',
		'BDI':'Burundian',
		'CPV':'Cape Verdian or Cape Verdean',
		'TCD':'Chadian',
		'COM':'Comoran',
		'DJI':'Djibouti',
		'ARE':'Emirian',
		'GNQ':'Equatoguinean',
		'ERI':'Eritrean',
		'FJI':'Fijian',
		'GMB':'Gambian',
		'GRD':'Grenadian',
		'GTM':'Guatemalan',
		'GNB':'Guinea-Bissauan',
		'GIN':'Guinean',
		'GUY':'Guyanese',
		'HND':'Honduran',
		'KIR':'I-Kiribati',
		'KNA':'Kittian and Nevisian',
		'KWT':'Kuwaiti',
		'KGZ':'Kyrgyz or Kirghiz',
		'LAO':'Lao or Laotian',
		'LIE':'Liechtensteiner',
		'LTU':'Lithuanian',
		'MDG':'Malagasy',
		'MWI':'Malawian',
		'MDV':'Maldivan',
		'MLI':'Malian',
		'MHL':'Marshallese',
		'MUS':'Mauritian',
		'FSM':'Micronesian',
		'MCO':'Monacan',
		'LSO':'Mosotho ',
		'BWA':'Motswana, Batswana',
		'MOZ':'Mozambican',
		'NAM':'Namibian',
		'NRU':'Nauruan',
		'NPL':'Nepalese',
		'NER':'Nigerien',
		'OMN':'Omani',
		'PLW':'Palauan',
		'PNG':'Papua New Guinean',
		'RWA':'Rwandan',
		'LCA':'Saint Lucian',
		'WSM':'Samoan',
		'SMR':'San Marinese',
		'STP':'Sao Tomean',
		'SYC':'Seychellois',
		'SLE':'Sierra Leonean',
		'SLB':'Solomon Islander',
		'SUR':'Surinamer',
		'SWZ':'Swazi',
		'TJK':'Tajik or Tadzhik',
		'TGO':'Togolese',
		'TON':'Tongan',
		'TTO':'Trinidadian or Tobagonian',
		'TUV':'Tuvaluan',
		'ZMB':'Zambian',
		};


		//****Deprecated Maps*****//
		var county_nationality_map = {
		'gr':'Greece',
		'aa':'Albania',
		'ae':'Algeria',
		'af':'Afghanistan',
		'ag':'Argentina',
		'at':'Australia',
		'au':'Austria',
		'be':'Belgium',
		'bl':'Brazil',
		'bn':'Bosnia and Hercegovina',
		'bo':'Bolivia',
		'bu':'Bulgaria',
		'bw':'Belarus',
		'cc':'China',
		'ci':'Croatia',
		'cl':'Chile',
		'cn':'Canada',
		'cu':'Cuba',
		'cy':'Cyprus',
		'dk':'Denmark',
		'er':'Estonia',
		'fi':'Finland',
		'fr':'France',
		'gs':'Georgia (Republic)',
		'gw':'Germany',
		'hu':'Hungary',
		'ic':'Iceland',
		'ie':'Ireland',
		'ii':'India',
		'iq':'Iraq',
		'ir':'Iran',
		'is':'Israel',
		'it':'Italy',
		'ja':'Japan',
		'jm':'Jamaica',
		'jo':'Jordan',
		'ke':'Kenya',
		'kn':'Korea (North)',
		'ko':'Korea (South)',
		'kz':'Kazakhstan',
		'le':'Lebanon',
		'lh':'Liechtenstein',
		'li':'Lithuania',
		'lu':'Luxembourg',
		'lv':'Latvia',
		'mc':'Monaco',
		'mm':'Malta',
		'mo':'Montenegro',
		'mr':'Morocco',
		'mv':'Moldova',
		'mx':'Mexico',
		'ne':'Netherlands',
		'no':'Norway',
		'np':'Nepal',
		'nq':'Nicaragua',
		'nr':'Nigeria',
		'nz':'New Zealand',
		'pe':'Peru',
		'pk':'Pakistan',
		'pl':'Poland',
		'pn':'Panama',
		'po':'Portugal',
		'py':'Paraguay',
		'qa':'Qatar',
		'rb':'Serbia',
		'rm':'Romania',
		'ru':'Russia (Federation)',
		'sa':'South Africa',
		'si':'Singapore',
		'sp':'Spain',
		'su':'Saudi Arabia',
		'sw':'Sweden',
		'sy':'Syria',
		'sz':'Switzerland',
		'th':'Thailand',
		'ti':'Tunisia',
		'tk':'Turkmenistan',
		'ts':'United Arab Emirates',
		'tu':'Turkey',
		'ua':'Egypt',
		'un':'Ukraine',
		'uy':'Uruguay',
		'uz':'Uzbekistan',
		'vc':'Vatican City',
		've':'Venezuela',
		'vm':'Vietnam',
		'vp':'Various places',
		'xn':'Macedonia',
		'xo':'Slovakia',
		'xr':'Czech Republic',
		'xv':'Slovenia',
		'xx':'No place, unknown, or undetermined',
		'xxc':'Canada',
		'xxk':'United Kingdom',
		'xxu':'United States',
		};
